Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2019-11, with the labels that each got.

#860 use "generic" image for deployments
  .travis.yml
Labels: ready to merge, waiting for review

#851 [SC-1936] use course scope throughout the platform
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1568021901926-AddCourseRoles.js
  migrations/1569423562190-AddScopePermissionsViewPermissionToCourseTeachers.js
  package-lock.json
  package.json
  src/services/helpers/scopePermissions/ScopeListService.js
  src/services/helpers/scopePermissions/ScopeMembersService.js
  src/services/helpers/scopePermissions/ScopePermissionService.js
  src/services/helpers/scopePermissions/ScopeService.js
  src/services/helpers/scopePermissions/hooks/checkScopePermissions.js
  src/services/helpers/scopePermissions/hooks/index.js
  src/services/helpers/scopePermissions/hooks/lookupScope.js
  src/services/helpers/scopePermissions/hooks/rejectQueryingForOtherUsers.js
  src/services/helpers/scopePermissions/hooks/util/resolveScope.js
  src/services/helpers/scopePermissions/index.js
  src/services/role/services/permissions.js
  src/services/user-group/index.js
  src/services/user-group/services/courseMembers.js
  src/services/user-group/services/coursePermission.js
  src/services/user-group/services/courseScopeLists.js
  test/services/courses/services/courseMembers.test.js
  test/services/courses/services/coursePermission.test.js
  test/services/courses/services/scopelist.test.js
  test/services/helpers/scopePermissions/hooks/index.test.js
  test/services/helpers/scopes/ScopeMembersService.test.js
  test/services/helpers/scopes/ScopeService.test.js
  test/services/helpers/scopes/hooks.test.js
  test/services/helpers/scopes/hooks/checkScopePermissions.js
  test/services/helpers/scopes/hooks/lookupScope.js
  test/services/helpers/scopes/hooks/rejectQueryingForOtherUsers.js
Labels: needs data protection review

#863 SC-2440 add migration for Enter The Cloud game
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1572964724172-add-enterthecloud-start-permission.js
Labels: auto_merged

#849 SC-1600-tasks-without-duedate
  src/services/homework/model.js
Labels: ready to merge

#862 Feature/sc 2212 class successor removal fix
  backup/setup/migrations.json
  migrations/1572963566569-remove-broken-class-successor-links.js
  src/services/user-group/services/classSuccessor.js
  test/services/user-group/services/classSuccessor.test.js
Labels: ready to merge

#838 Feature/sc 2305 oauth localtest
  package-lock.json
  test/services/oauth2/hydra.js
  test/services/oauth2/index.test.js
  test/services/oauth2/mock.js
  test/services/oauth2/oauth2MockServer.js
Labels: ready to merge

#848 Feature/sc 1944 mongoose update v 5
  package-lock.json
  package.json
  src/helper/compare.js
  src/hooks/index.js
  src/jobs/rss-news.js
  src/services/account/hooks/index.js
  src/services/fileStorage/model.js
  src/services/fileStorage/proxy-service.js
  src/services/fileStorage/utils/filePermissionHelper.js
  src/services/homework/copy-service.js
  src/services/homework/hooks/index.js
  src/services/homework/hooks/submissions.js
  src/services/homework/model.js
  src/services/lesson/hooks/copy.js
  src/services/lesson/model.js
  src/services/link/link-model.js
  src/services/ltiTool/model.js
  src/services/news/index.js
  src/services/news/model.js
  src/services/pseudonym/hooks/index.js
  src/services/pseudonym/model.js
  src/services/releases/release-model.js
  src/services/rocketChat/hooks/index.js
  src/services/rocketChat/model.js
  src/services/role/model.js
  src/services/school/model.js
  src/services/statistic/index.js
  src/services/teams/events/user.js
  src/services/teams/hooks/index.js
  src/services/teams/index.js
  src/services/teams/model.js
  src/services/user-group/hooks/courses.js
  src/services/user-group/model.js
  src/services/user-group/services/course-copy-service.js
  src/services/user/model.js
  src/sockets/clipboard/clipboard-model.js
  src/utils/database.js
  test/helper/compare.test.js
  test/jobs/rss-news/index.integration.test.js
  test/services/helpers/services/classes.js
  test/services/homework/index.test.js
  test/services/news/hooks/news.hooks.test.js
  test/services/pseudonym/index.test.js
  test/services/roster/index.test.js
  test/services/teams/events/index.test.js
  test/services/teams/index.test.js
  test/services/user-group/index.test.js
  test/services/user/services/AdminUsers.test.js
Labels: ready to merge

#864 Feature/sc 2199 service template
  package-lock.json
  src/services/serviceTemplate/hooks/customHook.js
  src/services/serviceTemplate/hooks/index.js
  src/services/serviceTemplate/index.js
  src/services/serviceTemplate/model.js
  src/services/serviceTemplate/schemas/index.js
  src/services/serviceTemplate/schemas/serviceTemplate.create.json
  src/services/serviceTemplate/schemas/serviceTemplate.patch.json
  src/services/serviceTemplate/services/modelService.js
Labels: ready to merge

#829 Greenkeeper/csv parse 4.6.3
  package-lock.json
  package.json
Labels: greenkeeper, ready to merge

#830 Greenkeeper/cross env 6.0.3
  package-lock.json
  package.json
Labels: greenkeeper, ready to merge

#867 class model service implementation
  src/services/user-group/hooks/classes.js
  src/services/user-group/hooks/helpers/classHooks.js
  src/services/user-group/index.js
  src/services/user-group/services/classModelService.js
  src/services/user-group/services/classes.js
  test/services/user-group/hooks/classes.test.js
  test/services/user-group/index.test.js
Labels: ready to merge

#840 Roster changes for iframe depseudonymization
  src/services/ltiTool/model.js
  src/services/pseudonym/hooks/index.js
  src/services/roster/hooks/index.js
  src/services/roster/index.js
Labels: ready to merge

#872 allow to skip travis stages
  .travis.yml
Labels: ready to merge

#832 Greenkeeper/codecov 3.6.1
  package-lock.json
  package.json
Labels: greenkeeper, ready to merge

#885 Feature/2802 courses modelservice
  package-lock.json
  src/hooks/index.js
  src/services/user-group/index.js
  src/services/user-group/services/courseModelService.js
  src/services/user-group/services/courses.js
  src/services/user/hooks/index.js
  test/app.hooks.test.js
  test/services/roster/index.test.js
Labels: waiting for review
