Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2019-09, with the labels that each got.

#768 Greenkeeper/simple oauth2 2.3.0
  package-lock.json
  package.json
Labels: greenkeeper

#777 Add sentry error reporting
  package-lock.json
  package.json
  src/app.js
  src/helper/version.js
  src/services/version/index.js
Labels: ready to merge

#773 fixed timestamps
  backup/setup/ltitools.json
  backup/setup/migrations.json
  backup/setup/roles.json
Labels: ready to merge

#721 Feature/sc 1625 migration for persist files by copied courses
  migrations/1564493063114-persist_files_by_copied_courses.js
  migrations/helpers/DatabaseTaskTemplate.js
  migrations/helpers/OutputLogTemplate.js
  src/services/fileStorage/utils/copyFile.js
Labels: ready to merge

#790 feature/SC-1796 part 2
  src/services/school/logic/year.js
  src/services/user-group/hooks/classes.js
  src/services/user-group/model.js
  src/services/user-group/services/classSuccessor.js
  test/services/helpers/services/classes.js
  test/services/user-group/index.test.js
Labels: ready to merge

#799 add migations to version
  package.json
  src/services/version/index.js
  startup.sh
Labels: waiting for review

#818 fix authentication logic
  src/app.hooks.js
  src/services/authentication/logic/index.js
Labels: waiting for review

#805 Add new sorting function and tests
  src/services/user-group/hooks/classes.js
  src/services/user-group/hooks/helpers/classHooks.js
  test/services/user-group/hooks/classes.test.js
  test/services/user-group/index.test.js
Labels: ready to merge

#791 SC-1518 Test-cases for unpublished news
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1567610344053-addNewsCreateToAdmin.js
  src/services/news/hooks/unpublishedNews.hooks.js
  src/services/news/index.js
  test/services/news/index.test.js
Labels: ready to merge

#809 Migration remove research and dateOfResearch
  backup/setup/migrations.json
  migrations/1568731418288-remove-research-and-dateofresearchconsent.js
Labels: waiting for review
