Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-03, with the labels that each got.

#1011 Hotfix/22.2.5
  package-lock.json
  package.json
  src/services/homework/copy-service.js
  src/services/homework/hooks/copy.js
  src/services/homework/hooks/index.js
  src/services/lesson/services/LessonCopyService.js
  src/services/user-group/services/course-copy-service.js
  test/services/helpers/services/homeworks.js
  test/services/helpers/services/index.js
  test/services/helpers/services/lessons.js
  test/services/helpers/services/submissions.js
  test/services/helpers/testObjects.js
  test/services/homework/copy-service.test.js
  test/services/homework/index.test.js
  test/services/lessons/index.test.js
  test/services/lessons/lessonCopyService.test.js
Labels: hotfix: do not merge here, waiting for review

#1004 Greenkeeper/nodemon 2.0.2
  package-lock.json
  package.json
Labels: ready to merge

#994 Feld "key" ist nicht bei allen Tools notwendig
  src/services/ltiTool/model.js
Labels: ready to merge

#1008 Config as singleton SC-3348
  package-lock.json
  package.json
  src/app.hooks.js
  src/app.js
  src/helper/version.js
  src/services/account/services/jwtTimerService.js
  src/services/authentication/hooks/index.js
  src/services/authentication/strategies/ApiKeyStrategy.js
  src/services/sync/strategies/TSP/TSP.js
  src/services/user/hooks/publicTeachers.js
  src/services/videoconference/index.js
  src/services/videoconference/logic/server.js
  src/utils/redis.js
  test/app.hooks.redis.test.js
  test/app.hooks.test.js
  test/services/account/services/jwtTimerService.test.js
  test/services/authentication/apiKeyStrategy.test.js
  test/services/authentication/hooks/index.test.js
  test/services/user/unit.test.js
  test/services/videoconference/index.test.js
  test/utils/redis/redis.test.js
Labels: ready to merge

#1043 SC-3609 extend jwt lifetime for apps
  config/default.schema.json
  src/app.hooks.js
  src/services/account/services/SupportJWTService.js
  src/services/account/services/jwtTimerService.js
  src/services/authentication/hooks/index.js
  src/services/authentication/index.js
  src/utils/redis.js
  test/app.hooks.redis.test.js
  test/services/account/services/jwtTimerService.test.js
  test/services/authentication/hooks/index.test.js
Labels: ready to merge

#1082 SC-3678 handle invalid jwt
  src/utils/redis.js
Labels: ready to merge

#1009 Feature/sc 3505/add nexboard services
  config/default.schema.json
  package-lock.json
  package.json
  src/helper/version.js
  src/services/index.js
  src/services/nexboard/hooks/index.js
  src/services/nexboard/index.js
  src/services/nexboard/services/Boards.js
  src/services/nexboard/services/Projects.js
  src/services/nexboard/services/index.js
  src/services/nexboard/utils/Nexboard.js
  test/app.hooks.redis.test.js
  test/services/account/index.test.js
  test/services/account/services/jwtTimerService.test.js
  test/services/authentication/apiKeyStrategy.test.js
  test/services/authentication/authentication.test.js
  test/services/authentication/hooks/index.test.js
  test/services/courses/services/coursePermission.test.js
  test/services/datasources/datasources.test.js
  test/services/help/index.test.js
  test/services/helpers/login.js
  test/services/nexboard/MockServer.js
  test/services/nexboard/index.test.js
  test/services/nexboard/standAloneMock.js
  test/services/sync/strategies/webuntis/WebUntisSyncer.test.js
  test/services/webuntis/webuntisMetadataService.test.js
  test/utils/redis/redis.test.js
Labels: ready to merge

#1061 Feature/sc 3575 messenger sync
  backup/setup/migrations.json
  backup/setup/roles.json
  config/default.schema.json
  migrations/1584614792049-add-messenger-sync-permissions.js
  package-lock.json
  package.json
  src/app.js
  src/services/index.js
  src/services/messengerSync/consumer.js
  src/services/messengerSync/eventListener.js
  src/services/messengerSync/index.js
  src/services/messengerSync/services/messengerTokenService.js
  src/services/messengerSync/services/schoolSyncService.js
  src/services/messengerSync/testConsumer.js
  src/services/messengerSync/utils.js
  src/services/school/model.js
  src/utils/rabbitmq.js
  test/services/helpers/services/teams.js
  test/services/helpers/testObjects.js
  test/services/messengerSync/rabbitmqMock.js
  test/services/messengerSync/services/schoolSyncService.test.js
  test/services/messengerSync/utils.test.js
Labels: waiting for review

#869 SC-2447 | Added EBS (Alert) System
  config/default.schema.json
  src/helper/externalApiRequest.js
  src/services/alert/MessageProvider/status/index.js
  src/services/alert/adapter/index.js
  src/services/alert/adapter/message.js
  src/services/alert/adapter/status.js
  src/services/alert/cache.js
  src/services/alert/index.js
  src/services/index.js
Labels: ready to merge

#1029 SC-3574 | Add chat option to course
  src/services/teams/model.js
  src/services/user-group/model.js
Labels: ready to merge

#1102 SC-3791 | dashboard rework homeschooling
  src/services/homework/hooks/index.js
Labels: ready to merge

#1093 gitflow-feature-stash: fix-test-deployment
  deploy.sh
Labels: ready to merge

#1103 implement initial course tests
  src/services/user-group/index.js
  src/services/user-group/services/courses.js
  src/utils/index.js
  src/utils/modelServices.js
  test/services/user-group/services/courseModelService.test.js
  test/services/user-group/services/courses.test.js
Labels: waiting for review
