Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-06, with the labels that each got.

#1324 Feature/SC-3942 schulcloud-server about pagination teams page
  src/services/teams/hooks/index.js
  src/services/teams/services/admin.js
  test/services/teams/services/admin.test.js
Labels: ready to merge

#1369 hotfix 23.1.5
  package-lock.json
  package.json
  src/services/fileStorage/proxy-service.js
Labels: ready to merge

#1355 SC-4010 - Erweiterung der API / Servertests
  test/routes/routes.test.js
  test/routes/whitelist.js
Labels: ready to merge

#1351 SC-4513 - filter schools for unauthorized requests
  src/hooks/index.js
  src/services/account/hooks/index.js
  src/services/account/services/accountApiService.js
  src/services/school/hooks/index.js
  test/services/school/index.test.js
Labels: ready to merge

#1375 SC-4552 Fix server logs showing sensitive data
  src/middleware/errorHandler.js
Labels: waiting for review

#1380 Hotfix/23.2.1 SC-4720 SC-4606 Remove ShortLinks-Service from registrastion links
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/link/index.js
Labels: waiting for review

#1387 fix missing env
  config/default.schema.json
  package-lock.json
  package.json
  src/services/etherpad/hooks/Pad.js
Labels: WIP

#1381 SC-3926 remove x-powered-by header
  src/app.js
Labels: ready to merge

#1376 add change to feathers packages 4.5.3
  package-lock.json
  package.json
Labels: ready to merge

#1400 etherpad migration
  migrate_etherpad.js
  package-lock.json
  package.json
Labels: WIP

#1346 Feature/sc 4041 studentlist visibility
  backup/setup/migrations.json
  backup/setup/roles.json
  config/default.json
  config/default.schema.json
  config/test.json
  migrations/1591276239414-add-SCHOOL_PERMISSION_VIEW-permission.js
  package-lock.json
  src/hooks/index.js
  src/services/role/hooks/userRoles.js
  src/services/role/index.js
  src/services/role/services/userPermissions.js
  src/services/role/services/userRoles.js
  src/services/role/utils/permissions.js
  src/services/school/index.js
  src/services/school/model.js
  src/services/school/services/permissions.js
  src/services/user/index.js
  src/services/user/services/AdminUsers.js
Labels: ready to merge

#1398 Feature/sc 4192 class queries
  CHANGELOG.md
  src/hooks/index.js
  test/services/user-group/services/classes.test.js
Labels: ready to merge

#1406 dont join defaultchannels
  src/services/rocketChat/services/rocketChatUser.js
Labels: ready to merge

#1399 Feature/sc 4577 datenschutz per school
  CHANGELOG.md
  src/app.js
  src/services/base64Files/hooks/index.js
  src/services/base64Files/hooks/setDownloadHeaders.js
  src/services/base64Files/index.js
  src/services/base64Files/models.js
  src/services/consent/hooks/consentversions.js
  src/services/consent/hooks/consentversionsModelHooks.js
  src/services/consent/index.js
  src/services/consent/model.js
  src/services/consent/services/consentVersionService.js
  src/services/consent/services/index.js
  src/services/index.js
Labels: needs data protection review, waiting for review

#1410 feature/SC-4577/Add missing filename
  src/services/base64Files/hooks/setDownloadHeaders.js
  src/services/base64Files/models.js
  src/services/consent/services/consentVersionService.js
Labels: needs data protection review, waiting for review

#1412 feature/SC-4987/pwgen mark as deprecated
  package.json
  src/services/account/index.js
  test/routes/whitelist.js
Labels: ready to merge

#1422 feature/SC-5011/fix link test
  test/services/link/index.test.js
Labels: waiting for review

#1426 change content url
  compose-server-test.dummy
Labels: ready to merge

#1429 Hotfix/sc 5054 registration fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/consent/services/consentVersionService.js
  test/services/link/index.test.js
Labels: WIP

#1433 Fix broken test
  src/services/user/firstLogin.js
  test/routes/whitelist.js
Labels: ready to merge

#1419 feature/SC-5012/fix duplicated mock ports
  test/services/etherpad/MockServer.js
Labels: ready to merge

#1366 Prevent logging private user data
  src/services/homework/hooks/submissions.js
Labels: ready to merge

#1436 Hotfix/23.4.5 fix ldap self service
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/school/hooks/index.js
Labels: WIP

#1404 SC-4553 Fix exposed password in logs - service: moodle_mobile_app
  src/middleware/errorHandler.js
Labels: ready to merge

#1310 feature/SC-4168/Limit Access to Materials Service
  src/services/content/hooks/materials.js
  src/services/content/hooks/redirect.js
  src/services/content/hooks/resources.js
  src/services/content/hooks/search.js
  src/services/content/index.js
  test/services/content/material.test.js
Labels: ready to merge

#1440 Feature/sc 5007 transaction for ldap activation
  src/services/ldap/hooks/index.js
  src/services/ldap/index.js
Labels: WIP

#1423 SC-4520 - extend me service
  src/services/helpers/utils/externallyManaged.js
  src/services/helpers/utils/index.js
  src/services/me/index.js
Labels: ready to merge

#1414 Feature/sc 4456 add missing user route tests
  test/services/me/services/meService.test.js
  test/services/user/services/AdminUsers.test.js
  test/services/user/services/MailRegistrationLink.test.js
  test/services/user/services/UserLinkImportService.test.js
  test/services/user/services/userService.test.js
Labels: ready to merge

#1457 SC-4520 - fix small bug in me service
  src/services/me/index.js
Labels: ready to merge

#1458 Hotfix SC-5239
  package-lock.json
  package.json
  src/services/user/registration.js
  test/services/user/registration.test.js
Labels: waiting for review

#1460 SC-4142 TSP sync performance improvements
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1593068289663-addTspSyncIndexes.js
  src/helper/externalSourceSchema.js
  src/services/school/model.js
  src/services/sync/strategies/TSP/TSPSchoolSyncer.js
  src/services/user/model/user.schema.js
Labels: ready to merge

#1461 [SC-4973] rename FEATURE_ADMIN_TOGGLE_STUDENT_VISIBILITY
  config/default.json
  config/default.schema.json
  config/test.json
  src/services/role/index.js
  src/services/school/index.js
Labels: waiting for review

#1411 SC-4456 route tests fix
  test/routes/routes.test.js
  test/routes/whitelist.js
Labels: ready to merge
