Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-11, with the labels that each got.

#1851 Hotfix/1/SC-2710 - Custom Timezone
  CHANGELOG.md
  src/services/school/hooks/index.js
  src/services/school/hooks/lookupSchool.js
  src/services/school/model.js
  src/services/user/registration.js
  test/services/helpers/services/schools.js
  test/services/school/index.test.js
  test/services/user/registration.test.js
Labels: auto update, waiting for review

#1906 quickfix - adminUser search fix
  src/services/user/services/AdminUsers.js
Labels: auto update, ready to merge

#1904 Feature/sc 7555 move user and account to trashbin
  src/components/user/repo/db/trashbin.schema.js
  src/components/user/repo/trashbin.repo.js
  src/components/user/repo/user.repo.js
  src/components/user/services/index.js
  src/components/user/services/trashbin.service.v2.js
  src/components/user/services/user.service.v2.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
Labels: WIP

#1883 SC-7331 Introduce axios, remove request-promise-native in status api
  CHANGELOG.md
  package-lock.json
  package.json
  src/helper/apiHelper.js
  src/services/alert/MessageProvider/status/index.js
  src/services/alert/MessageProvider/status/statusApi.js
Labels: ready to merge

#1795 SC-6690 - refactors the edu-sharing connector
  CHANGELOG.md
  src/services/edusharing/index.js
  src/services/edusharing/logic/connector.js
  src/services/edusharing/services/EduSharingConnector.js
  src/services/edusharing/services/EduSharingResponse.js
  src/services/edusharing/services/MerlinTokenGenerator.js
  test/services/edusharing/EduSharingConnector.test.js
  test/services/edusharing/hooks/index.js
  test/services/edusharing/mock/response-auth.json
  test/services/edusharing/mock/response-node.json
Labels: WIP

#1916 SC-6690 - set defaults to fix server not starting
  CHANGELOG.md
  config/default.schema.json
Labels: ready to merge

#1912 Hotfix SC-7638
  CHANGELOG.md
  src/services/user/hooks/registrationPins.js
Labels: waiting for review

#1919 Ce/cleanup versions
  CHANGELOG.md
  package-lock.json
  package.json
Labels: WIP

#1909 SC-7353 - fix course sharing
  CHANGELOG.md
  src/services/user-group/services/course-copy-service.js
  test/services/courses/services/courseCopy.test.js
Labels: auto update, waiting for review

#1921 SC-5476 Extend tests for Matrix messenger config and permission service
  CHANGELOG.md
  test/services/messenger/services/messengerConfigService.test.js
  test/services/messenger/services/messengerPermissionService.test.js
Labels: ready to merge

#1920 SC-7615 - reduces erros in lernstore
  CHANGELOG.md
  src/services/edusharing/services/EduSharingConnector.js
  test/services/edusharing/EduSharingConnector.test.js
Labels: ready to merge

#1928 Hotfix/3/sc 7683/add log metrics and fix errors
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/app.js
  src/configuration/MemorySchedule.js
  src/configuration/index.js
  src/errors/utils.js
  src/services/rocketChat/services/rocketChatChannel.js
  src/utils/systemInfo.js
  startup.sh
Labels: waiting for review

#1894 Feature/sc 7413/cleanup code
  CHANGELOG.md
  src/index.js
  src/logger/index.js
  src/logger/utils.js
  src/utils/processEvents.js
Labels: auto update, ready to merge, waiting for review

#1929 Hotfix/3/sc 7695/secure csv user patches
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/CSVSyncer.js
  test/services/helpers/testObjects.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Labels: waiting for review

#1798 SC-5900: move schul-cloud specific logic
  CHANGELOG.md
  config/default.schema.json
  src/services/messengerSync/consumer.js
  src/services/messengerSync/eventListener.js
  src/services/messengerSync/producer.js
  src/services/messengerSync/services/messengerTokenService.js
  src/services/messengerSync/utils.js
  src/services/user/hooks/userService.js
  src/utils/array.js
  test/services/messengerSync/consumer.test.js
  test/services/messengerSync/services/messengerTokenService.test.js
  test/services/messengerSync/services/schoolSyncService.test.js
  test/services/messengerSync/utils.test.js
Labels: auto update, ready to merge

#1942 SC - 7205 - create new data seed for QA
  CHANGELOG.md
  backup/setup/accounts.json
  backup/setup/analytics.json
  backup/setup/classes.json
  backup/setup/consents_history.json
  backup/setup/coursegroups.json
  backup/setup/courses.json
  backup/setup/directories.json
  backup/setup/files.json
  backup/setup/gradelevels.json
  backup/setup/helpdocuments.json
  backup/setup/homeworks.json
  backup/setup/keys.json
  backup/setup/lessons.json
  backup/setup/links.json
  backup/setup/newshistories.json
  backup/setup/problems.json
  backup/setup/pseudonyms.json
  backup/setup/registrationpins.json
  backup/setup/rocketchatchannels.json
  backup/setup/rocketchatusers.json
  backup/setup/schools.json
  backup/setup/teams.json
  backup/setup/users.json
  backup/setup/users_history.json
  backup/setup/webuntismetadatas.json
  package-lock.json
Labels: auto update

#1924 SC-7572 - Find /users route after hooks - extremely slow
  CHANGELOG.md
  src/services/user/hooks/userService.js
  test/services/user/hooks/userService.hooks.test.js
Labels: auto update, ready to merge

#1946 SC-7370 Add optional rootPath attribute to iserv-idm strategy
  CHANGELOG.md
  src/services/ldap/strategies/iserv-idm.js
Labels: waiting for review

#1949 SC-7614 - creates documentation for edu-sharing endpoints
  CHANGELOG.md
  src/services/edusharing/docs/openapi.yaml
Labels: ready to merge

#1956 SC-7555 build app classes, facade
  src/common/disallow.hook.js
  src/components/user/index.js
  src/components/user/repo/account.repo.js
  src/components/user/repo/index.js
  src/components/user/repo/trashbin.repo.js
  src/components/user/repo/user.repo.js
  src/components/user/services/user.service.v2.integration.test.js
  src/components/user/services/user.service.v2.js
  src/components/user/uc/users.facade.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
  src/services/account/model.js
Labels: WIP

#1958 Hotfix/2/sc 7395 invalid paging cookie fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap/strategies/general.js
Labels: WIP, hotfix: do not merge here

#1954 ARC-137 avoid DoS on alerts in error state
  CHANGELOG.md
  src/services/alert/cache.js
Labels: ready to merge

#1953 SC-6596 Remove school from messenger permission path
  CHANGELOG.md
  src/services/messenger/index.js
  src/services/messenger/services/messengerPermissionService.js
  test/services/messenger/services/messengerPermissionService.test.js
Labels: ready to merge, waiting for review

#1922 SC-4666 - LDAP pool sync
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSystemSyncer.js
Labels: waiting for review

#1951 SC-4667 LDAP delta sync
  CHANGELOG.md
  src/services/ldap/strategies/deltaSyncUtils.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/iserv-idm.js
  src/services/ldap/strategies/iserv.js
  src/services/sync/strategies/LDAPSchoolSyncer.js
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSystemSyncer.js
  src/services/sync/strategies/Syncer.js
  src/services/sync/strategies/SystemSyncer.js
  src/services/system/model.js
  test/services/ldap/strategies/deltaSyncUtils.test.js
  test/services/ldap/strategies/iserv-idm.test.js
Labels: ready to merge

#1955 Feature/SC-7614 - edusharing documentation
  CHANGELOG.md
  src/services/edusharing/docs/openapi.yaml
Labels: auto update, ready to merge

#1952 Feature/sc 7571 generate link druckbogen
  CHANGELOG.md
  src/services/link/index.js
  src/services/user/index.js
  src/services/user/services/QrRegistrationLinks.js
  src/services/user/services/QrRegistrationLinksLegacyClient.js
  src/services/user/services/UsersModelService.js
  src/services/user/services/index.js
  test/services/user/services/QrRegistrationLinks.test.js
  test/services/user/services/QrRegistrationLinksLegacyClient.test.js
Labels: ready to merge

#1960 Feature/SC-7555 - delete user trashbin dr
  src/components/user/index.js
  src/components/user/repo/account.repo.js
  src/components/user/repo/index.js
  src/components/user/repo/trashbin.repo.js
  src/components/user/repo/user.repo.js
  src/components/user/services/index.js
  src/components/user/services/user.service.v2.integration.test.js
  src/components/user/services/user.service.v2.js
  src/components/user/uc/users.facade.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
  src/services/user/services/AdminUsers.js
Labels: WIP

#1964 ARC-138 fix changelog action
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: ready to merge

#1966 feature/SC-7555 - Updated unit tests
  src/components/user/uc/users.uc.unit.test.js
Labels: WIP

#1971 Bugfix/SC-1589 - Trim strings to avoid empty team names
  CHANGELOG.md
  src/services/teams/model.js
Labels: auto update, ready to merge

#1974 Feature/SC-7573 route hash broken promise chain
  CHANGELOG.md
  src/services/helpers/hash.js
  test/services/user/registration.test.js
Labels: ready to merge

#1972 Fix audience of the jwt for new organisation name.
  CHANGELOG.md
  config/default.schema.json
  src/middleware/errorHandler.js
  src/services/authentication/docs/openapi.yaml
  src/services/authentication/logic/index.js
Labels: auto update, ready to merge

#1970 set request logging enabled for development only
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  config/development.json
Labels: auto update, waiting for review

#1980 feature/SC-7884 - Authentication error when accessing any nuxt page in the client
  CHANGELOG.md
  src/services/me/docs/openapi.yaml
  src/services/user/docs/registration.openapi.yaml
Labels: ready to merge

#1977 Hotfix/SC-7714 - xss risk
  CHANGELOG.md
  package-lock.json
  package.json
  src/utils/sanitizeHtml.js
  test/utils/sanitizeHtml.test.js
Labels: ready to merge

#1764 SC-6294 added typescript dependencies, configuration and update run scripts (…
  .eslintrc.js
  .gitignore
  .mocharc.js
  .nodemon.json
  .nycrc.json
  .prettierignore
  .prettierrc.js
  CHANGELOG.md
  Dockerfile
  package-lock.json
  package.json
  src/services/sync/strategies/CSVSyncer.js
  test/app.test.js
  test/app.test.ts
  tsconfig.json
Labels: ready to merge

#1986 move request helper to more present location
  CHANGELOG.md
  config/default.schema.json
  config/globals.js
  src/externalServices/apiHelper.js
  src/externalServices/index.js
  src/externalServices/statusApi.js
  src/helper/externalApiRequest.js
  src/services/alert/MessageProvider/status/index.js
  src/services/fileStorage/proxy-service.js
Labels: auto update, ready to merge, waiting for review

#1988 facade locator
  CHANGELOG.md
  src/app.js
  src/utils/facadeLocator.js
  test/utils/facadeLocator/facadeLocator.integration.test.js
  test/utils/facadeLocator/facadeLocator.unit.test.js
Labels: auto update, ready to merge

#1911 Feature/sc-7555 - delete user with trashbin
  .mocharc.js
  CHANGELOG.md
  src/app.js
  src/components/index.js
  src/components/user/index.js
  src/components/user/repo/account.repo.integration.test.js
  src/components/user/repo/account.repo.js
  src/components/user/repo/db/trashbin.schema.js
  src/components/user/repo/index.js
  src/components/user/repo/trashbin.repo.integration.test.js
  src/components/user/repo/trashbin.repo.js
  src/components/user/repo/user.repo.integration.test.js
  src/components/user/repo/user.repo.js
  src/components/user/services/index.js
  src/components/user/services/user.service.v2.integration.test.js
  src/components/user/services/user.service.v2.js
  src/components/user/uc/userRoles.uc.js
  src/components/user/uc/userRoles.unit.test.js
  src/components/user/uc/users.facade.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
  src/services/account/model.js
  src/services/user/model/user.schema.js
  src/services/user/services/AdminUsers.js
Labels: auto update, waiting for review

#1996 deactivate api validation for development environment
  config/development.json
Labels: auto update, ready to merge

#1930 Add migration to allow counties in states
  .eslintignore
  .prettierignore
  CHANGELOG.md
  backup/setup/federalstates.json
  backup/setup/migrations.json
  backup/setup/schools.json
  migrations/1604574963243-seedFederalStatesWithCounties.js
  migrations/helpers/counties051120.json
  src/services/account/docs/openapi.yaml
  src/services/federalState/countyModel.js
  src/services/federalState/model.js
  src/services/school/hooks/index.js
  src/services/school/model.js
  test/services/school/index.test.js
Labels: waiting for review

#1982 Hotfix/5/SC-7773 antivirus config
  CHANGELOG.md
  config/default.schema.json
  config/development.json
  config/globals.js
  package-lock.json
  package.json
  src/services/fileStorage/proxy-service.js
  src/services/fileStorage/strategies/awsS3.js
  test/services/fileStorage/aws/awsS3.test.js
Labels: waiting for review

#1979 SC-7838 - delete user pseudonyms
  CHANGELOG.md
  src/components/pseudonym/repo/index.js
  src/components/pseudonym/repo/pseudonym.repo.integration.test.js
  src/components/pseudonym/repo/pseudonym.repo.js
  src/components/pseudonym/uc/pseudonym.uc.js
  src/services/pseudonym/index.js
  test/services/helpers/services/index.js
  test/services/helpers/services/ltiTools.js
  test/services/helpers/services/pseudonyms.js
  test/services/helpers/testObjects.js
Labels: auto update, ready to merge

#2002 SC-7476 Prevent hash generation if user has account
  CHANGELOG.md
  src/services/link/index.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
  test/services/user/hooks/userService.hooks.test.js
Labels: ready to merge

#1990 Feature/sc 7028 api spec for course page
  CHANGELOG.md
  src/components/course/docs/openapi.yaml
  src/components/course/index.js
Labels: ready to merge

#1975 Feature/sc-7836 - delete user registration pin
  CHANGELOG.md
  src/components/user/repo/index.js
  src/components/user/repo/registrationPin.repo.integration.test.js
  src/components/user/repo/registrationPin.repo.js
  src/components/user/uc/registrationPin.uc.js
  test/services/helpers/services/index.js
  test/services/helpers/services/registrationPins.js
  test/services/helpers/testObjects.js
Labels: auto update, waiting for review

#1995 Change email addresses for tickets for niedersachcsen
  CHANGELOG.md
  config/globals.js
  package-lock.json
  package.json
  src/services/helpdesk/hooks/index.js
  test/services/helpdesk/index.test.js
Labels: ready to merge
