Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-01, with the labels that each got.

#905 Update chalk to ^3.0.0
  package-lock.json
  package.json
Labels: greenkeeper, ready to merge

#924 SC 1621 storage file name
  src/services/fileStorage/strategies/awsS3.js
  src/services/fileStorage/utils/filePathHelper.js
Labels: ready to merge

#917 implement new notification service for mail handler
  config/default.json
  config/globals.js
  config/test.json
  package-lock.json
  package.json
  src/services/helpers/service.js
  test/services/helpers/service.test.js
Labels: LOKI, ready to merge

#923 Feature/SC-3105 - fix mail attachments
  src/services/helpers/service.js
  test/services/helpers/service.test.js
Labels: ready to merge

#919 SC-3015 | disable team creation by students for whole instance
  config/globals.js
  migrations/1578329693694-disable-team-created-by-students-all-schools.js
  src/services/school/model.js
Labels: LOKI, ready to merge

#910 Feature/sc 1887 news docu
  src/services/news/docs.js
  src/services/news/index.js
Labels: ready to merge

#894 feature/SC-2915 Improve logging for errors
  package-lock.json
  src/app.hooks.js
  src/hooks/index.js
  src/logger/index.js
  src/logger/systemLogger.js
  src/middleware/errorHandler.js
Labels: ready to merge

#918 added filesIds to homework
  src/services/fileStorage/utils/filePermissionHelper.js
  src/services/homework/model.js
  test/services/fileStorage/fixtures.js
  test/services/fileStorage/utils/filePermissionHelper.test.js
Labels: ready to merge

#928 Feature/sc 3096 homework copy for files
  .gitignore
  src/app.hooks.js
  src/services/fileStorage/model-service.js
  src/services/fileStorage/utils/copyFile.js
  src/services/homework/copy-service.js
  src/services/homework/hooks/copy.js
  src/services/homework/index.js
Labels: LOKI

#868 WIP: Add TSP Auth Strategy
  src/services/authentication/index.js
  src/services/authentication/strategies/TSPStrategy.js
  src/services/authentication/strategies/index.js
Labels: WIP

#933 assert that notification service was actually called in tests
  test/services/helpers/service.test.js
Labels: ready to merge

#929 remove unneeded function call after promise
  package-lock.json
  src/services/rocketChat/services/rocketChatUser.js
Labels: LOKI, ready to merge

#940 ce/remove deprecated logs in production
  src/hooks/index.js
Labels: LOKI

#941 Ce/fix resolve scopes route
  src/services/resolve/index.js
Labels: ready to merge

#935 SC-2767-trim-credentials
  src/services/authentication/hooks/index.js
  test/services/authentication/authentication.test.js
Labels: ready to merge

#903 return 200 on password reset route for invalid input to hide error re…
  src/services/passwordRecovery/hooks/index.js
Labels: ready to merge

#936 SC-2941-allow-sub-sup-tags
  src/utils/sanitizeHtml.js
Labels: ready to merge

#937 version upgrade to node 10.17
  .nvmrc
  .travis.yml
  Dockerfile
  package.json
Labels: ready to merge

#898 Update feathers-mongoose (Part 1)
  backup/setup/passwordrecoveries.json
  backup/setup/teams.json
  package-lock.json
  package.json
  src/services/pseudonym/hooks/index.js
  src/services/pseudonym/index.js
  src/utils/database.js
  test/services/account/index.test.js
  test/services/account/moodle/moodle.test.js
  test/services/helpers/registration.test.js
  test/services/helpers/services/accounts.js
  test/services/helpers/services/login.js
  test/services/helpers/services/schools.js
  test/services/helpers/testObjects.js
  test/services/link/index.test.js
  test/services/passwordRecovery/index.test.js
  test/services/pseudonym/index.test.js
  test/services/school/maintenance.test.js
Labels: ready to merge

#938 ce/ add team tests
  backup/setup/teams.json
  src/hooks/index.js
  src/services/teams/index.js
  test/services/helpers/services/accounts.js
  test/services/helpers/services/classes.js
  test/services/helpers/services/consents.js
  test/services/helpers/services/courses.js
  test/services/helpers/services/datasources.js
  test/services/helpers/services/roles.js
  test/services/helpers/services/schoolGroups.js
  test/services/helpers/services/schools.js
  test/services/helpers/services/teams.js
  test/services/helpers/services/testSystem.js
  test/services/helpers/services/users.js
  test/services/helpers/services/years.js
  test/services/helpers/testObjects.js
  test/services/teams/index.test.js
  test/services/user-group/index.test.js
  test/services/user-group/services/classSuccessor.test.js
Labels: LOKI, needs data protection review

#873 SC-1247 | Replaced global permission with scope permissions
  src/services/helpers/scopePermissions/hooks/util/resolveScope.js
  src/services/user-group/hooks/courses.js
  src/services/user-group/hooks/index.js
  src/services/user-group/services/course-copy-service.js
  src/services/user-group/services/courses.js
  test/services/courses/hooks/index.test.js
  test/services/courses/index.test.js
  test/services/courses/services/courseCopy.test.js
  test/services/courses/services/courses.test.js
  test/services/helpers/services/courses.js
  test/services/roster/index.test.js
Labels: LOKI, ready to merge
