Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-02, with the labels that each got.

#945 BooleanValue to trigger PDF preview
  src/services/fileStorage/strategies/awsS3.js
Labels: ready to merge

#932 Add migration.
  backup/setup/migrations.json
  migrations/1579006126081-addSchoolIdsForUsersInTeams.js
  package-lock.json
  src/middleware/errorHandler.js
Labels: LOKI

#934 Sc 2408 bbb
  backup/setup/consentversions.json
  backup/setup/ltitools.json
  backup/setup/migrations.json
  backup/setup/roles.json
  config/default.schema.json
  migrations/1562595327050-AddPositionToLessons.js
  migrations/1562847510503-lessonIsCopyFrom.js
  migrations/1564493063114-persist_files_by_copied_courses.js
  migrations/1578905724955-videoconference permissions added in coursesroles.js
  migrations/1578929548449-add bbb template to lti tools.js
  migrations/1580721491130-addVideoconferencePermissionsToTeamRoles.js
  migrations/done/editorlinks.js
  migrations/done/files.js
  migrations/done/links.js
  migrations/done/privacy.js
  migrations/done/submissions.js
  migrations/done/teacher.js
  migrations/helpers/DatabaseTaskTemplate.js
  package-lock.json
  package.json
  src/helper/compare.js
  src/hooks/index.js
  src/services/calendar/index.js
  src/services/consent/docs/index.js
  src/services/datasources/hooks/index.js
  src/services/index.js
  src/services/ltiTool/hooks/index.js
  src/services/roster/hooks/index.js
  src/services/school/model.js
  src/services/teams/model.js
  src/services/user-group/index.js
  src/services/videoconference/hooks/index.js
  src/services/videoconference/index.js
  src/services/videoconference/logic/constants.js
  src/services/videoconference/logic/index.js
  src/services/videoconference/logic/server.js
  src/services/videoconference/logic/utils.js
  src/services/videoconference/model.js
  test/helper/compare.test.js
  test/services/consent/index.test.js
  test/services/courses/services/coursePermission.test.js
  test/services/videoconference/index.js
  test/services/videoconference/index.test.js
  test/services/videoconference/logic/index.js
Labels: IntegraTHORs

#956 Feature/sc 3147 homework copy tests
  src/services/homework/copy-service.js
  test/services/homework/copy-service.test.js
  test/services/homework/index.test.js
Labels: ready to merge

#954 datasources for webuntis
  backup/setup/webuntismetadatas.json
  src/services/datasources/constants.js
  src/services/datasources/hooks/index.js
  src/services/datasources/hooks/protectFields.js
  src/services/datasources/model.js
  src/services/datasources/schemas/datasourceRuns.create.schema.json
  src/services/datasources/schemas/datasources.create.schema.json
  src/services/datasources/schemas/datasources.patch.schema.json
  src/services/datasources/services/datasourceRuns.js
  src/services/datasources/services/datasources.js
  src/services/index.js
  src/services/sync/index.js
  src/services/sync/strategies/WebUntisSyncer.js
  src/services/sync/strategies/index.js
  src/services/webuntis/hooks/index.js
  src/services/webuntis/hooks/requireDatasourceId.js
  src/services/webuntis/index.js
  src/services/webuntis/model.js
  src/services/webuntis/services/webuntisMetadata.js
  test/services/datasources/datasourceRuns.test.js
  test/services/datasources/datasources.test.js
  test/services/datasources/hooks.test.js
  test/services/helpers/services/datasources.js
  test/services/sync/strategies/webuntis/WebUntisSyncer.test.js
  test/services/webuntis/hooks.test.js
  test/services/webuntis/webuntisMetadataService.test.js
Labels: ready to merge

#961 moved integration-test script from gist into repo
  .travis.yml
Labels: ready to merge

#976 feature/add sso registration test
  test/services/user/registration.test.js
Labels: do not merge

#980 Update simple-oauth2 to ^3.0.0
  package-lock.json
  package.json
Labels: dependencies, ready to merge

#981 allow superheroes to patch schools
  src/services/school/hooks/index.js
  test/services/school/index.test.js
Labels: waiting for review

#972 Tf/fix protect fields without config
  src/services/datasources/hooks/index.js
  src/services/datasources/hooks/protectFields.js
  src/services/datasources/hooks/validateParams.js
  src/services/datasources/services/datasources.js
  test/services/datasources/datasources.test.js
  test/services/datasources/hooks.test.js
Labels: ready to merge

#984 Featire/sc 3232 editor closed beta unlock
  src/services/user/model.js
Labels: ready to merge

#958 SC-3067 verify tsp signature
  package-lock.json
  package.json
  src/services/authentication/strategies/TSPStrategy.js
Labels: dependencies

#990 Sc 3455 datasources superheroes
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1582122141200-datasource-permissions-for-superhero.js
  src/services/datasources/hooks/restrictToDatasourceSchool.js
  test/services/datasources/datasourceRuns.test.js
Labels: ready to merge

#979 CE/add sso registration test
  test/services/user/registration.test.js
Labels: ready to merge

#996 SC-3338 Remove unused dependencies
  package-lock.json
  package.json
Labels: dependencies
