Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-10, with the labels that each got.

#1780 Hotfix SC-6973
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/hooks/registrationPins.js
  src/services/user/index.js
  src/services/user/model/registrationPin.schema.js
Labels: WIP

#1790 Create indexes for slow queries
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1601563383652-addIndexesForSlowQueries.js
  package-lock.json
  package.json
  src/services/fileStorage/model.js
  src/services/homework/model.js
Labels: hotfix: do not merge here, needs data protection review, waiting for review

#1785 ce/add show version to global config
  config/globals.js
  src/services/version/index.js
Labels: auto update, ready to merge

#1792 ARC-111 Avoid privacy PR reviews
  .pullapprove.yml
Labels: WIP, data protection review approved

#1772 add editor flag to seed
  backup/setup/users.json
Labels: auto update, ready to merge

#1770 feature/SC-6510 make use of merlin content
  CHANGELOG.md
  backup/setup/materials.json
  config/default.schema.json
  src/services/content/material-model.js
  src/services/edusharing/hooks/merlin.hooks.js
  src/services/edusharing/index.js
  src/services/edusharing/logic/MerlinTokenGenerator.js
  src/services/edusharing/logic/connector.js
  src/services/lesson/hooks/index.js
  src/services/lesson/services/AddMaterialService.js
Labels: waiting for review

#1796 Fix module export of new instance of merlin class
  CHANGELOG.md
  src/services/edusharing/logic/MerlinTokenGenerator.js
Labels: waiting for review

#1799 SC-6960 fix registration eating users
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/registration.js
Labels: hotfix: do not merge here, waiting for review

#1805 fixes readme badges
  CHANGELOG.md
  README.md
Labels: auto update, ready to merge

#1800 SC-6766 catch promise style
  .eslintrc.js
  CHANGELOG.md
  package-lock.json
  package.json
Labels: WIP

#1808 Update Commons to 1.2.8
  package-lock.json
  package.json
  src/index.js
Labels: WIP

#1804 Hotfix/3/sc 7115/reduce role db requests
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/role/hooks/index.js
  src/services/role/model.js
  src/utils/cache.js
  src/utils/index.js
Labels: WIP, hotfix: do not merge here

#1806 Repair merge conflict causing tests to fail
  src/services/user/registration.js
Labels: auto update, ready to merge

#1809 SC-6766 SC-7080 log unhandledRejection and unhandledException
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  config/globals.js
  package-lock.json
  package.json
  src/app.js
  src/index.js
  src/middleware/sentry.js
  src/utils/processEvents.js
Labels: waiting for review

#1810 sc 6769 api validation for adminusers
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/app.js
  src/services/user/docs/adminusers.openapi.yaml
  src/services/user/docs/openapi.yaml
  src/services/user/index.js
  src/utils/apiValidation.js
  test/services/datasources/datasourceRuns.test.js
  test/services/lessons/addMaterialService.test.js
  test/services/user/services/AdminUsers.integration.test.js
Labels: ready to merge

#1775 SC-6676 allows only following roles for registration: teacher/student…
  CHANGELOG.md
  src/services/user/registration.js
  test/services/user/registration.test.js
Labels: waiting for review

#1827 SC-7201 Fix homeworks test
  src/services/homework/hooks/index.js
  test/services/homework/index.test.js
Labels: auto update, ready to merge

#1811 Add unit test for Merlin service
  CHANGELOG.md
  src/services/edusharing/logic/MerlinTokenGenerator.js
  test/services/edusharing/services/merlinGenerator.test.js
Labels: waiting for review

#1831 fix api docu route registrations
  CHANGELOG.md
  package-lock.json
  src/services/account/index.js
  src/services/activation/index.js
  src/services/alert/index.js
  src/services/analytics/index.js
  src/services/authentication/index.js
  src/services/base64Files/index.js
  src/services/calendar/index.js
  src/services/consent/index.js
  src/services/content/index.js
  src/services/datasources/index.js
  src/services/edusharing/index.js
  src/services/etherpad/index.js
  src/services/federalState/index.js
  src/services/fileStorage/index.js
  src/services/help/index.js
  src/services/helpdesk/index.js
  src/services/homework/index.js
  src/services/ldap/index.js
  src/services/lesson/index.js
  src/services/link/index.js
  src/services/ltiTool/index.js
  src/services/me/index.js
  src/services/news/index.js
  src/services/nexboard/index.js
  src/services/notification/index.js
  src/services/oauth2/index.js
  src/services/passwordRecovery/index.js
  src/services/pseudonym/index.js
  src/services/releases/index.js
  src/services/resolve/index.js
  src/services/rocketChat/index.js
  src/services/role/index.js
  src/services/roster/index.js
  src/services/school/index.js
  src/services/statistic/index.js
  src/services/storageProvider/index.js
  src/services/sync/index.js
  src/services/system/index.js
  src/services/teams/index.js
  src/services/user-group/index.js
  src/services/user/index.js
  src/services/videoconference/index.js
  src/services/webuntis/index.js
  src/services/wopi/index.js
Labels: ready to merge

#1836 OPS-1297 add release branches to scope of changelog action
  .github/workflows/require_changelog.yml
Labels: WIP

#1826 Hotfix/3/sc 7165/improve sanitization
  CHANGELOG.md
  package-lock.json
  package.json
  src/utils/sanitizeHtml.js
  test/utils/sanitizeHtml.test.js
Labels: waiting for review

#1834 SC-6986 - fix changing password error
  CHANGELOG.md
  src/services/account/hooks/index.js
  src/services/account/services/accountApiService.js
  test/services/account/services/accounts.test.js
Labels: auto update, ready to merge

#1828 feature/SC-7351/Add some missing hpi strings.
  .github/PULL_REQUEST_TEMPLATE.md
  .pullapprove.yml
  .travis.yml
  README.md
  compose-server-test.dummy
  config/default.schema.json
  config/test.json
  deploy.sh
  migrate-etherpads.js
  migrations/done/privacy.js
  package-lock.json
  package.json
  src/services/account/docs/openapi.yaml
  src/services/account/services/SupportJWTService.js
  src/services/activation/docs/openapi.yaml
  src/services/alert/docs/openapi.yaml
  src/services/alert/index.js
  src/services/analytics/docs/openapi.yaml
  src/services/authentication/docs/openapi.yaml
  src/services/base64Files/docs/openapi.yaml
  src/services/calendar/docs/openapi.yaml
  src/services/consent/docs/openapi.yaml
  src/services/content/docs/openapi.yaml
  src/services/datasources/docs/openapi.yaml
  src/services/edusharing/docs/openapi.yaml
  src/services/etherpad/docs/openapi.yaml
  src/services/federalState/docs/openapi.yaml
  src/services/fileStorage/docs/openapi.yaml
  src/services/help/docs/openapi.yaml
  src/services/helpdesk/docs/openapi.yaml
  src/services/helpers/docs/openapi.yaml
  src/services/homework/docs/openapi.yaml
  src/services/ldap/docs/openapi.yaml
  src/services/lesson/docs/openapi.yaml
  src/services/link/docs/openapi.yaml
  src/services/ltiTool/docs/openapi.yaml
  src/services/me/docs/openapi.yaml
  src/services/news/docs/openapi.yaml
  src/services/nexboard/docs/openapi.yaml
  src/services/notification/docs/openapi.yaml
  src/services/oauth2/docs/openapi.yaml
  src/services/passwordRecovery/docs/openapi.yaml
  src/services/pseudonym/docs/openapi.yaml
  src/services/releases/docs/openapi.yaml
  src/services/resolve/docs/openapi.yaml
  src/services/rocketChat/docs/openapi.yaml
  src/services/role/docs/openapi.yaml
  src/services/roster/docs/openapi.yaml
  src/services/school/docs/openapi.yaml
  src/services/statistic/docs/openapi.yaml
  src/services/storageProvider/docs/openapi.yaml
  src/services/sync/docs/openapi.yaml
  src/services/system/docs/openapi.yaml
  src/services/teams/docs/openapi.yaml
  src/services/user-group/docs/openapi.yaml
  src/services/user/docs/adminusers.openapi.yaml
  src/services/user/docs/openapi.yaml
  src/services/videoconference/docs/openapi.yaml
  src/services/webuntis/docs/openapi.yaml
  src/services/wopi/docs/openapi.yaml
Labels: auto update, waiting for review

#1837 Hotfix/5/SC-7085 parent pin
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/SkipRegistration.js
  test/services/user/services/SkipRegistration.test.js
Labels: waiting for review

#1850 update develop with latest from master
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/SkipRegistration.js
  test/services/user/services/SkipRegistration.test.js
Labels: WIP

#1843 add util to cleanup IncomingMessage for errors
  CHANGELOG.md
  src/errors/index.js
  src/errors/utils.js
  src/helper/compare.js
  src/middleware/errorHandler.js
  src/utils/incomingMessageToJson.js
  src/utils/index.js
  test/errors/utils.test.js
  test/utils/incomingMessageToJson.test.js
Labels: auto update, ready to merge, waiting for review

#1814 Feature/SC-6060 - Analyse and fix top errors in sentry
  CHANGELOG.md
  src/services/account/services/jwtTimerService.js
Labels: waiting for review

#1849 ce/Fix mocha test in oauth
  CHANGELOG.md
  test/services/oauth2/mock.js
  test/services/oauth2/oauth2MockServer.js
Labels: auto update, ready to merge, waiting for review

#1779 SC-6586 - Remove parents from users collection to improve maintainabi…
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/roles.json
  backup/setup/users.json
  migrations/1601022564938-copy-parents-data-into-children-entities-and-delete-parent-users.js
  src/services/user/firstLogin.js
  src/services/user/hooks/userService.js
  src/services/user/model/user.schema.js
  src/services/user/registration.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
  test/services/user/registration.test.js
  test/services/user/services/userService.test.js
Labels: waiting for review

#1856 Hotfix/1/SC-7420
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/account/hooks/index.js
  src/services/account/services/accountApiService.js
  test/services/account/services/accounts.test.js
Labels: waiting for review

#1852 Hotfix/2/sc 6986 fix password edit permissions
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/account/hooks/index.js
Labels: waiting for review

#1833 Add officialSchoolNumber to school-model
  CHANGELOG.md
  src/services/fileStorage/strategies/awsS3.js
  src/services/school/hooks/index.js
  src/services/school/model.js
  test/services/school/index.test.js
Labels: ready to merge

#1839 Introduce FEATURE_PROMETHEUS_ENABLED
  CHANGELOG.md
  config/default.schema.json
  src/app.js
  src/utils/prometheus.js
Labels: WIP

#1855 update commons to 1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
  test/app.hooks.redis.test.js
  test/services/account/services/jwtTimerService.test.js
  test/services/authentication/apiKeyStrategy.test.js
  test/services/authentication/hooks/index.test.js
  test/services/etherpad/index.test.js
  test/services/etherpad/permissions.test.js
  test/services/etherpad/permissionsStudents.test.js
  test/services/fileStorage/aws/awsMultipleS3.test.js
  test/services/messengerSync/consumer.test.js
  test/services/messengerSync/services/messengerTokenService.test.js
  test/services/messengerSync/services/schoolSyncService.test.js
  test/services/nexboard/index.test.js
  test/services/storageProvider/index.test.js
  test/services/user/services/AdminUsers.integration.test.js
  test/utils/redis/redis.test.js
Labels: auto update

#1860 Feature/sc 7357/settings endpoint
  CHANGELOG.md
  src/services/config/configService.js
  src/services/config/docs/openapi.yaml
  src/services/config/hooks/index.js
  src/services/config/hooks/superheroAccess.js
  src/services/config/index.js
  src/services/index.js
  src/services/rocketChat/services/rocketChatLogout.js
  src/services/rocketChat/services/rocketChatUser.js
  test/services/config/hooks/superheroAccess.test.js
Labels: ready to merge

#1859 SC-4385 - IServ individual exclusion
  CHANGELOG.md
  src/services/ldap/strategies/iserv-idm.js
Labels: auto update, ready to merge

#1844 update doc paths
  CHANGELOG.md
  src/services/account/index.js
  src/services/activation/index.js
  src/services/alert/index.js
  src/services/analytics/index.js
  src/services/authentication/index.js
  src/services/base64Files/index.js
  src/services/calendar/index.js
  src/services/consent/index.js
  src/services/content/index.js
  src/services/datasources/index.js
  src/services/edusharing/index.js
  src/services/etherpad/index.js
  src/services/federalState/index.js
  src/services/fileStorage/index.js
  src/services/help/index.js
  src/services/helpdesk/index.js
  src/services/homework/index.js
  src/services/ldap/index.js
  src/services/lesson/index.js
  src/services/link/index.js
  src/services/ltiTool/index.js
  src/services/me/index.js
  src/services/news/index.js
  src/services/nexboard/index.js
  src/services/notification/index.js
  src/services/oauth2/index.js
  src/services/passwordRecovery/index.js
  src/services/pseudonym/index.js
  src/services/releases/index.js
  src/services/resolve/index.js
  src/services/rocketChat/index.js
  src/services/role/index.js
  src/services/roster/index.js
  src/services/school/index.js
  src/services/statistic/index.js
  src/services/storageProvider/index.js
  src/services/sync/index.js
  src/services/system/index.js
  src/services/teams/index.js
  src/services/user-group/index.js
  src/services/videoconference/index.js
  src/services/webuntis/index.js
  src/services/wopi/index.js
Labels: auto update, ready to merge

#1864 Feature/SC-6293 lernstore access
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/roles.json
  config/default.schema.json
  migrations/1603301779189-disableLernStoreForStudentsinNI_SH.js
  src/services/edusharing/hooks/index.js
  src/services/school/index.js
  test/services/edusharing/hooks/index.js
Labels: waiting for review

#1865 Hotfix/1/SC-7452
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/hooks/registrationPins.js
Labels: waiting for review

#1858 Hotfix/2/SC-6986 - fix password edit permissions (merge to develop)
  CHANGELOG.md
  src/services/account/hooks/index.js
Labels: waiting for review

#1870 Hotfix/1/SC-7452 (into develop)
  CHANGELOG.md
  src/services/user/hooks/registrationPins.js
Labels: waiting for review

#1872 replace querystring by qs
  CHANGELOG.md
  package-lock.json
  package.json
  src/middleware/requestLogger.js
  src/services/calendar/index.js
  src/services/link/index.js
  src/services/notification/index.js
Labels: ready to merge

#1878 Hotfix/3/revert unhandled rejection handler
  CHANGELOG.md
  package-lock.json
  package.json
  src/index.js
  src/logger/index.js
Labels: waiting for review

#1873 SC-6080 - move REQUEST_TIMEOUT from globals to Configuration
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  config/development.json
  config/globals.js
  src/helper/externalApiRequest.js
  src/services/calendar/index.js
  src/services/content/index.js
  src/services/edusharing/logic/connector.js
  src/services/helpers/service.js
  src/services/notification/index.js
  src/services/rocketChat/helpers.js
Labels: auto update, ready to merge

#1866 SC-7454 - restore birthdate fix
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
Labels: auto update, ready to merge

#1853 SC-7091 Migrate schools from RocketChat to Matrix Messenger
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/schools.json
  migrations/1603114571772-rocketchat-to-matrix-messenger.js
Labels: auto update, ready to merge

#1874 SC-6586 Repaired migration script
  CHANGELOG.md
  migrations/1601022564938-copy-parents-data-into-children-entities-and-delete-parent-users.js
  src/services/user/model/user.schema.js
Labels: waiting for review

#1871 SC-7395 serialize user fetching
  CHANGELOG.md
  src/services/ldap/strategies/general.js
Labels: auto update

#1877 Feature/sc 7404 legacy basepath
  CHANGELOG.md
  package-lock.json
  package.json
  src/middleware/index.js
  src/middleware/legacyForward.js
  src/services/me/index.js
  test/middleware/legacyForward.integration.test.js
  test/services/me/services/meService.test.js
Labels: auto update, ready to merge

#1893 Hotfix SC-7491 add index on users.email
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1603872433544-addIndexForUserEmail.js
  package-lock.json
  package.json
  src/services/user/model/user.schema.js
Labels: hotfix: do not merge here, needs data protection review

#1887 Feature/sc 7411 document simple routes
  CHANGELOG.md
  config/default.schema.json
  config/globals.js
  src/app.js
  src/hooks/index.js
  src/hooks/transformToDataTransferObject.js
  src/middleware/errorHandler.js
  src/middleware/legacyForward.js
  src/services/docs/index.js
  src/services/docs/openapi.yaml
  src/services/index.js
  src/services/me/docs/openapi.yaml
  src/services/me/hooks/index.js
  src/services/versionService/index.js
  src/services/versionService/openapi.yaml
  src/utils/apiValidation.js
  test/hooks/transformToDataTransferObject.unit.test.js
  test/services/helpers/services/login.js
  test/services/helpers/testObjects.js
  test/services/me/services/me.integration.test.js
  test/services/versionService/version.integration.test.js
Labels: auto update, ready to merge

#1896 SC-7517/Feature/fix oauth2 tests
  CHANGELOG.md
  test/services/oauth2/hydra.js
  test/services/oauth2/mock.js
Labels: auto update, ready to merge

#1763 Feature/SC-6738-Extend search input field in new admin tables to search for full name
  .github/workflows/migrations.yml
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/users.json
  migrations/1602693850245-search_index.js
  migrations/1602762361840-syncUserIndex.js
  src/services/user/model/user.schema.js
  src/services/user/services/AdminUsers.js
  src/services/user/utils/aggregations.js
  src/utils/database.js
  src/utils/search.js
  test/services/user/services/AdminUsers.test.js
  test/utils/search.test.js
Labels: auto update, ready to merge

#1867 Allow API Auth
  src/services/statisticMail/hooks/index.js
Labels: WIP, auto update

#1898 SC-7530 rename SHOW_VERSION to FEATURE_VERSION_ENABLED
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  config/production.json
  package-lock.json
  src/services/versionService/index.js
  test/services/versionService/version.integration.test.js
Labels: ready to merge

#1832 SC-5476 Add school setting to allow students to create their own chat rooms
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/roles.json
  config/default.json
  config/default.schema.json
  migrations/1602761974065-add-messenger-one-to-one-permissions.js
  src/services/index.js
  src/services/messenger/index.js
  src/services/messenger/services/messengerConfigService.js
  src/services/messenger/services/messengerPermissionService.js
  src/services/messengerSync/services/messengerTokenService.js
  src/services/messengerSync/utils.js
  src/services/school/hooks/index.js
  src/services/school/model.js
  test/services/messenger/services/messengerConfigService.test.js
  test/services/messenger/services/messengerPermissionService.test.js
  test/services/messengerSync/services/messengerTokenService.test.js
Labels: auto update, waiting for review

#1903 rename integration test repo
  .travis.yml
  CHANGELOG.md
Labels: waiting for review
