Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-05, with the labels that each got.

#1236 Hotfix/22.9.17
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/fileStorage/proxy-service.js
Labels: hotfix: do not merge here

#1222 SC-3577: add school feature flag to add messenger room for whole school
  .idea/schulcloud.iml
  src/services/ltiTool/hooks/index.js
  src/services/messengerSync/producer.js
  src/services/messengerSync/services/messengerTokenService.js
  src/services/messengerSync/services/schoolSyncService.js
  src/services/messengerSync/utils.js
  src/services/rocketChat/hooks/index.js
  src/services/rocketChat/services/rocketChatChannel.js
  src/services/rocketChat/services/rocketChatUser.js
  src/services/school/hooks/index.js
  src/services/school/model.js
  src/services/teams/hooks/helpers.js
  src/services/teams/hooks/index.js
  src/services/teams/model.js
  src/services/teams/services/admin.js
  src/services/user-group/model.js
  test/services/helpers/services/courses.js
  test/services/messengerSync/services/messengerTokenService.test.js
  test/services/messengerSync/utils.test.js
  test/services/school/index.test.js
Labels: ready to merge

#1245 Add roster service to ignored redis routes
  src/app.hooks.js
Labels: ready to merge

#1250 Fix PR template typos
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready to merge

#1241 SC-3686 - registration link service
  CHANGELOG.md
  src/services/link/index.js
  src/services/user/index.js
  src/services/user/services/MailRegistrationLink.js
  src/services/user/services/index.js
Labels: waiting for review

#1205 Refactor video conference services
  src/services/videoconference/index.js
  src/services/videoconference/logic/constants.js
Labels: ready to merge

#1251 gitflow-feature-stash: enhance-bbb-errors
  src/services/videoconference/logic/index.js
Labels: ready to merge

#1261 Update CHANGELOG.md
  CHANGELOG.md
Labels: ready to merge

#1262 Ce/update mergify
  .mergify.yml
  CHANGELOG.md
Labels: ready to merge

#1264 SC-4104 Replace unsecure Math.radnom(x) with crypto package from nodejs
  src/services/account/index.js
  src/services/helpers/hash.js
  src/services/rocketChat/randomPass.js
  src/services/user/hooks/registrationPins.js
  src/utils/randomNumberGenerator.js
  test/utils/randomNumberGenerator.test.js
Labels: waiting for review

#1268 Feature/SC-4260-sentry-server
  config/default.schema.json
  src/app.js
  src/middleware/sentry.js
Labels: ready to merge

#1183 Feature/sc 4019 coursegroup
  src/hooks/index.js
  src/services/user-group/hooks/courseGroups.js
  src/services/user-group/index.js
  src/services/user-group/services/courseGroupModelService.js
  src/services/user-group/services/courseGroups.js
  test/services/helpers/services/courseGroups.js
  test/services/helpers/services/index.js
  test/services/helpers/testObjects.js
  test/services/user-group/services/courseGroups.test.js
Labels: ready to merge

#1228 [#SC-4064] Aufgaben feedback mit files erweitern (1/4)
  CHANGELOG.md
  src/services/fileStorage/utils/filePermissionHelper.js
  src/services/homework/hooks/index.js
  src/services/homework/model.js
  test/services/helpers/services/files.js
  test/services/helpers/services/index.js
  test/services/helpers/testObjects.js
  test/services/homework/submissionService.test.js
Labels: ready to merge

#1289 [Hotfix] SC-4389 - fixed pagination for students/teacher table
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: waiting for review

#1242 [#SC-4064-3] Change download file names (3/4)
  src/services/fileStorage/proxy-service.js
  test/services/fileStorage/index.test.js
Labels: ready to merge

#1248 feature/SC-3970/use 'after' hooks in order to santizes output from database
  src/app.hooks.js
  src/services/help/index.js
  src/services/homework/hooks/copy.js
  src/utils/sanitizeHtml.js
  test/app.hooks.test.js
  test/services/help/index.test.js
Labels: ready to merge

#1287 Feature/sc 4195
  src/services/account/hooks/index.js
  src/services/account/index.js
  src/services/account/services/accountApiService.js
  src/services/account/services/accountModelService.js
  src/services/authentication/index.js
  test/services/account/services/accountModelService.test.js
  test/services/account/services/accounts.test.js
  test/services/user-group/services/courses.test.js
Labels: ready to merge, request_changes

#1294 Feature/sc 4045 registration without consent
  config/default.schema.json
  src/services/consent/docs/index.js
  src/services/consent/model.js
  src/services/user/firstLogin.js
  src/services/user/registration.js
Labels: WIP

#1290 SC-4335 Fix bug with school result pagination
  src/services/school/hooks/index.js
  test/services/school/index.test.js
Labels: ready to merge

#1298 SC-4075 change default value for STUDENT_TEAM_CREATION to opt-out
  config/default.json
  config/default.schema.json
Labels: WIP

#1292 SC-4291 Remove overwriting from-address in the helpdesk e-mail
  src/hooks/index.js
  src/services/helpdesk/hooks/index.js
  src/services/helpers/service.js
  test/services/helpers/service.test.js
Labels: ready to merge

#1305 Ce/fix response
  package-lock.json
  package.json
  src/services/passwordRecovery/hooks/index.js
  src/services/passwordRecovery/index.js
Labels: ready to merge

#1299 SC-4352 add more school years 2021/22 - 2025/26
  backup/setup/migrations.json
  backup/setup/years.json
  migrations/1589468201229-add_more_school_years.js
Labels: ready to merge

#1362 Hotfix/1/sc 4749 improve sanitize html
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.hooks.js
  src/utils/sanitizeHtml.js
  test/app.hooks.test.js
Labels: WIP
