Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-07, with the labels that each got.

#1476 Hotfix/3/sc 4965
  CHANGELOG.md
  migrations/1593184378869-remove_user-consent-ids.js
  src/services/consent/hooks/consents.js
  src/services/user/hooks/userService.js
  src/services/user/model/consent.schema.js
  src/services/user/registration.js
Labels: WIP

#1430 SC-4073 brute force passwordRecovery
  backup/setup/migrations.json
  backup/setup/passwordRecovery.json
  backup/setup/passwordrecoveries.json
  config/globals.js
  migrations/1592545139451-passwordRecoveryCopyIdToToken.js
  package-lock.json
  package.json
  src/middleware/errorHandler.js
  src/middleware/errors.js
  src/services/passwordRecovery/hooks/index.js
  src/services/passwordRecovery/index.js
  src/services/passwordRecovery/model.js
  src/services/passwordRecovery/services/ChangePasswordService.js
  src/services/passwordRecovery/services/GenerateRecoveryPasswordTokenService.js
  src/utils/randomNumberGenerator.js
  test/routes/whitelist.js
  test/services/passwordRecovery/index.test.js
  test/services/passwordRecovery/services/ChangePasswordService.test.js
Labels: ready to merge

#1442 OPS-737 Fixed the filter logic on create trigger
  .github/workflows/update_version.yml
Labels: waiting for review

#965 SC-2230 Edusharing (I) wrapper
  config/default.json
  config/default.schema.json
  src/services/edusharing/hooks/index.js
  src/services/edusharing/index.js
  src/services/edusharing/logic/connector.js
  src/services/index.js
  src/services/lesson/hooks/addMaterial.js
  src/services/lesson/hooks/index.js
  src/services/lesson/index.js
  src/services/lesson/services/AddMaterialService.js
  src/services/lesson/services/index.js
Labels: WIP

#1490 fix error when parentConsents undefined
  src/services/user/utils/consent.js
Labels: waiting for review

#1471 Hotfix/4/sc 5071 secure consent versions api
  package-lock.json
  package.json
  src/hooks/index.js
  src/services/consent/services/consentVersionService.js
  src/services/user/index.js
  src/services/user/services/index.js
  src/services/user/services/registrationConsent.js
  test/services/consent/index.test.js
Labels: ready to merge

#1498 Hotfix/3/sc-2711 add federal state for international schools
  CHANGELOG.md
  backup/setup/federalstates.json
  backup/setup/migrations.json
  migrations/1594199712718-add-federal-state-internation-school.js
  package-lock.json
  package.json
  src/services/federalState/index.js
Labels: WIP

#1501 SC-5250 - adds a trim to the column-names of the csv
  CHANGELOG.md
  src/services/sync/strategies/CSVSyncer.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Labels: ready to merge

#1478 Feature/sc 4041-student-list-visibility-test
  src/services/role/hooks/userRoles.js
  test/services/helpers/services/schools.js
  test/services/role/services/userPermissions.test.js
  test/services/role/services/userRoles.test.js
Labels: waiting for review

#1448 Hotfix/3/sc 4197 etherpad migration script from masters
  config/default.schema.json
  config/globals.js
  migrate_etherpad.js
  migrations/1591695787216-move_etherpad.js
  package-lock.json
  package.json
Labels: waiting for review

#1528 Bugfix/sc 5071 make base64 file route public
  src/services/base64Files/hooks/index.js
Labels: ready to merge

#1356 SC-4520 - Activation service
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  src/services/activation/hooks/utils.js
  src/services/activation/index.js
  src/services/activation/model.js
  src/services/activation/services/ActivationModelService.js
  src/services/activation/services/ActivationService.js
  src/services/activation/services/eMailAddress/index.js
  src/services/activation/services/exampleStrategyService/index.template.js
  src/services/activation/services/index.js
  src/services/activation/services/interface/mailFormat.js
  src/services/activation/utils/customErrorMessages.js
  src/services/activation/utils/customStrategyUtils.js
  src/services/activation/utils/generalUtils.js
  src/services/helpers/utils/index.js
  src/services/helpers/utils/userHelpers.js
  src/services/index.js
  test/services/activation/hooks/utils.test.js
  test/services/activation/services/activationService.test.js
  test/services/activation/services/eMailAddress/index.test.js
  test/services/activation/utils/customUtils.test.js
  test/services/activation/utils/index.test.js
  test/services/helpers/services/activation.js
  test/services/helpers/services/index.js
  test/services/helpers/testObjects.js
Labels: ready to merge

#1539 Move SILENT_ERROR_ENABLED env to schema file
  config/default.schema.json
  config/globals.js
  src/middleware/errorHandler.js
Labels: ready to merge

#1535 SC-5542 - Order of table headers
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: ready to merge

#1464 Feature/SC-4289 class-filtering-and-sorting
  CHANGELOG.md
  src/services/consent/utils/aggregations.js
  src/services/user/services/AdminUsers.js
Labels: ready to merge

#1540 SC-5686 - fix permission for viewing / editing teams
  CHANGELOG.md
  src/services/teams/hooks/index.js
Labels: ready to merge

#1552 include team 6 and 7 hotfix instances
  deploy.sh
Labels: ready to merge

#1548 Hotfix/2/23.6.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/LDAPSchoolSyncer.js
Labels: WIP, hotfix: do not merge here

#1554 try mergify auto update pull requests
  .mergify.yml
Labels: auto update

#1553 Feature/sc-5754 - is external school attribute
  CHANGELOG.md
  src/services/school/model.js
  test/services/school/index.test.js
Labels: needs data protection review, waiting for review

#1491 Encode Depseudo Iframe
  src/services/roster/index.js
  test/services/roster/index.test.js
Labels: WIP

#1505 adjust schools service unauthorized calls tests
  test/services/school/index.test.js
Labels: ready to merge

#1565 Hotfix/4/sc 5416 start a new school year
  backup/setup/migrations.json
  backup/setup/schools.json
  migrations/1595833881178-start_new_school_year.js
  package-lock.json
  package.json
Labels: WIP, do not merge

#1573 SC-5888 fix: Choose current schoolyear based on the school
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/school/logic/year.js
Labels: WIP

#1575 Hotfix SC-4970
  package.json
  src/services/authentication/strategies/TSPStrategy.js
  src/services/sync/strategies/TSP/TSP.js
  src/services/sync/strategies/TSP/TSPSchoolSyncer.js
Labels: ready to merge

#1455 SC-4997 force user to change password if the password was changed by …
  package-lock.json
  src/services/account/hooks/index.js
  src/services/user/firstLogin.js
  src/services/user/index.js
  src/services/user/model/user.schema.js
  src/services/user/services/ForcePasswordChange.js
  src/services/user/services/index.js
  src/utils/passwordHelpers.js
  test/helper/passwordHelpers.test.js
  test/services/user/services/ForcePasswordChange.test.js
Labels: ready to merge
