Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-09, with the labels that each got.

#1697 Hotfix/4/sc 6511 ldap edit button missing
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/school/hooks/index.js
Labels: waiting for review

#1657 SC-5808 - add isExternal check to adminUsers create method
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: auto update, ready to merge

#1681 SC-6172 disallow disposable/existing mails
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: auto update, ready to merge

#1691 SC-6484 remove default current date birthday
  src/services/user/services/AdminUsers.js
Labels: ready to merge

#1700 Feature/sc 6368 security students adminusers
  src/services/user/hooks/adminUsers.hooks.js
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: auto update, ready to merge

#1689 Feature/SC-5612 - Search bar for admintables
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
Labels: auto update, ready to merge

#1693 SC-5941 Fix filtering of creation date in admin tables
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: ready to merge

#1679 SC-6389 extend school and user model with default language, implement…
  CHANGELOG.md
  src/services/me/index.js
  src/services/school/hooks/index.js
  src/services/school/hooks/lookupSchool.js
  src/services/school/model.js
  src/services/user/model/user.schema.js
  src/services/user/registration.js
Labels: auto update, needs data protection review, waiting for review

#1705 Hotfix/2/sc 6554 csv parent patch
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/CSVSyncer.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Labels: hotfix: do not merge here, waiting for review

#1710 SC-6594 - add sendregistrationlink hook
  src/services/user/services/AdminUsers.js
Labels: auto update, auto_merged

#1708 SC-6369 - security adminUser teachers route
  test/services/user/services/AdminUsers.test.js
Labels: WIP, auto update, auto_merged

#1723 SC-6697 - edit email (Hotfix 24.4.4)
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: WIP

#1724 SC-6640 - Registration: Stundent vs. Parent e-mail verification
  CHANGELOG.md
  src/services/user/registration.js
  test/services/user/registration.test.js
Labels: auto update, waiting for review

#1725 ops-1109 removed deployment on testenvironment.
  deploy.sh
Labels: WIP, auto update, auto_merged

#1730 Cleanup prettier/eslint ignore files
  .eslintignore
  .prettierignore
  CHANGELOG.md
  src/services/version/index.js
  test/services/user/services/AdminUsers.test.js
Labels: WIP

#1728 Hotfix SC-6637
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/AdminUsers.js
Labels: ready to merge

#1732 lint and fix changelog entries
  CHANGELOG.md
Labels: WIP

#1734 Hotfix SC-6733
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/CSVSyncer.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Labels: waiting for review

#1722 Feature/extend jwt
  CHANGELOG.md
  src/services/authentication/index.js
Labels: WIP, auto update, auto_merged

#1743 SC-6784 - fix invalid date adminUsers
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
Labels: auto update, ready to merge

#1744 SC-6743 - service cleanup
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
Labels: auto update, auto_merged

#1756 Hotfix/2/secure admin routes
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/AdminUsers.js
  src/services/user/utils/aggregations.js
  test/services/user/services/AdminUsers.test.js
Labels: WIP, do not merge

#1757 Merge branch 'hotfix/2/secure_admin_routes'
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
  src/services/user/utils/aggregations.js
  test/services/user/services/AdminUsers.test.js
Labels: auto update, ready to merge

#1760 Hotfix: SC-6809: rabbitmq connection fix
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/messengerSync/consumer.js
  src/services/messengerSync/producer.js
  src/utils/rabbitmq.js
  test/services/messengerSync/rabbitmqMock.js
  test/services/messengerSync/services/schoolSyncService.test.js
Labels: waiting for review

#1677 SC-6150 Added initial OAS API spec for news service
  src/services/news/docs/openapi.yaml
  src/services/news/index.js
Labels: ready to merge

#1714 SC-6506 Remove dependency to feathers-swagger in routes.test.js
  CHANGELOG.md
  test/routes/whitelist.js
  test/services/helpers/getAllRoutes.js
Labels: ready to merge

#1749 SC-6676 allows only following roles for registration: teacher/student…
  src/services/user/registration.js
  test/services/user/registration.test.js
Labels: ready to merge

#1716 Feature/sc 5230 unblock users and account
  CHANGELOG.md
  package-lock.json
  src/services/account/hooks/index.js
  src/services/account/services/accountApiService.js
  src/services/user/services/userService.js
  test/services/account/services/accounts.test.js
  test/services/role/services/userPermissions.test.js
  test/services/role/services/userRoles.test.js
  test/services/user/services/ForcePasswordChange.test.js
  test/services/user/services/userService.test.js
Labels: ready to merge

#1739 SC-6774 Remove no-await-in-loop from eslint exceptions in server
  .eslintrc.js
  CHANGELOG.md
Labels: WIP

#1761 SC-6899: Add rabbitmq channel class to maintain channel connection
  CHANGELOG.md
  src/services/messengerSync/consumer.js
  src/services/messengerSync/producer.js
  src/utils/rabbitmq.js
  test/services/messengerSync/consumer.test.js
  test/services/messengerSync/rabbitmqMock.js
  test/services/messengerSync/services/schoolSyncService.test.js
Labels: auto update, waiting for review

#1766 Hotfix SC-6696 topics in courses
  CHANGELOG.md
  package-lock.json
  package.json
  src/hooks/index.js
  test/services/courses/index.test.js
  test/services/lessons/index.test.js
Labels: hotfix: do not merge here, waiting for review

#1758 SC-6830 - fix remove method when users > 20
  CHANGELOG.md
  src/services/user/hooks/adminUsers.hooks.js
  src/services/user/services/AdminUsers.js
Labels: auto update, auto_merged, ready to merge

#1769 increase possible amount of schools per page
  src/services/school/index.js
Labels: WIP

#1773 Hotfix/25.0.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/hooks/registrationPins.js
Labels: WIP, hotfix: do not merge here

#1774 SC-6942: fix TSC login
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/authentication/hooks/index.js
  src/services/authentication/index.js
  src/services/authentication/strategies/TSPStrategy.js
Labels: hotfix: do not merge here, waiting for review

#1733 Bugfix/SC-6674 - Ensure unique email addresses
  CHANGELOG.md
  src/hooks/index.js
  src/services/user/hooks/userService.js
  src/services/user/services/userService.js
  test/services/user/hooks/userService.hooks.test.js
  test/services/user/services/userService.test.js
Labels: auto update, waiting for review

#1781 Hotfix/3/add lead time detection
  CHANGELOG.md
  config/globals.js
  package-lock.json
  package.json
  src/app.hooks.js
  src/app.js
Labels: waiting for review
