Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-08, with the labels that each got.

#1581 SC-5917 Fix bug in LDAP activation
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap/index.js
Labels: waiting for review

#1582 add new conditional for error-name
  config/default.schema.json
  src/middleware/errorHandler.js
Labels: waiting for review

#1589 Hotfix/4/sc 5835 start new school year cluster4
  backup/setup/migrations.json
  backup/setup/schools.json
  migrations/1596459511983-start_new_school_year_cluster_4.js
  package-lock.json
  package.json
Labels: do not merge, waiting for review

#1500 add user login, user email and user role
  src/services/helpdesk/hooks/index.js
Labels: ready to merge

#1529 Feature/sc 5487 generate harder link for external
  config/default.json
  config/globals.js
  src/services/link/index.js
Labels: ready to merge

#1594 removed unused stuff (sign up Mail)
  package-lock.json
  package.json
  src/services/account/helper.js
  src/services/account/templates/signup/html.ejs
  src/services/account/templates/signup/style.scss
  src/services/account/templates/signup/text.ejs
Labels: auto update, ready to merge

#1597 add deployment output commands
  deploy.sh
Labels: auto update, ready to merge

#1610 Fix deployment/release 24.1.0
  .dockerignore
  .travis.yml
  deploy.sh
  travis_rsa.enc
Labels: WIP

#1611 Fix deployment/release 24.0.0
  .dockerignore
  .travis.yml
  deploy.sh
  travis_rsa.enc
Labels: WIP

#1583 prepare enable course and lessons routes
  src/hooks/index.js
  src/hooks/restrictPopulate.js
  src/services/lesson/hooks/addMaterial.js
  src/services/lesson/hooks/index.js
  src/services/user-group/services/courses.js
  test/hooks/restrictPopulate.test.js
  test/services/lessons/addMaterialService.test.js
  test/services/lessons/index.test.js
  test/services/lessons/lessonCopyService.test.js
  test/services/user-group/services/courses.test.js
Labels: auto update, ready to merge

#899 [SC-2934] fix login for deprecated local systems
  backup/setup/migrations.json
  backup/setup/systems.json
  migrations/1576570802025-removeUnnecessaryLocalSystems.js
  src/services/authentication/hooks/index.js
  src/services/helpers/service.js
  test/services/helpers/services/schools.js
Labels: data protection review approved, ready to merge

#1551 SC-5543 - implement register link QR service
  src/services/user/index.js
  src/services/user/services/QrRegistrationLinks.js
  src/services/user/services/index.js
  test/services/user/services/QrRegistrationLinks.test.js
Labels: auto update, ready to merge

#1615 Feature/SC-6087 - edusharing sanitazation issue
  src/services/edusharing/hooks/index.js
Labels: WIP

#1574 SC-5280: Improve LDAP error handling and logs
  CHANGELOG.md
  src/services/ldap/errors.js
  src/services/ldap/index.js
  src/services/sync/strategies/LDAPSchoolSyncer.js
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSystemSyncer.js
  src/services/sync/strategies/Syncer.js
  test/services/sync/strategies/Syncer.test.js
Labels: auto update, ready to merge

#1600 lowercase searchString before sending to SearchEngine
  src/services/edusharing/logic/connector.js
Labels: ready to merge

#1625 SC-6091 authentication retry edusharing. More specific error codes
  src/services/edusharing/logic/connector.js
Labels: WIP

#1418 Restrict Consent
  .travis.yml
  backup.js
  config/default.schema.json
  migrations/1596646151754-move_consent.js
  migrations/1596646314266-add_indexes_consent_version.js
  src/hooks/index.js
  src/services/consent/consent.deprecated.js
  src/services/consent/consentStatus.service.js
  src/services/consent/hooks/consentCheck.js
  src/services/consent/hooks/consents.js
  src/services/consent/index.js
  src/services/consent/model.js
  src/services/consent/services/consent.deprecated.js
  src/services/consent/services/consentCheck.service.js
  src/services/consent/utils/consent.js
  src/services/consent/utils/index.js
  src/services/role/hooks/index.js
  src/services/user/hooks/admin.js
  src/services/user/hooks/consent.js
  src/services/user/hooks/publicTeachers.js
  src/services/user/hooks/userService.js
  src/services/user/index.js
  src/services/user/model/user.schema.js
  src/services/user/services/AdminUsers.js
  src/services/user/services/UsersModelService.js
  src/services/user/services/userService.js
  src/services/user/utils/admin.js
  src/services/user/utils/aggregations.js
  src/services/user/utils/consent.js
  test/services/consent/hooks/consent.test.js
  test/services/consent/hooks/consentCheck.test.js
  test/services/consent/index.test.js
  test/services/consent/services/consentCheck.test.js
  test/services/consent/utils/consent.test.js
  test/services/consent/utils/helper.js
  test/services/helpers/services/consentVersion.js
  test/services/helpers/services/index.js
  test/services/helpers/testObjects.js
  test/services/user/services/AdminUsers.test.js
  test/services/user/services/userService.test.js
  test/services/user/unit.test.js
  test/services/user/utils/aggregations.test.js
Labels: auto update, ready to merge

#1626 SC-6122 preload edu sharing images
  src/services/edusharing/logic/connector.js
Labels: ready to merge

#1601 allow triggering sending StatMail without auth if trigger is internal
  src/services/statisticMail/hooks/index.js
Labels: ready to merge

#1599 SC-5070 change IDs of schools in DB-seed
  backup/setup/classes.json
  backup/setup/courses.json
  backup/setup/helpdocuments.json
  backup/setup/homeworks.json
  backup/setup/news.json
  backup/setup/schools.json
  backup/setup/submissions.json
  backup/setup/teams.json
  backup/setup/users.json
  migrations/1566293963302-add_help_documents.js
  src/services/fileStorage/docs/index.js
  src/services/fileStorage/utils/migrateS3ToFlat.js
  test/app.hooks.test.js
  test/services/account/services/accounts.test.js
  test/services/courses/index.test.js
  test/services/courses/services/courses.test.js
  test/services/fileStorage/aws/awsMultipleS3.test.js
  test/services/fileStorage/aws/awsS3.test.js
  test/services/helpers/testObjects.js
  test/services/homework/index.test.js
  test/services/rocketChat/index.test.js
  test/services/roster/index.test.js
  test/services/teams/helper/helper.user.js
  test/services/teams/services/admin.test.js
  test/services/user-group/index.test.js
  test/services/user/registration.test.js
  test/services/user/services/registrationSchool.test.js
  test/services/user/services/userService.test.js
  test/services/wopi/index.test.js
Labels: data protection review approved, ready to merge

#1655 SC-6248 extends the admin student route
  src/services/user/services/AdminUsers.js
  src/services/user/utils/aggregations.js
Labels: ready to merge

#1639 SC-4029 - send registrationlink mail
  src/services/sync/strategies/CSVSyncer.js
  src/services/user/hooks/userService.js
  src/services/user/services/AdminUsers.js
  src/services/user/services/MailRegistrationLink.js
  src/services/user/services/userService.js
Labels: auto update, ready to merge

#1640 SC-4008 - generate registrationLink
  config/globals.js
  src/services/link/index.js
Labels: auto update, ready to merge

#1656 Tf/revert feature revert
  .pullapprove.yml
  .travis.yml
  backup/setup/migrations.json
  backup/setup/systems.json
  config/default.json
  config/globals.js
  migrations/1576570802025-removeUnnecessaryLocalSystems.js
  package-lock.json
  package.json
  src/services/account/helper.js
  src/services/account/hooks/index.js
  src/services/account/templates/signup/html.ejs
  src/services/account/templates/signup/style.scss
  src/services/account/templates/signup/text.ejs
  src/services/authentication/hooks/index.js
  src/services/helpdesk/hooks/index.js
  src/services/helpers/service.js
  src/services/link/index.js
  src/services/user/firstLogin.js
  src/services/user/index.js
  src/services/user/model/user.schema.js
  src/services/user/services/ForcePasswordChange.js
  src/services/user/services/QrRegistrationLinks.js
  src/services/user/services/index.js
  src/utils/passwordHelpers.js
  test/helper/passwordHelpers.test.js
  test/services/helpers/services/schools.js
  test/services/user/services/ForcePasswordChange.test.js
  test/services/user/services/QrRegistrationLinks.test.js
Labels: WIP, do not merge

#1649 SC-6074 Improve logging of errors in registration
  backup/setup/migrations.json
  migrations/1597654308406-remove-importHashes-from-users-with-accounts.js
  package-lock.json
  package.json
  src/services/user/registration.js
Labels: needs data protection review

#1658 SC-6248 Further fix for find consents
  src/services/user/services/AdminUsers.js
  src/services/user/utils/aggregations.js
Labels: waiting for review

#1614 Hotfix SC-5983 Rework TSP consent process
  package-lock.json
  package.json
  src/services/authentication/strategies/TSPStrategy.js
  src/services/sync/strategies/TSP/TSP.js
  src/services/sync/strategies/TSP/TSPSchoolSyncer.js
Labels: waiting for review

#1660 Hotfix/2/disable ldap system changes
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap/index.js
  src/services/system/hooks/index.js
  src/services/system/hooks/searchUserPasswordEncryption.js
  src/services/system/hooks/verifyPayload.js
Labels: WIP, hotfix: do not merge here

#1627 SC-6122 - preload edusharing images parallel
  CHANGELOG.md
  src/services/edusharing/logic/EduSearchResponse.js
  src/services/edusharing/logic/connector.js
Labels: waiting for review

#1676 hotfix/24.4.5/SC-6328/ add migration to set StudentList Settings in schools to false
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/schools.json
  migrations/1598266672663-setStudentListSettingsInSchoolsToFalse.js
  package-lock.json
  package.json
Labels: ready to merge

#1602 SC-3909 revoke student creation for teachers
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1596723147575-revoke_student_creation_from_teachers.js
Labels: needs data protection review, waiting for review

#1678 THR Schuljahreswechsel
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/authentication/strategies/TSPStrategy.js
  src/services/sync/strategies/TSP/SchoolChange.js
  src/services/sync/strategies/TSP/TSPSchoolSyncer.js
Labels: WIP, hotfix: do not merge here

#1682 SC-6351 verify migrations
  .github/workflows/migrations.yml
  backup.js
  backup/setup/migrations.json
  package.json
Labels: data protection review approved, ready to merge

#1690 sc 6469
  CHANGELOG.md
  package-lock.json
  package.json
  src/hooks/index.js
  src/services/lesson/hooks/index.js
  test/services/lessons/index.test.js
Labels: hotfix: do not merge here, waiting for review
