Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-04, with the labels that each got.

#1112 Feature/sc 3821 homeworks for coteacher
  CHANGELOG.md
  src/services/homework/hooks/index.js
  src/services/homework/hooks/submissions.js
  test/services/homework/index.test.js
  test/services/homework/submissionService.test.js
Labels: ready to merge

#1121 Hotfix/22.7.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/hooks/index.js
Labels: do not merge

#1097 Feature/sc 3685 skip registration bulk route
  CHANGELOG.md
  src/services/user/hooks/skipRegistration.js
  src/services/user/index.js
  src/services/user/services/SkipRegistration.js
  test/services/user/services/SkipRegistration.integration.test.js
  test/services/user/services/SkipRegistration.test.js
Labels: waiting for review

#1118 Tf/user service structure refactoring
  src/services/user/hooks/userService.js
  src/services/user/index.js
  src/services/user/services/UsersModelService.js
  src/services/user/services/index.js
  src/services/user/services/userService.js
  test/app.hooks.redis.test.js
  test/app.hooks.test.js
  test/services/account/services/jwtTimerService.test.js
  test/services/authentication/hooks/index.test.js
  test/services/fileStorage/index.test.js
Labels: ready to merge

#1085 remove clipboard files and sockets
  .gitignore
  CHANGELOG.md
  migrations/1585131530713-remove clipboard.js
  src/services/clipboard/index.js
  src/services/index.js
  src/sockets/clipboard/actions.js
  src/sockets/clipboard/clipboard-model.js
  src/sockets/clipboard/index.js
  src/sockets/clipboard/upload.js
  src/sockets/index.js
Labels: ready to merge

#1135 Feature/SC-3944/Fix upload of school logo
  src/services/school/hooks/index.js
Labels: ready to merge

#1134 Fix: Messenger discard failed message after one retry
  src/services/messengerSync/consumer.js
Labels: ready to merge

#1069 add birthday to csv syncer
  CHANGELOG.md
  src/services/sync/strategies/CSVSyncer.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.unit.test.js
Labels: ready to merge

#1091 SC-3767 move process.env calls to globals file
  .eslintrc.json
  CHANGELOG.md
  config/default.json
  config/globals.js
  config/secrets.js
  config/test.json
  src/app.js
  src/hooks/index.js
  src/logger/index.js
  src/logger/systemLogger.js
  src/middleware/errorHandler.js
  src/middleware/requestLogger.js
  src/middleware/sentry.js
  src/services/analytics/index.js
  src/services/authentication/hooks/index.js
  src/services/authentication/logic/index.js
  src/services/consent/config.js
  src/services/consent/hooks/consents.js
  src/services/fileStorage/SecurityCheckService.js
  src/services/fileStorage/proxy-service.js
  src/services/fileStorage/strategies/awsS3.js
  src/services/helpers/service.js
  src/services/ldap/strategies/iserv.js
  src/services/ldap/strategies/univention.js
  src/services/link/index.js
  src/services/passwordRecovery/hooks/index.js
  src/services/rocketChat/helpers.js
  src/services/rocketChat/index.js
  src/services/rocketChat/rocketChatConfig.js
  src/services/school/hooks/index.js
  src/services/sync/strategies/CSVSyncer.js
  src/services/sync/strategies/TSP/TSP.js
  src/services/teams/hooks/index.js
  src/services/teams/hooks/mail-text.js
  src/services/teams/index.js
  src/services/teams/services/admin.js
  src/services/user/hooks/registrationPins.js
  src/services/user/hooks/userService.js
  src/services/user/registration.js
  src/utils/database.js
  test/services/helpers/service.test.js
  test/services/oauth2/index.test.js
  test/services/rocketChat/index.test.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
  test/services/teams/helper/helper.hook.js
  test/services/teams/helper/helper.user.js
Labels: ready to merge

#1129 Feature/sc 3671 bulk delete users
  CHANGELOG.md
  src/services/user/hooks/userService.js
  src/services/user/services/userService.js
  test/services/user/hooks/index.hooks.test.js
  test/services/user/hooks/userService.hooks.test.js
  test/services/user/services/userService.test.js
  test/services/user/unit.test.js
Labels: ready to merge

#1133 Feature/sc 3640 case insensitive sorting
  CHANGELOG.md
  src/hooks/index.js
  src/services/homework/hooks/index.js
  src/services/user-group/services/classes.js
  src/services/user-group/services/courses.js
  src/services/user/hooks/publicTeachers.js
  src/services/user/services/AdminUsers.js
  src/services/user/services/userService.js
Labels: ready to merge

#1132 SC-3395 | return error, if release fetch failed
  CHANGELOG.md
  src/services/releases/index.js
Labels: ready to merge

#1145 Feature/SC-2922/School file storage administration
  src/services/school/hooks/index.js
Labels: ready to merge

#1125 migrate backup.sh to backup.js
  CHANGELOG.md
  backup.js
  backup.sh
  package-lock.json
  package.json
Labels: ready to merge

#1137 Feature/sc 3948 adminusers query
  CHANGELOG.md
  src/services/user-group/services/classes.js
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: ready to merge

#1104 jwt expiration in redis increased for private devices
  src/app.hooks.js
  src/services/account/services/SupportJWTService.js
  src/services/account/services/jwtTimerService.js
  src/services/authentication/hooks/index.js
  src/utils/redis.js
  test/app.hooks.redis.test.js
  test/services/account/services/jwtTimerService.test.js
  test/services/authentication/hooks/index.test.js
Labels: ready to merge

#1142 SC-3958 cleanup ldap service
  CHANGELOG.md
  config/globals.js
  src/services/ldap/index.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/index.js
  src/services/ldap/strategies/interface.js
  src/services/ldap/strategies/iserv.js
  src/services/ldap/strategies/univention.js
Labels: ready to merge

#1159 Disallow unused routes
  src/services/content/hooks/index.js
Labels: ready to merge

#1153 SC-4000 trigger messenger sync on user creation
  src/services/messengerSync/consumer.js
  src/services/messengerSync/eventListener.js
  src/services/messengerSync/services/messengerTokenService.js
  src/services/messengerSync/services/schoolSyncService.js
  src/services/messengerSync/utils.js
  test/services/messengerSync/rabbitmqMock.js
  test/services/messengerSync/services/schoolSyncService.test.js
  test/services/messengerSync/utils.test.js
Labels: ready to merge

#1167 add missing peers, sort dependencies, audit fix
  package-lock.json
  package.json
Labels: ready to merge

#1168 update commoins to 1.0.20, remove typescript
  package-lock.json
  package.json
Labels: ready to merge

#1157 SC-3892 | Update Filter of submission to work with older submissions
  CHANGELOG.md
  src/services/homework/hooks/index.js
Labels: ready to merge

#1180 fix api-key-strategy with queryparams
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/authentication/strategies/ApiKeyStrategy.js
Labels: hotfix: do not merge here

#1162 SC-4013: trigger school sync on school update
  .eslintrc.json
  .gitignore
  config/default.schema.json
  src/services/messengerSync/consumer.js
  src/services/messengerSync/eventListener.js
  src/services/messengerSync/index.js
  src/services/messengerSync/producer.js
  src/services/messengerSync/services/schoolSyncService.js
  src/services/messengerSync/testConsumer.js
  src/services/messengerSync/utils.js
  src/services/user-group/logic/courses.js
  src/utils/rabbitmq.js
  test/services/messengerSync/rabbitmqMock.js
  test/services/messengerSync/services/schoolSyncService.test.js
  test/services/messengerSync/utils.test.js
Labels: ready to merge

#1194 Run a single unit test
  README.md
  package.json
Labels: ready to merge

#1215 Move "chai" packages to "devDependencies"
  package.json
Labels: ready to merge

#1227 fix user tests
  CHANGELOG.md
  test/services/user/services/userService.test.js
Labels: ready to merge

#1202 [#SC-4064] Remove obsolete comment model
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/submissions.json
  migrations/1587545242723-drop-comment-model.js
  src/services/homework/hooks/comments.js
  src/services/homework/model-service.js
  src/services/homework/model.js
  src/services/statistic/index.js
Labels: ready to merge

#1229 SC-4114/Filter Fix lastName
  src/services/user/services/AdminUsers.js
Labels: ready to merge

#1212 Fix whitespace in shell scripts
  backup.sh
  deploy.sh
  startup.sh
Labels: ready to merge

#1207 Fix further lint issues
  src/services/account/index.js
  src/services/homework/hooks/submissions.js
  src/services/rocketChat/randomPass.js
  src/services/user/registration.js
  src/services/user/services/SkipRegistration.js
  test/services/content/content.test.js
  test/services/teams/hooks/collection.test.js
Labels: ready to merge

#1195 Fix test output
  config/globals.js
  src/app.js
  src/index.js
Labels: waiting for review
