Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2020-12, with the labels that each got.

#2006 fix type script error
  CHANGELOG.md
  package-lock.json
  package.json
Labels: auto update, ready to merge, waiting for review

#2013 SC-6727 Change email address - fix implementation after ops review
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/services/helpdesk/hooks/index.js
  test/services/helpdesk/index.test.js
Labels: WIP

#2021 SC-6294 - fixed test issues, coverage reporter changed
  .mocharc.js
  .nycrc.json
  CHANGELOG.md
  tsconfig.json
Labels: ready to merge

#2031 hotfix/4/SC-8077 - migration copy parents to users broken
  CHANGELOG.md
  migrations/1601022564938-copy-parents-data-into-children-entities-and-delete-parent-users.js
  package-lock.json
  package.json
Labels: waiting for review

#2025 valid merlin url will be created as soon as the course is accessed
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/lesson/hooks/index.js
Labels: do not merge, waiting for review

#2019 SC-6692 - adds lern-store county filter
  CHANGELOG.md
  backup/setup/migrations.json
  config/default.schema.json
  migrations/1606739119373-merlin_credentials.js
  src/services/edusharing/helpers.js
  src/services/edusharing/index.js
  src/services/edusharing/services/EduSharingConnector.js
  src/services/edusharing/services/MerlinTokenGenerator.js
  src/services/federalState/countyModel.js
  src/services/lesson/hooks/index.js
Labels: ready to merge

#1967 Feature/reuse docker container
  .travis.yml
  CHANGELOG.md
  Dockerfile
  config/default.schema.json
  config/production.json
  config/test.json
  package-lock.json
  src/services/helpers/service.js
  test/services/activation/services/activationService.test.js
  test/services/activation/services/eMailAddress/index.test.js
  test/services/helpers/service.test.js
Labels: auto update, ready to merge

#1997 [SC-7543] new LDAP config service
  .nodemon.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/errors/utils.js
  src/middleware/errorHandler.js
  src/services/docs/openapi.yaml
  src/services/index.js
  src/services/ldap-config/docs/openapi.yaml
  src/services/ldap-config/docs/schemas/dnRegexPattern.txt
  src/services/ldap-config/docs/schemas/error.response.yaml
  src/services/ldap-config/docs/schemas/get.response.yaml
  src/services/ldap-config/docs/schemas/patch.requestBody.yaml
  src/services/ldap-config/docs/schemas/post.requestBody.yaml
  src/services/ldap-config/docs/schemas/verify.response.yaml
  src/services/ldap-config/errors.js
  src/services/ldap-config/hooks/fillDefaultValues.js
  src/services/ldap-config/hooks/index.js
  src/services/ldap-config/index.js
  src/services/ldap-config/service.js
  src/services/ldap/LDAPConnectionError.js
  src/services/ldap/index.js
  src/services/system/model.js
  src/utils/apiValidation.js
  test/services/ldap-config/assets/knownBadConfig.json
  test/services/ldap-config/assets/knownGoodConfig.json
  test/services/ldap-config/errors.unit.test.js
  test/services/ldap-config/hooks/fillDefaultValues.test.js
  test/services/ldap-config/service.integration.test.js
  test/services/ldap-config/service.unit.test.js
  test/services/user/services/AdminUsers.integration.test.js
Labels: API, auto update, ready to merge

#2054 hotfix/25.2.6/fix sentry disabling and remove sanitization by read operations
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.hooks.js
  src/errors/utils.js
Labels: waiting for review

#2056 Hotfix/25.3.3 - boundle of 25.2 hotfixes
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.hooks.js
  src/errors/utils.js
  src/services/fileStorage/strategies/awsS3.js
Labels: waiting for review

#2057 SC-7998 Hotfix 25.3.4 move version route to be a feathers service
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.js
  src/services/docs/openapi.yaml
  src/services/index.js
  src/services/versionService/docs/openapi.yaml
  src/services/versionService/hooks/index.js
  src/services/versionService/index.js
  src/services/versionService/services/Version.js
Labels: waiting for review

#2017 feature/SC-7483 adjust backend for shd consent upload
  CHANGELOG.md
  src/helper/userHelpers.js
  src/services/consent/services/consentVersionService.js
  test/services/consent/index.test.js
Labels: waiting for review

#2047 SC-6692 - migration should not throw error
  migrations/1606739119373-merlin_credentials.js
Labels: ready to merge

#2061 Hotfix/1/sc 8149 registration pin in sync
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/LDAPSchoolSyncer.js
  src/services/sync/strategies/TSP/TSP.js
  src/services/user/services/userService.js
Labels: WIP

#2065 sc-8179 build repaired
  CHANGELOG.md
  test/services/helpers/services/users.js
Labels: auto update, ready to merge, waiting for review

#2026 Feature/sc 8030/refactor delete user uc
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/user/index.js
  src/components/user/repo/registrationPin.repo.js
  src/components/user/repo/user.repo.integration.test.js
  src/components/user/repo/user.repo.js
  src/components/user/services/index.js
  src/components/user/services/user.service.v2.integration.test.js
  src/components/user/services/user.service.v2.js
  src/components/user/uc/registrationPin.facade.js
  src/components/user/uc/registrationPin.uc.js
  src/components/user/uc/userRoles.uc.js
  src/components/user/uc/userRoles.unit.test.js
  src/components/user/uc/users.facade.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
Labels: auto update, ready to merge

#1981 SC-7841 introduced class repo
  CHANGELOG.md
  src/components/user-group/repo/classes.repo.integration.test.js
  src/components/user-group/repo/classes.repo.js
  src/components/user-group/repo/index.js
  src/components/user-group/uc/classes.facade.js
  src/components/user-group/uc/deleteUserData.uc.js
  src/components/user-group/uc/deleteUserData.unit.test.js
  src/errors/index.js
  src/helper/compare.js
Labels: auto update, ready to merge

#1973 Feature/sc 7827/delete shared files with users
  CHANGELOG.md
  package-lock.json
  src/components/fileStorage/index.js
  src/components/fileStorage/repo/db/index.js
  src/components/fileStorage/repo/files.repo.integration.test.js
  src/components/fileStorage/repo/files.repo.js
  src/components/fileStorage/repo/index.js
  src/components/fileStorage/repo/strategies/index.js
  src/components/fileStorage/uc/applicationInternal/removePermissions.js
  src/components/fileStorage/uc/deleteUserData.uc.js
  src/components/fileStorage/uc/deleteUserData.uc.unit.test.js
  src/components/fileStorage/uc/fileStorage.facade.integration.test.js
  src/components/fileStorage/uc/fileStorage.facade.js
  src/components/index.js
  src/components/user/repo/account.repo.integration.test.js
  test/services/helpers/services/files.js
  test/services/helpers/testObjects.js
Labels: ready to merge

#2020 SC-7825 delete course data
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/course/repo/courseGroups.repo.js
  src/components/course/repo/courses.repo.integration.test.js
  src/components/course/repo/courses.repo.js
  src/components/course/repo/coursesGroups.repo.integration.test.js
  src/components/course/repo/db/lesson.js
  src/components/course/repo/index.js
  src/components/course/repo/lessons.repo.integration.test.js
  src/components/course/repo/lessons.repo.js
  src/components/course/uc/courses.facade.js
  src/components/course/uc/deleteUserData.integration.test.js
  src/components/course/uc/deleteUserData.uc.js
  src/components/course/uc/deleteUserData.unit.test.js
  src/components/course/uc/deleteUserData/deleteUserDataSteps.js
  src/components/fileStorage/repo/files.repo.js
  src/components/helper/repo.helper.js
  src/components/user-group/repo/classes.repo.integration.test.js
  src/components/user-group/repo/classes.repo.js
  src/components/user-group/uc/deleteUserData.uc.js
  src/components/user-group/uc/deleteUserData.unit.test.js
  test/services/helpers/services/courses.js
  test/services/helpers/services/lessons.js
  test/services/helpers/testObjects.js
Labels: ready to merge

#2076 changelog fix
  CHANGELOG.md
Labels: ready to merge

#2070 SC-7763 - adds searchable flag for lern-store results
  CHANGELOG.md
  config/default.schema.json
  config/test.json
  src/services/edusharing/services/EduSharingConnector.js
  test/services/edusharing/services/EduSharingConnector.test.js
Labels: ready to merge

#2071 SC-8020 - adds collection filter to lernstore
  CHANGELOG.md
  config/default.schema.json
  config/test.json
  src/services/edusharing/docs/openapi.yaml
  src/services/edusharing/services/EduSharingConnector.js
  src/services/lesson/hooks/index.js
  test/services/edusharing/services/EduSharingConnector.test.js
Labels: ready to merge

#2079 SC-8229 - Invalid DN error handling
  CHANGELOG.md
  src/services/ldap-config/errors.js
Labels: auto update, auto_merged, ready to merge

#2081 SC-8219 - Removed required attributes
  CHANGELOG.md
  src/services/ldap-config/docs/schemas/get.response.yaml
  src/services/ldap-config/docs/schemas/patch.requestBody.yaml
  src/services/ldap-config/docs/schemas/post.requestBody.yaml
Labels: auto update, auto_merged, ready to merge

#2086 Hotfix/3/sc 8235 registration link generation
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/services/QrRegistrationLinks.js
  test/services/user/services/QrRegistrationLinks.test.js
Labels: do not merge, waiting for review

#2089 Add team indexes and migration
  CHANGELOG.md
  migrations/1608214028384-syncTeamIndexes.js
  src/services/teams/model.js
Labels: waiting for review

#2090 SC-8209 Hotfix 25.3.6 continue ldap sync when a single user fails
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/LDAPSchoolSyncer.js
  src/services/sync/strategies/TSP/SchoolChange.js
Labels: waiting for review

#2093 SC-7763 - fixes searchable flag for lernstore items
  CHANGELOG.md
  src/services/edusharing/services/EduSharingConnector.js
Labels: ready to merge

#2099 Hotfix/4/sc 8198 continue on sync issues
  CHANGELOG.md
  src/services/sync/strategies/Syncer.js
  src/services/sync/strategies/TSP/SchoolChange.js
  src/services/sync/strategies/TSP/TSPSchoolSyncer.js
Labels: WIP

#2085 Feature/sc 7835 deletion concept problems
  CHANGELOG.md
  src/components/helpdesk/repo/index.js
  src/components/helpdesk/repo/problem.repo.integration.test.js
  src/components/helpdesk/repo/problem.repo.js
  src/components/helpdesk/uc/helpdesk.facade.js
  src/components/helpdesk/uc/helpdesk.uc.js
  src/components/helpdesk/uc/helpdesk.unit.test.js
  src/components/helper/repo.helper.js
  src/components/helper/uc.helper.js
  test/services/helpers/services/index.js
  test/services/helpers/services/problems.js
  test/services/helpers/testObjects.js
Labels: WIP, auto update
