Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-06, with the labels that each got.

#2554 [OPS-2418] add E2E tests only for PRs on feature branch
  .travis.yml
  CHANGELOG.md
  build.sh
Labels: WIP

#2572 SC-9103 add logging for syncIndexes script
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/syncIndexes.js
Labels: ready to merge

#2586 fix dependencies issue
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#2504 SC-9018; SC-9003 - created schoolsList public endpoint
  CHANGELOG.md
  src/services/school/docs/openapi.yaml
  src/services/school/hooks/index.js
  src/services/school/hooks/publicSchools.hooks.js
  src/services/school/index.js
  src/services/school/services/schoolsList.js
  test/routes/whitelist.js
  test/services/school/index.test.js
Labels: ready to merge, waiting for review

#2592 Hotfix/SC-8898 ldap rabbit poc
  .travis.yml
  CHANGELOG.md
  backup/setup/migrations.json
  config/default.schema.json
  config/development.json
  config/test.json
  migrations/1620316360923-LDAPSyncIndices.js
  package-lock.json
  package.json
  src/errors/applicationErrors.js
  src/errors/index.js
  src/logger/syncLogger.js
  src/services/account/model.js
  src/services/school/model.js
  src/services/sync/index.js
  src/services/sync/repo/class.repo.js
  src/services/sync/repo/index.js
  src/services/sync/repo/school.repo.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/LDAPSchoolSyncer.js
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSyncerConsumer.js
  src/services/sync/strategies/LDAPSystemSyncer.js
  src/services/sync/strategies/SyncMessageBuilder.js
  src/services/sync/strategies/Syncer.js
  src/services/sync/strategies/consumerActions/BaseConsumerAction.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  src/services/sync/strategies/consumerActions/SchoolAction.js
  src/services/sync/strategies/consumerActions/UserAction.js
  src/services/sync/strategies/consumerActions/index.js
  src/services/sync/utils/index.js
  src/services/sync/utils/index.test.js
  src/services/user-group/model.js
  src/services/user/model/user.schema.js
  test/services/helpers/services/classes.js
  test/services/helpers/services/roles.js
  test/services/sync/LdapSync.integration.test.js
  test/services/sync/repo/class.repo.integration.test.js
  test/services/sync/repo/school.repo.integration.test.js
  test/services/sync/repo/user.repo.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.test.js
  test/services/sync/strategies/LDAPSyncerProducer.test.js
  test/services/sync/strategies/SyncMessageBuilder.test.js
  test/services/sync/strategies/consumerActions/ BaseConsumerAction.test.js
  test/services/sync/strategies/consumerActions/ClassAction.test.js
  test/services/sync/strategies/consumerActions/SchoolAction.test.js
  test/services/sync/strategies/consumerActions/UserAction.test.js
Labels: WIP

#2587 Odyssey task pagination
  apps/server/src/modules/task/controller/dto/index.ts
  apps/server/src/modules/task/controller/dto/task-query.dto.ts
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/entity/index.ts
  apps/server/src/modules/task/entity/task.option.entity.ts
  apps/server/src/modules/task/repo/task.repo.integration.spec.ts
  apps/server/src/modules/task/repo/task.repo.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/shared/core/controller/dto/pagination.query.dto.ts
  apps/server/src/shared/core/controller/dto/pagination.response.dto.ts
  apps/server/src/shared/core/types/paginated.ts
  apps/server/test/modules/task/task.e2e-spec.ts
Labels: WIP, do not merge

#2488 SC-8959 Add messenger to deletion concept
  CHANGELOG.md
  src/components/index.js
  src/components/messenger/index.js
  src/components/messenger/repo/messenger.repo.js
  src/components/messenger/uc/deleteUserData.uc.js
  src/components/messenger/uc/messenger.facade.js
  src/components/user/uc/users.uc.js
  src/services/messengerSync/eventListener.js
Labels: waiting for review

#2613 Delete update_version.yml
  .github/workflows/update_version.yml
Labels: waiting for review

#2620 SC-9134 - Add missing mongo indexes for LDAP Sync
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/repo/user.repo.js
  src/services/user/model/user.schema.js
Labels: auto update, waiting for review

#2569 SC-9092 delete S3 files
  CHANGELOG.md
  migrations/1622209795280-add_S3_expiration.js
  src/services/fileStorage/strategies/awsS3.js
  test/services/fileStorage/aws/s3.mock.js
Labels: ready to merge

#2618 SC-9029 - Change place of the channel creation for RabbitMQ.
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSystemSyncer.js
Labels: auto update, waiting for review

#2644 improve syncIndex
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/syncIndexes.js
Labels: ready to merge

#2619 SC-9139 - Add a check if user roles should be updated or not to the repo
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/repo/user.repo.js
Labels: auto update, waiting for review

#2646 rename permission TASK_DASHBOARD_VIEW_V3
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1623849218703-rename-task-permission.js
  package-lock.json
  package.json
Labels: waiting for review

#2596 SC-9093 add default language and timezone to config service
  CHANGELOG.md
  config/default.json
  config/default.schema.json
  src/services/config/publicAppConfigService.js
  test/services/config/hooks/services/publicAppConfigService.test.js
Labels: waiting for review

#2653 remove unneccesary timeout rules replaced by correct promise handling
  CHANGELOG.md
  TODO.md
  apps/server/doc/testing.md
  test/app.hooks.redis.test.js
  test/jobs/rss-news/index.integration.test.js
  test/services/account/iserv/iserv.test.js
  test/services/authentication/authentication.integration.test.js
  test/services/authentication/hooks/index.test.js
  test/services/calendar/index.test.js
  test/services/courses/services/courseMembers.test.js
  test/services/datasources/datasourceRuns.test.js
Labels: WIP

#2654 fix nest test/debug configuration
  .vscode/launch.default.json
  package.json
Labels: WIP

#2659 SC-9156: Add maintenance mode for LDAP rewrite
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/repo/school.repo.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  src/services/sync/strategies/consumerActions/UserAction.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/consumerActions/ClassAction.test.js
  test/services/sync/strategies/consumerActions/UserAction.test.js
Labels: waiting for review

#2665 Feature/sc 6294 typescript nestjs news
  apps/server/doc/testing.md
  apps/server/src/modules/authorization/authorization.service.spec.ts
  apps/server/src/modules/authorization/authorization.service.ts
  apps/server/src/modules/authorization/feathers-auth.provider.ts
  apps/server/src/modules/database/index.ts
  apps/server/src/modules/database/mongo-database/index.ts
  apps/server/src/modules/database/mongo-database/mongo-database.module.ts
  apps/server/src/modules/database/mongo-database/mongo-shared-connection.ts
  apps/server/src/modules/database/mongo-database/mongo-shared-driver.ts
  apps/server/src/modules/news/controller/news.controller.ts
  apps/server/src/modules/news/entity/news.entity.ts
  apps/server/src/modules/news/entity/news.types.ts
  apps/server/src/modules/news/mapper/news.mapper.spec.ts
  apps/server/src/modules/news/mapper/news.mapper.ts
  apps/server/src/modules/news/repo/news-target-filter.ts
  apps/server/src/modules/news/repo/news.repo.integration.spec.ts
  apps/server/src/modules/news/repo/news.repo.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/task/repo/task.repo.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/domain/interface/find-options.ts
  apps/server/src/shared/domain/interface/index.ts
  apps/server/src/shared/domain/interface/pagination.interface.ts
  apps/server/src/shared/domain/interface/sorting.ts
  apps/server/src/shared/repo/base.repo.integration.spec.ts
  apps/server/src/shared/repo/base.repo.ts
  apps/server/test/modules/news/news.e2e-spec.ts
Labels: WIP

#2662 Feature/authenticaion
  .vscode/launch.default.json
  apps/server/src/modules/authentication/auth.module.ts
  apps/server/src/modules/authentication/constants.ts
  apps/server/src/modules/authentication/interface/jwt-payload.ts
  apps/server/src/modules/authentication/strategy/jwt.strategy.ts
  apps/server/src/modules/database/mongo-memory-database/mongo-memory-database.module.ts
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/user/controller/dto/ResolvedUser.dto.ts
  apps/server/src/modules/user/controller/dto/index.ts
  apps/server/src/modules/user/controller/index.ts
  apps/server/src/modules/user/controller/user.controller.spec.ts
  apps/server/src/modules/user/controller/user.controller.ts
  apps/server/src/modules/user/entity/account.entity.ts
  apps/server/src/modules/user/entity/index.ts
  apps/server/src/modules/user/entity/role.entity.ts
  apps/server/src/modules/user/entity/user.entity.ts
  apps/server/src/modules/user/index.ts
  apps/server/src/modules/user/mapper/ResolvedUser.mapper.spec.ts
  apps/server/src/modules/user/mapper/ResolvedUser.mapper.ts
  apps/server/src/modules/user/mapper/index.ts
  apps/server/src/modules/user/repo/account.repo.ts
  apps/server/src/modules/user/repo/index.ts
  apps/server/src/modules/user/repo/role.repo.integration.spec.ts
  apps/server/src/modules/user/repo/role.repo.ts
  apps/server/src/modules/user/repo/user.repo.integration.spec.ts
  apps/server/src/modules/user/repo/user.repo.ts
  apps/server/src/modules/user/uc/index.ts
  apps/server/src/modules/user/uc/role.uc.spec.ts
  apps/server/src/modules/user/uc/role.uc.ts
  apps/server/src/modules/user/uc/user.uc.spec.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.facade.spec.ts
  apps/server/src/modules/user/user.facade.ts
  apps/server/src/modules/user/user.module.ts
  apps/server/src/modules/user/utils/createCurrentTestUser.ts
  apps/server/src/modules/user/utils/index.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/domain/entity/base.entity.ts
  apps/server/test/modules/task/task.e2e-spec.ts
  jest.config.ts
Labels: WIP

#2667 OPS-2466 - changes build pipeline to github actions
  .dockerignore
  .github/workflows/build_push_service.yml
  .github/workflows/main.yml
  .github/workflows/tag.yml
  .travis.yml
  CHANGELOG.md
  Dockerfile
  ansible/group_vars/all/schulcloud-server.yml
  ansible/group_vars/brb/schulcloud-server.yml
  ansible/group_vars/nbc/schulcloud-server.yml
  ansible/roles/schulcloud-server/tasks/main.yml
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  ansible/roles/schulcloud-server/templates/configmap_file_init_db.yml.j2
  ansible/roles/schulcloud-server/templates/deployment.yml.j2
  ansible/roles/schulcloud-server/templates/job_init_db.yml.j2
  ansible/roles/schulcloud-server/templates/onepassword.yml.j2
  ansible/roles/schulcloud-server/templates/secret.yml.j2
  ansible/roles/schulcloud-server/templates/svc.yml.j2
  build.sh
  package-lock.json
  package.json
  scripts/deploy.sh
  src/index.js
  src/middleware/legacyForward.js
Labels: waiting for review

#2669 Feature/sc 8448 fix merlin url
  CHANGELOG.md
  src/services/edusharing/services/EduSharingConnector.js
  src/services/edusharing/services/MerlinTokenGenerator.js
  src/services/lesson/hooks/index.js
  test/services/edusharing/services/EduSharingConnector.test.js
Labels: WIP

#2664 Hotfix/SC-9149 brb sjw
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1624360656497-start_new_school_year_brb.js
  package-lock.json
  package.json
Labels: WIP

#2700 fix route forwarding
  CHANGELOG.md
  package-lock.json
  package.json
  src/middleware/legacyForward.js
  src/services/me/index.js
Labels: waiting for review

#2705 fix /api route forwarding
  CHANGELOG.md
  package-lock.json
  package.json
  src/app.js
  src/middleware/apiPath.js
  src/middleware/legacyForward.js
Labels: WIP

#2706 add github test actions
  .github/workflows/test.yml
  .github/workflows/test_e2e.yml
  CHANGELOG.md
  scripts/e2eTest.sh
  scripts/unitTestFeathers.sh
  scripts/unitTestNest.sh
Labels: WIP

#2672 Feature/SC-9170 - let superhero delete users
  CHANGELOG.md
  src/components/helper/uc.helper.js
  src/components/helper/uc.helper.unit.test.js
  src/components/user/services/user.service.v2.integration.test.js
  src/components/user/uc/users.uc.js
Labels: WIP

#2710 set node js version in test actions
  .github/workflows/test.yml
Labels: WIP
