Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-01, with the labels that each got.

#2123 Release/25.5.0 fix firstlogin
  CHANGELOG.md
  src/services/user/hooks/registrationPins.js
Labels: WIP

#2135 get last updated object
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/calendar/hooks/index.js
Labels: waiting for review

#2136 migrations.json
  backup/setup/migrations.json
Labels: WIP

#1776 SC-5287/Fix OAuth2 roster bug
  CHANGELOG.md
  src/services/roster/index.js
  test/services/roster/index.test.js
Labels: WIP

#2131 feature/SC-8322 - prevent s3 provider inconsistencies
  CHANGELOG.md
  src/services/fileStorage/strategies/awsS3.js
  src/services/fileStorage/strategies/interface.js
  src/services/fileStorage/utils/providerAssignmentHelper.js
  test/services/fileStorage/aws/awsS3.test.js
  test/services/fileStorage/aws/s3.mock.js
  test/services/fileStorage/utils/providerAssignmentHelper.test.js
  test/services/helpers/services/schools.js
Labels: WIP, auto update

#2141 Feature/sc 8322 improve s3 stability
  backup/setup/migrations.json
  src/errors/utils.js
  src/services/fileStorage/strategies/awsS3.js
Labels: WIP

#2117 Feature/sc 8029 integration of pseudonyms
  CHANGELOG.md
  src/components/course/uc/deleteUserData/deleteUserDataSteps.js
  src/components/helpdesk/repo/problem.repo.js
  src/components/helpdesk/uc/helpdesk.facade.js
  src/components/helpdesk/uc/helpdesk.uc.js
  src/components/helper/uc.helper.js
  src/components/helper/validation.helper.js
  src/components/pseudonym/repo/pseudonym.repo.integration.test.js
  src/components/pseudonym/repo/pseudonym.repo.js
  src/components/pseudonym/uc/pseudonym.facade.js
  src/components/pseudonym/uc/pseudonym.uc.js
  src/components/pseudonym/uc/pseudonym.unit.test.js
  src/components/user-group/uc/deleteUserData.uc.js
  src/components/user/repo/registrationPin.repo.integration.test.js
  src/components/user/repo/registrationPin.repo.js
  src/components/user/uc/registrationPin.facade.js
  src/components/user/uc/registrationPin.uc.js
  src/components/user/uc/users.uc.js
Labels: WIP, auto update

#1703 clear examples
  src/services/fileStorage/docs/index.js
Labels: WIP, auto update

#2139 Feature/sc 8379 secure lti tools route
  src/services/ltiTool/hooks/index.js
  test/services/ltiTool/index.test.js
Labels: waiting for review

#2165 add pseudonym model in api schema
  src/services/pseudonym/docs/openapi.yaml
  src/services/roster/docs/openapi.yaml
Labels: WIP

#2166 Hotfix/3/sc 8420 sync indexes
  CHANGELOG.md
  backup/setup/migrations.json
  config/development.json
  migrations/1610972728660-syncIndexes.js
  package-lock.json
  package.json
  src/services/fileStorage/model.js
  src/services/homework/model.js
  src/services/lesson/model.js
  src/services/news/model.js
  src/services/role/model.js
  src/services/school/model.js
  src/services/teams/model.js
  src/services/user-group/model.js
  src/services/user/model/registrationPin.schema.js
  src/services/user/model/user.schema.js
  src/services/videoconference/model.js
Labels: waiting for review

#2171 SC-8322: throw error for upload if storage provider was updated
  src/services/fileStorage/strategies/awsS3.js
  test/services/fileStorage/aws/awsS3.test.js
Labels: WIP

#2140 SC-5461 Hotfix/7/better marks release
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1610965479712-update-pseudonym-indexes.js
  package-lock.json
  package.json
  src/services/ltiTool/hooks/index.js
  src/services/pseudonym/docs/openapi.yaml
  src/services/pseudonym/hooks/index.js
  src/services/pseudonym/model.js
  src/services/roster/docs/openapi.yaml
  src/services/roster/hooks/index.js
  src/services/roster/index.js
  test/services/helpers/services/ltiTools.js
  test/services/ltiTool/index.test.js
  test/services/pseudonym/index.test.js
  test/services/roster/index.test.js
Labels: WIP

#2174 fix aws test
  test/services/fileStorage/aws/awsS3.test.js
Labels: WIP

#2175 Hotfix/1/clean up s3 inconsistencies
  CHANGELOG.md
  backup/setup/migrations.json
  config/development.json
  migrations/1609942742732-fixStorageProviderInconsistencies.js
  migrations/1610965479712-update-pseudonym-indexes.js
  migrations/1610972728660-syncIndexes.js
  package-lock.json
  package.json
  src/services/calendar/hooks/index.js
  src/services/fileStorage/model.js
  src/services/homework/model.js
  src/services/lesson/model.js
  src/services/ltiTool/hooks/index.js
  src/services/news/model.js
  src/services/pseudonym/docs/openapi.yaml
  src/services/pseudonym/hooks/index.js
  src/services/pseudonym/model.js
  src/services/role/model.js
  src/services/roster/docs/openapi.yaml
  src/services/roster/hooks/index.js
  src/services/roster/index.js
  src/services/school/model.js
  src/services/teams/model.js
  src/services/user-group/model.js
  src/services/user/model/registrationPin.schema.js
  src/services/user/model/user.schema.js
  src/services/videoconference/model.js
  test/services/helpers/services/ltiTools.js
  test/services/ltiTool/index.test.js
  test/services/pseudonym/index.test.js
  test/services/roster/index.test.js
Labels: WIP

#2100 Feature/sc 8213 error handling
  .prettierrc.js
  CHANGELOG.md
  src/components/fileStorage/repo/files.repo.js
  src/components/user-group/repo/classes.repo.integration.test.js
  src/components/user-group/repo/classes.repo.js
  src/components/user-group/uc/deleteUserData.uc.js
  src/components/user-group/uc/deleteUserData.unit.test.js
  src/errors/applicationErrors.js
  src/errors/commonErrorTypes.js
  src/errors/helper/assertionErrorHelper.js
  src/errors/index.js
  src/errors/utils.js
  src/middleware/errorHandler.js
  src/services/ldap/LDAPConnectionError.js
  src/services/ldap/index.js
  src/services/passwordRecovery/services/ChangePasswordService.js
  test/app.test.ts
  test/errors/index.test.js
  test/services/ldap-config/service.integration.test.js
Labels: auto update, ready to merge

#2122 SC-4576 sanitize bbb room and member names
  CHANGELOG.md
  src/errors/helper/assertionErrorHelper.js
  src/services/videoconference/logic/index.js
  test/services/videoconference/logic/index.js
Labels: ready to merge

#2184 SC-8390 - prevents Lern-Store collections search when flag is false
  CHANGELOG.md
  src/services/edusharing/services/EduSharingConnector.js
  test/services/edusharing/services/EduSharingConnector.test.js
Labels: ready to merge

#2121 SC-8300 consolidate logging of (ldap-)syncer
  .gitignore
  CHANGELOG.md
  src/services/messengerSync/utils.js
  src/services/sync/strategies/CSVSyncer.js
  src/services/sync/strategies/LDAPSchoolSyncer.js
  src/services/sync/strategies/Syncer.js
  src/services/user/docs/adminusers.openapi.yaml
  src/services/user/docs/openapi.yaml
Labels: ready to merge

#2189 Hotfix/3/25.5.6 SC-8444
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user-group/services/course-copy-service.js
Labels: WIP

#2187 Feature/sc 6950 manage school kreis and official school number
  CHANGELOG.md
  src/services/school/hooks/index.js
  test/services/school/index.test.js
Labels: waiting for review

#2178 Hotfix/3/sc 8410 verify ldap timeout
  CHANGELOG.md
  src/services/ldap-config/service.js
  src/services/ldap/index.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/interface.js
  src/services/ldap/strategies/iserv-idm.js
  src/services/ldap/strategies/iserv.js
  src/services/ldap/strategies/univention.js
  test/services/ldap-config/service.integration.test.js
  test/services/ldap-config/service.unit.test.js
Labels: waiting for review

#2190 Feature/sc 8482 facades integration
  CHANGELOG.md
  src/components/course/index.js
  src/components/course/uc/courses.facade.js
  src/components/course/uc/deleteUserData.integration.test.js
  src/components/course/uc/deleteUserData.uc.js
  src/components/course/uc/deleteUserData.unit.test.js
  src/components/fileStorage/uc/applicationInternal/removePermissions.js
  src/components/helpdesk/index.js
  src/components/helpdesk/uc/helpdesk.facade.js
  src/components/helpdesk/uc/helpdesk.uc.js
  src/components/helpdesk/uc/helpdesk.unit.test.js
  src/components/helper/uc.helper.js
  src/components/index.js
  src/components/pseudonym/index.js
  src/components/pseudonym/uc/pseudonym.facade.js
  src/components/pseudonym/uc/pseudonym.uc.js
  src/components/pseudonym/uc/pseudonym.unit.test.js
  src/components/user-group/index.js
  src/components/user-group/uc/classes.facade.js
  src/components/user-group/uc/deleteUserData.uc.js
  src/components/user-group/uc/deleteUserData.unit.test.js
  src/components/user/repo/trashbin.repo.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
Labels: WIP, auto update

#2201 Hotfix 25.5.7 SC-8489
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/homework/hooks/index.js
  test/services/homework/index.test.js
Labels: ready to merge

#2202 Hotfix SC-8480
  CHANGELOG.md
  package-lock.json
  package.json
  src/errors/utils.js
Labels: WIP

#2204 Kubectls experiments dockerfile
  Dockerfile
  backup.js
  startup.sh
Labels: WIP

#2209 Kubectls experiments mongodb replicaset
  backup.js
  k8s/configmap.yaml
  k8s/deployment.yaml
  package.json
  startup.sh
Labels: WIP

#2210 Kubectls experiments redis
  .github/workflows/main.yml
  k8s/configmap.yaml
  k8s/deployment_redis.yaml
  k8s/service_redis.yaml
Labels: WIP

#2208 SC-8503 - Clicking on task in BRB and THR shows pencil page
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/homework/hooks/index.js
Labels: WIP

#2215 Kubectls experiments ssl
  .github/workflows/main.yml
  k8s/ingress.yaml
Labels: WIP

#2211 Hotfix/3/ SC-8506
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ltiTool/hooks/index.js
  src/services/videoconference/index.js
  src/services/videoconference/logic/constants.js
Labels: waiting for review

#2216 Hotfix SC-8499
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1611829684290-addUniquePseudonymIndex.js
  package-lock.json
  package.json
  src/services/pseudonym/hooks/index.js
  src/services/pseudonym/model.js
Labels: WIP

#2219 Hotfix SC-8499 Migration Order
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1610972727660-addUniquePseudonymIndex.js
  package-lock.json
  package.json
Labels: WIP

#2220 SC-8462 add logging for homework deletion
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/homework/hooks/index.js
Labels: WIP

#2221 Adding support for branches with special characters
  .github/workflows/main.yml
Labels: WIP

#2033 Feature/sc 7825/delete tasks
  CHANGELOG.md
  package-lock.json
  src/components/task/repo/db/index.js
  src/components/task/repo/task.repo.integration.test.js
  src/components/task/repo/task.repo.js
  src/components/task/uc/deleteUserData.uc.js
  src/components/task/uc/deleteUserData.uc.unit.test.js
  src/components/task/uc/task.facade.js
  src/errors/index.js
  test/services/helpers/services/homeworks.js
  test/services/helpers/services/submissions.js
  test/services/helpers/testObjects.js
Labels: auto update, ready to merge
