Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-07, with the labels that each got.

#2673 SC-9159 remove news v1
  .github/workflows/publish_pages.yml
  CHANGELOG.md
  TODO.md
  apps/server/doc/testing.md
  apps/server/src/constants.ts
  apps/server/src/core/error/filter/global-error.filter.ts
  apps/server/src/main.ts
  apps/server/src/modules/authorization/authorization.service.spec.ts
  apps/server/src/modules/authorization/authorization.service.ts
  apps/server/src/modules/authorization/feathers-auth.provider.ts
  apps/server/src/modules/database/index.ts
  apps/server/src/modules/database/mongo-database/index.ts
  apps/server/src/modules/database/mongo-database/mongo-database.module.ts
  apps/server/src/modules/database/mongo-database/mongo-shared-connection.ts
  apps/server/src/modules/database/mongo-database/mongo-shared-driver.ts
  apps/server/src/modules/news/controller/dto/create-news.params.ts
  apps/server/src/modules/news/controller/news.controller.ts
  apps/server/src/modules/news/controller/team-news.controller.ts
  apps/server/src/modules/news/entity/news.entity.ts
  apps/server/src/modules/news/entity/news.types.ts
  apps/server/src/modules/news/mapper/news.mapper.spec.ts
  apps/server/src/modules/news/mapper/news.mapper.ts
  apps/server/src/modules/news/news.module.ts
  apps/server/src/modules/news/repo/news-target-filter.ts
  apps/server/src/modules/news/repo/news.repo.integration.spec.ts
  apps/server/src/modules/news/repo/news.repo.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/repo/task.repo.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/controller/swagger.spec.ts
  apps/server/src/shared/domain/README.md
  apps/server/src/shared/domain/interface/find-options.ts
  apps/server/src/shared/domain/interface/index.ts
  apps/server/src/shared/domain/interface/pagination.interface.ts
  apps/server/src/shared/domain/interface/sorting.ts
  apps/server/src/shared/repo/base.repo.integration.spec.ts
  apps/server/src/shared/repo/base.repo.ts
  apps/server/test/modules/news/news.e2e-spec.ts
  backup/setup/migrations.json
  backup/setup/news.json
  migrations/1622622198664-news_add_target_schools.js
  src/services/news/constants.js
  src/services/news/docs.js
  src/services/news/docs/openapi.yaml
  src/services/news/hooks/index.js
  src/services/news/index.js
  src/services/news/model.js
  src/utils/apiValidation.js
  src/utils/sanitizeHtml.js
  test/services/news/hooks/news.hooks.test.js
  test/services/news/index.test.js
Labels: WIP

#2671 SC-9157 rabbitmq connection mail
  CHANGELOG.md
  apps/server/src/legacy/nest-app-holder.ts
  apps/server/src/main.ts
  apps/server/src/modules/mail/interfaces/mail.ts
  apps/server/src/modules/mail/mail.module.ts
  apps/server/src/modules/mail/mail.service.spec.ts
  apps/server/src/modules/mail/mail.service.ts
  apps/server/src/modules/mail/rabbitMqClient.ts
  apps/server/src/server.module.ts
  config/default.schema.json
  config/test.json
  package-lock.json
  package.json
  src/hooks/index.js
  src/services/helpers/service.js
Labels: WIP

#2753 update nestjs documentation
  .github/workflows/publish_pages.yml
  README.md
  apps/server/README.md
  package.json
Labels: WIP

#2754 Tw/update documentation
  README.md
Labels: WIP

#2762 SC-9194 fix nestjs test coverage
  apps/server/src/legacy/nest-app-holder.ts
  apps/server/src/modules/feathers/feathers-service.provider.spec.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/entity/file-task-info.entity.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/modules/user/entity/account.entity.ts
  apps/server/src/modules/user/user.facade.ts
  apps/server/src/shared/repo/base.repo.integration.spec.ts
  apps/server/src/shared/repo/base.repo.ts
Labels: WIP

#2758 fix nestjs test coverage
  apps/server/src/legacy/nest-app-holder.ts
  apps/server/src/modules/feathers/feathers-service.provider.spec.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/entity/file-task-info.entity.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/modules/user/entity/account.entity.ts
  apps/server/src/modules/user/user.facade.ts
  apps/server/src/shared/repo/base.repo.integration.spec.ts
  apps/server/src/shared/repo/base.repo.ts
Labels: WIP

#2761 SC-9157 improve config
  .github/workflows/test.yml
  CHANGELOG.md
  apps/server/src/modules/mail/mail.interface.ts
  apps/server/src/modules/mail/mail.module.spec.ts
  apps/server/src/modules/mail/mail.module.ts
  apps/server/src/modules/mail/mail.service.spec.ts
  apps/server/src/modules/mail/mail.service.ts
  apps/server/src/modules/mail/rabbitMqClient.ts
  apps/server/src/server.module.ts
Labels: WIP

#2764 SC-9195 inject nestjs mail service into feathers app
  .github/workflows/test.yml
  apps/server/src/legacy/nest-app-holder.ts
  apps/server/src/main.ts
  src/services/helpers/service.js
Labels: WIP

#2771 OPS-2574 - Removeing autodeployed branches for developers if branch deleted
  .github/workflows/clean.yml
  CHANGELOG.md
Labels: waiting for review

#2779 improved build process
  .dockerignore
  .github/workflows/build_push_service.yml
  .github/workflows/main.yml
  .github/workflows/tag.yml
  Dockerfile
Labels: waiting for review

#2778 SC-9197 - limiting jest workers to 2 workers
  .github/workflows/test.yml
  CHANGELOG.md
  package.json
Labels: waiting for review

#2786 SC-9292 Fix sending registration link mails
  CHANGELOG.md
  src/services/helpers/service.js
Labels: waiting for review

#2793 OPS-2579 - add init job for storage to the deployment
  CHANGELOG.md
  ansible/roles/schulcloud-server/tasks/main.yml
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  ansible/roles/schulcloud-server/templates/configmap_storage_init.yml.j2
  ansible/roles/schulcloud-server/templates/storage_init.yml.j2
Labels: waiting for review

#2765 SC-8887 - allow public access to consentVersion find service
  CHANGELOG.md
  src/services/consent/services/consentVersionService.js
Labels: ready to merge

#2799 Update require_changelog.yml
  .github/workflows/require_changelog.yml
Labels: WIP

#2798 use global env instead of matrix definitions
  .github/workflows/test.yml
Labels: WIP

#2800 Change default lernstore mode to edusharing
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  ansible/roles/schulcloud-server/templates/secret.yml.j2
  config/default.schema.json
  config/development.json
Labels: WIP

#2810 SC-9092 add missing S3 key encryption
  CHANGELOG.md
  migrations/1622209795280-add_S3_expiration.js
  package-lock.json
  package.json
Labels: waiting for review

#2808 SC-9190 add populated targets with name and id to news
  CHANGELOG.md
  apps/server/src/modules/news/controller/dto/news.response.ts
  apps/server/src/modules/news/controller/dto/target-info.response.ts
  apps/server/src/modules/news/entity/news.entity.ts
  apps/server/src/modules/news/entity/news.types.ts
  apps/server/src/modules/news/mapper/news.mapper.spec.ts
  apps/server/src/modules/news/mapper/news.mapper.ts
  apps/server/src/modules/news/mapper/target-info.mapper.ts
  apps/server/src/modules/news/repo/news.repo.ts
Labels: WIP

#2815 Move S3 expiration migration to the end
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1627022636538-add_S3_expiration.js
  package-lock.json
  package.json
Labels: waiting for review

#2809 Feature/sc 9213 coursegroup tasks
  CHANGELOG.md
  apps/server/src/modules/task/entity/course-group-info.entity.ts
  apps/server/src/modules/task/entity/course-task-info.entity.ts
  apps/server/src/modules/task/entity/index.ts
  apps/server/src/modules/task/entity/submission.entity.ts
  apps/server/src/modules/task/repo/submission.repo.integration.spec.ts
  apps/server/src/modules/task/repo/submission.repo.ts
  apps/server/src/modules/task/repo/task.repo.integration.spec.ts
  apps/server/src/modules/task/repo/task.repo.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/server.module.ts
Labels: WIP

#2816 execute e2e tests on pr without wip label only
  .github/workflows/test_e2e.yml
Labels: WIP, run tests

#2828 SC-9211 enable maildrop with mailcatcher (see docker-compose)
  CHANGELOG.md
Labels: WIP, run tests

#2763 SC-9150 - add script to change school year for (except BRB)
  CHANGELOG.md
  scripts/startNewSchoolYear.js
Labels: waiting for review

#2825 SC-9053 prevent repeated user requests
  CHANGELOG.md
  src/services/user/hooks/userService.js
  src/services/user/services/MailRegistrationLink.js
Labels: waiting for review

#2830 updated seed data for school year 2021/22
  backup/setup/classes.json
  backup/setup/schools.json
Labels: run tests

#2829 SC-9212 fix changing classes via CSV import
  CHANGELOG.md
  src/services/sync/strategies/CSVSyncer.js
Labels: run tests, waiting for review

#2842 SC-9177 allow superheros to delete admins
  CHANGELOG.md
  src/components/user/docs/openapi.yaml
  src/components/user/services/index.js
  src/components/user/services/user.service.v2.integration.test.js
Labels: run tests, waiting for review

#2846 Tf/tasksuc extract dependencies
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/domain/task-submission-metadata.service.spec.ts
  apps/server/src/modules/task/domain/task-submission-metadata.service.ts
  apps/server/src/modules/task/task.module.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
Labels: run tests, waiting for review
