Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-04, with the labels that each got.

#2416 SC-8691 ldap: ensure client is unlocked in case of error
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap/index.js
  src/services/ldap/lockingQueue.js
  src/services/ldap/lockingQueue.unit.test.js
Labels: ready to merge

#2436 up missing migrations
  backup/setup/migrations.json
Labels: ready to merge

#2438 Hotfix/1/sc 8779 partial sync 2
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap/strategies/deltaSyncUtils.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/iserv-idm.js
  src/services/ldap/strategies/iserv.js
  src/services/school/model.js
  src/services/sync/strategies/LDAPSchoolSyncer.js
  test/services/ldap/strategies/deltaSyncUtils.test.js
  test/services/ldap/strategies/iserv-idm.test.js
Labels: waiting for review

#2446 SC-8908 fix ldap lock
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap/index.js
Labels: ready to merge

#2447 SC-8873: Add prioritization for Matrix messenger tasks
  CHANGELOG.md
  src/services/messengerSync/consumer.js
  src/services/messengerSync/producer.js
  src/utils/rabbitmq.js
Labels: WIP

#2449 SC-8910 - add external check to remove method
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: WIP

#2441 SC-8748 bump feathers-mongoose from 6.3.0 to 8.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/account/services/accountApiService.js
  src/services/account/services/accountModelService.js
  src/services/activation/services/ActivationModelService.js
  src/services/base64Files/index.js
  src/services/consent/index.js
  src/services/content/index.js
  src/services/datasources/services/datasourceRuns.js
  src/services/datasources/services/datasources.js
  src/services/federalState/index.js
  src/services/fileStorage/model-service.js
  src/services/helpdesk/index.js
  src/services/homework/hooks/submissions.js
  src/services/homework/model-service.js
  src/services/lesson/index.js
  src/services/link/index.js
  src/services/ltiTool/index.js
  src/services/messengerSync/services/schoolSyncService.js
  src/services/news/index.js
  src/services/pseudonym/index.js
  src/services/releases/index.js
  src/services/role/index.js
  src/services/school/index.js
  src/services/serviceTemplate/services/modelService.js
  src/services/storageProvider/index.js
  src/services/system/index.js
  src/services/teams/index.js
  src/services/teams/services/admin.js
  src/services/user-group/index.js
  src/services/user-group/services/classModelService.js
  src/services/user-group/services/classes.js
  src/services/user-group/services/courseGroupModelService.js
  src/services/user-group/services/courseGroups.js
  src/services/user-group/services/courseModelService.js
  src/services/user-group/services/courseScopeLists.js
  src/services/user-group/services/courses.js
  src/services/user/index.js
  src/services/user/services/UsersModelService.js
  src/services/user/services/userService.js
  src/services/user/utils/aggregations.js
  src/services/webuntis/services/webuntisMetadata.js
  src/utils/pagination.js
  test/services/teams/helper/helper.hook.js
  test/services/user-group/services/classes.test.js
  test/services/user/services/userService.test.js
Labels: WIP

#2448 SC-8909: fixed device ids
  CHANGELOG.md
  src/services/messengerSync/services/messengerTokenService.js
  test/services/messengerSync/services/messengerTokenService.test.js
Labels: ready to merge

#2466 Hotfix/1/sc 8917 ldap school missing
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap-config/service.js
  src/services/ldap/strategies/deltaSyncUtils.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/iserv-idm.js
  src/services/ldap/strategies/iserv.js
  test/services/ldap/strategies/deltaSyncUtils.test.js
Labels: waiting for review

#2470 SC-8934 - no more autosync for the migrations for the mongodb
  CHANGELOG.md
  package-lock.json
  package.json
  startup.sh
Labels: auto update, auto_merged, ready to merge

#2474 Hotfix/1/SC-8909 fixed device ids
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/messengerSync/services/messengerTokenService.js
  test/services/messengerSync/services/messengerTokenService.test.js
Labels: ready to merge

#2476 SC-8890 hotfix2 revert feathers-mongoose update from 3fecd039ff930844822f92a2b168c89af0bc3386
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/account/services/accountApiService.js
  src/services/account/services/accountModelService.js
  src/services/activation/services/ActivationModelService.js
  src/services/base64Files/index.js
  src/services/consent/index.js
  src/services/content/index.js
  src/services/datasources/services/datasourceRuns.js
  src/services/datasources/services/datasources.js
  src/services/federalState/index.js
  src/services/fileStorage/model-service.js
  src/services/helpdesk/index.js
  src/services/homework/hooks/submissions.js
  src/services/homework/model-service.js
  src/services/lesson/index.js
  src/services/link/index.js
  src/services/ltiTool/index.js
  src/services/messengerSync/services/schoolSyncService.js
  src/services/news/index.js
  src/services/pseudonym/index.js
  src/services/releases/index.js
  src/services/role/index.js
  src/services/school/index.js
  src/services/serviceTemplate/services/modelService.js
  src/services/storageProvider/index.js
  src/services/system/index.js
  src/services/teams/index.js
  src/services/teams/services/admin.js
  src/services/user-group/index.js
  src/services/user-group/services/classModelService.js
  src/services/user-group/services/classes.js
  src/services/user-group/services/courseGroupModelService.js
  src/services/user-group/services/courseGroups.js
  src/services/user-group/services/courseModelService.js
  src/services/user-group/services/courseScopeLists.js
  src/services/user-group/services/courses.js
  src/services/user/index.js
  src/services/user/services/UsersModelService.js
  src/services/user/services/userService.js
  src/services/user/utils/aggregations.js
  src/services/webuntis/services/webuntisMetadata.js
  src/utils/pagination.js
  test/services/teams/helper/helper.hook.js
  test/services/user-group/services/classes.test.js
  test/services/user/services/userService.test.js
Labels: waiting for review

#2483 update eslintrc to new eslint version
  .eslintrc.js
Labels: WIP

#2485 Master
  .gitignore
  .travis.yml
  deploy.sh
  travis_rsa.enc
Labels: WIP

#2472 SC-8873 Fix addUser prioritization for full school Matrix messenger sync
  CHANGELOG.md
  src/services/messengerSync/producer.js
  test/services/messengerSync/consumer.test.js
Labels: ready to merge

#2464 Hotfix/1/sc 8919 ldap rabbit poc repo
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/index.js
  src/services/sync/repo/class.repo.js
  src/services/sync/repo/index.js
  src/services/sync/repo/school.repo.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/LDAPSyncerConsumer.js
  test/services/helpers/services/classes.js
  test/services/helpers/services/roles.js
  test/services/sync/repo/class.repo.integration.test.js
  test/services/sync/repo/school.repo.integration.test.js
  test/services/sync/repo/user.repo.integration.test.js
  test/services/sync/strategies/LDAPSchoolSyncer.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.test.js
Labels: auto update, do not merge

#2461 Release/26.1.0
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1617011449972-set_search_index.js
  package-lock.json
  package.json
  src/services/user/docs/adminusers.openapi.yaml
  src/services/user/model/user.schema.js
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: auto update

#2480 Add resource measuring for tests.
  CHANGELOG.md
  config/default.schema.json
  config/development.json
  package-lock.json
  package.json
  src/utils/database.js
  test/routes/routes.js
  test/routes/routes.metrics.js
  test/routes/serviceLimits.js
  test/routes/servicePerformance.js
  test/services/helpers/getAllRoutes.js
  test/services/helpers/mongooseEventListener.js
  test/services/helpers/testObjects.js
Labels: waiting for review

#2498 Poc sc 9005
  .eslintrc.js
  src/errors/applicationErrors.js
  src/services/sync/strategies/LDAPSyncerConsumer.js
Labels: WIP

#2495 Feature/sc 9005 ldap rabbit poc error handling
  .eslintrc.js
  config/default.schema.json
  config/development.json
  src/errors/applicationErrors.js
  src/logger/syncLogger.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSyncerConsumer.js
  test/errors/applicationErrors.test.js
  test/services/sync/repo/class.repo.integration.test.js
  test/services/sync/repo/school.repo.integration.test.js
  test/services/sync/repo/user.repo.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.test.js
Labels: WIP
