Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-11, with the labels that each got.

#3151 BC-402 - change e2e test include to reusable workflows
  .github/workflows/push.yml
  CHANGELOG.md
Labels: waiting for review

#3148 BC-532 add indexes to lesson, course and task
  CHANGELOG.md
  apps/server/src/modules/task/uc/task.authorization.service.ts
  apps/server/src/repositories/learnroom/course.repo.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/domain/entity/lesson.entity.ts
  apps/server/src/shared/domain/entity/task.entity.ts
Labels: waiting for review, run tests

#3124 BC-543 - move logic in task
  CHANGELOG.md
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/shared/domain/entity/course.entity.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/domain/entity/submission.entity.spec.ts
  apps/server/src/shared/domain/entity/submission.entity.ts
  apps/server/src/shared/domain/entity/task.entity.spec.ts
  apps/server/src/shared/domain/entity/task.entity.ts
  apps/server/src/shared/domain/index.ts
  apps/server/src/shared/domain/vo/index.ts
  apps/server/src/shared/domain/vo/task-with-status.vo.ts
  apps/server/src/shared/testing/factory/submission.factory.ts
  apps/server/test/modules/task/task.e2e-spec.ts
Labels: waiting for review, run tests

#3153 Feature/bc 451 repos
  CHANGELOG.md
  apps/server/src/modules/files/job/delete-files.console.spec.ts
  package-lock.json
Labels: waiting for review

#3155 26.25.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: WIP

#3156 fix flaky file repository test
  CHANGELOG.md
  src/components/fileStorage/repo/files.repo.js
Labels: waiting for review, run tests, run unstable tests

#3154 BC-451 repos moved to shared: files, news
  CHANGELOG.md
  apps/server/doc/cross-cutting-concerns.md
  apps/server/src/core/logger/index.ts
  apps/server/src/modules/files/files.module.ts
  apps/server/src/modules/files/job/delete-files.console.spec.ts
  apps/server/src/modules/files/job/delete-files.console.ts
  apps/server/src/modules/files/uc/delete-files.uc.spec.ts
  apps/server/src/modules/files/uc/delete-files.uc.ts
  apps/server/src/modules/news/controller/news.controller.spec.ts
  apps/server/src/modules/news/news.module.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/task/repo/task-scope.ts
  apps/server/src/repositories/learnroom/course.repo.ts
  apps/server/src/shared/repo/files/files.repo.spec.ts
  apps/server/src/shared/repo/files/files.repo.ts
  apps/server/src/shared/repo/files/index.ts
  apps/server/src/shared/repo/files/storageprovider.repo.spec.ts
  apps/server/src/shared/repo/files/storageprovider.repo.ts
  apps/server/src/shared/repo/index.ts
  apps/server/src/shared/repo/news/index.ts
  apps/server/src/shared/repo/news/news-scope.spec.ts
  apps/server/src/shared/repo/news/news-scope.ts
  apps/server/src/shared/repo/news/news-target-filter.ts
  apps/server/src/shared/repo/news/news.repo.integration.spec.ts
  apps/server/src/shared/repo/news/news.repo.ts
Labels: waiting for review

#3132 BC-489 ldap federal state
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1634814982190-ldap_federal_state.js
  src/services/ldap-config/service.js
  src/services/school/hooks/index.js
  src/services/system/model.js
  test/services/ldap-config/service.unit.test.js
  test/services/school/index.test.js
Labels: ready to merge, run unstable tests

#3158 BC-605 sort references within groups alphabetically
  CHANGELOG.md
  apps/server/src/repositories/learnroom/dashboard.repo.integration.spec.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboardElement.entity.spec.ts
  package-lock.json
Labels: waiting for review

#3141 Teacher can add students from other schools to own team
  CHANGELOG.md
  src/services/teams/index.js
  test/services/teams/index.test.js
Labels: waiting for review, run tests

#3160 BC-451 move user and role repo to shared
  CHANGELOG.md
  apps/server/src/modules/user/repo/account.repo.ts
  apps/server/src/modules/user/repo/index.ts
  apps/server/src/modules/user/uc/role.uc.spec.ts
  apps/server/src/modules/user/uc/role.uc.ts
  apps/server/src/modules/user/uc/user.uc.spec.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.module.ts
  apps/server/src/shared/domain/entity/all-entities.ts
  apps/server/src/shared/domain/entity/dashboard.model.entity.ts
  apps/server/src/shared/domain/entity/index.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.integration.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.ts
  apps/server/src/shared/repo/index.ts
  apps/server/src/shared/repo/role/index.ts
  apps/server/src/shared/repo/role/role.repo.integration.spec.ts
  apps/server/src/shared/repo/role/role.repo.ts
  apps/server/src/shared/repo/user/index.ts
  apps/server/src/shared/repo/user/user.repo.integration.spec.ts
  apps/server/src/shared/repo/user/user.repo.ts
Labels: waiting for review

#3164 BC-599 - fix bug on email
  CHANGELOG.md
  src/services/helpers/service.js
Labels: ready to merge, run unstable tests

#3165 BC-489 fix error on migration
  CHANGELOG.md
  migrations/1634814982190-ldap_federal_state.js
Labels: ready to merge

#3166 fixed autodeployment storageprovider initialization race condition
  CHANGELOG.md
  ansible/roles/schulcloud-server/tasks/main.yml
  ansible/roles/schulcloud-server/templates/configmap_file_init_db.yml.j2
  ansible/roles/schulcloud-server/templates/configmap_storage_init.yml.j2
  ansible/roles/schulcloud-server/templates/storage_init.yml.j2
Labels: waiting for review

#3152 BC-369 - fix wrong behavior by the general LDAP Strategy if an attribute is not set
  CHANGELOG.md
  src/helper/stringHelper.js
  src/services/ldap/strategies/general.js
  test/helper/stringHelper.test.js
Labels: waiting for review, run unstable tests

#3173 BC-685 - fix more usage of class attribute
  CHANGELOG.md
  src/services/ldap/index.js
Labels: ready to merge

#3169 BC-589 - BC-652 - Change auto deployment to a reusable workflow
  .github/workflows/clean.yml
  .github/workflows/push.yml
  CHANGELOG.md
Labels: waiting for review

#3185 BC-340 personal course dashboards
  CHANGELOG.md
  apps/server/src/modules/learnroom/controller/dashboard.controller.spec.ts
  apps/server/src/modules/learnroom/controller/dashboard.controller.ts
  apps/server/src/modules/learnroom/mapper/dashboard.mapper.spec.ts
  apps/server/src/modules/learnroom/uc/dashboard.uc.spec.ts
  apps/server/src/modules/learnroom/uc/dashboard.uc.ts
  apps/server/src/shared/domain/entity/dashboard.entity.spec.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboard.model.entity.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.integration.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.ts
  apps/server/test/modules/learnroom/dashboard.e2e-spec.ts
Labels: waiting for review

#3163 BC-488
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap_file_init_db.yml.j2
  src/services/sync/strategies/LDAPSyncer.js
  test/services/sync/strategies/LDAPSyncerProducer.test.js
Labels: waiting for review, run unstable tests

#3190 BC-589 - Fix mistaken for branch delete event.
  .github/workflows/clean.yml
  CHANGELOG.md
Labels: waiting for review

#3195 version 26.17.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#3200 Bc 723 get courses
  apps/server/src/modules/learnroom/controller/course.controller.spec.ts
  apps/server/src/modules/learnroom/controller/course.controller.ts
  apps/server/src/modules/learnroom/controller/dto/courseMetadata.response.ts
  apps/server/src/modules/learnroom/controller/dto/index.ts
  apps/server/src/modules/learnroom/learnroom.module.ts
  apps/server/src/modules/learnroom/mapper/course.mapper.ts
  apps/server/src/modules/learnroom/uc/course.uc.spec.ts
  apps/server/src/modules/learnroom/uc/course.uc.ts
  apps/server/src/shared/domain/entity/course.entity.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/repo/course/course.repo.integration.spec.ts
  apps/server/src/shared/repo/course/course.repo.ts
  apps/server/test/modules/learnroom/course.e2e-spec.ts
Labels: waiting for review

#3207 BC-724 fixed OpenAPI spec for dashboard
  CHANGELOG.md
  apps/server/src/modules/learnroom/controller/dashboard.controller.ts
  config/default.schema.json
Labels: waiting for review

#3199 BC-730 add univention LDAP tests
  src/services/ldap/strategies/univention.js
  test/services/ldap/strategies/iserv-idm.test.js
  test/services/ldap/strategies/univention.test.js
Labels: waiting for review

#3210 version 26.18.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#3194 BC-596 enable strict property init with sample news/tasks
  CHANGELOG.md
  apps/server/doc/decisions.md
  apps/server/src/modules/learnroom/controller/dto/dashboard.response.ts
  apps/server/src/modules/learnroom/controller/dto/movePosition.params.ts
  apps/server/src/modules/learnroom/controller/dto/patchGroup.params.ts
  apps/server/src/modules/news/controller/dto/create-news.params.ts
  apps/server/src/modules/news/controller/dto/news.response.ts
  apps/server/src/modules/news/controller/dto/school-info.response.ts
  apps/server/src/modules/news/controller/dto/target-info.response.ts
  apps/server/src/modules/news/controller/dto/update-news.params.ts
  apps/server/src/modules/news/controller/dto/user-info.response.ts
  apps/server/src/modules/news/mapper/news.mapper.spec.ts
  apps/server/src/modules/news/mapper/news.mapper.ts
  apps/server/src/modules/news/mapper/school-info.mapper.ts
  apps/server/src/modules/news/mapper/target-info.mapper.ts
  apps/server/src/modules/news/mapper/user-info.mapper.ts
  apps/server/src/modules/rocketchat/rocket-chat.service.ts
  apps/server/src/modules/task/controller/dto/task.response.ts
  apps/server/src/modules/task/mapper/task.mapper.spec.ts
  apps/server/src/modules/task/mapper/task.mapper.ts
  apps/server/src/modules/user/controller/dto/ResolvedUser.dto.ts
  apps/server/src/shared/controller/transformer/decode-html-entities.transformer.spec.ts
  apps/server/src/shared/controller/transformer/string-to-boolean.transformer.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboard.model.entity.ts
  apps/server/src/shared/domain/entity/file.entity.ts
  apps/server/src/shared/domain/entity/news.entity.ts
  apps/server/src/shared/repo/role/role.repo.ts
  tsconfig.json
Labels: waiting for review

#3176 BC-688 disable allowJS to improve autocompletion
  CHANGELOG.md
  apps/server/tsconfig.app.json
  tsconfig.json
Labels: waiting for review

#3211 BC-740 change ansible vars for docker image and tag
  CHANGELOG.md
  ansible/group_vars/all/schulcloud-server.yml
  ansible/roles/schulcloud-management/templates/management-deployment.yml.j2
  ansible/roles/schulcloud-server/templates/api-delete-s3-files-cronjob.yml.j2
  ansible/roles/schulcloud-server/templates/api-worker-deployment.yml.j2
  ansible/roles/schulcloud-server/templates/deployment.yml.j2
Labels: ready to merge

#3181 feature/BC-609 finished tasks
  CHANGELOG.md
  apps/server/src/modules/learnroom/controller/course.controller.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/mapper/task.mapper.spec.ts
  apps/server/src/modules/task/uc/task.authorization.service.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/shared/domain/entity/course.entity.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/domain/entity/task.entity.spec.ts
  apps/server/src/shared/domain/entity/task.entity.ts
  apps/server/src/shared/repo/course/course.repo.integration.spec.ts
  apps/server/src/shared/repo/course/course.repo.ts
  apps/server/src/shared/repo/coursegroup/coursegroup.repo.integration.spec.ts
  apps/server/src/shared/repo/lesson/lesson.repo.ts
  apps/server/src/shared/repo/submission/submission.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task-scope.ts
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task.repo.ts
  apps/server/src/shared/testing/factory/base.factory.ts
  apps/server/src/shared/testing/factory/course.factory.ts
  apps/server/src/shared/testing/factory/lesson.factory.ts
  apps/server/src/shared/testing/factory/submission.factory.ts
  apps/server/src/shared/testing/factory/task.factory.ts
  apps/server/test/modules/task/task.e2e-spec.ts
  apps/server/test/modules/task/taskFinished.e2e-spec.ts
Labels: waiting for review

#3218 version 26.19.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#3202 BC-701 - bumping some packages
  CHANGELOG.md
  package-lock.json
  package.json
Labels: run unstable tests
