Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-03, with the labels that each got.

#2045 SC-7868 delete personal file connections
  .travis.yml
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/components/fileStorage/repo/db/index.js
  src/components/fileStorage/repo/fileStorageProvider.repo.integration.test.js
  src/components/fileStorage/repo/fileStorageProvider.repo.js
  src/components/fileStorage/repo/files.repo.integration.test.js
  src/components/fileStorage/repo/files.repo.js
  src/components/fileStorage/repo/index.js
  src/components/fileStorage/repo/strategies/index.js
  src/components/fileStorage/uc/applicationInternal/removePermissions.js
  src/components/fileStorage/uc/deleteUserData.uc.js
  src/components/fileStorage/uc/deleteUserData.uc.unit.test.js
  src/components/fileStorage/uc/fileStorage.facade.integration.test.js
  src/components/school/repo/index.js
  src/components/school/repo/school.repo.js
  src/components/school/uc/school.facade.js
  src/components/school/uc/school.uc.js
  src/components/user/uc/users.facade.js
  src/components/user/uc/users.uc.js
  src/services/ldap/index.js
Labels: ready to merge, waiting for review

#2329 switch sort priority
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
Labels: WIP

#2355 Hotfix/1/sc 8770
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/firstLogin.js
  test/services/user/firstLogin.integration.test.js
Labels: waiting for review

#2335 SC-5202 - refactors a bit and adds a cople of tests
  CHANGELOG.md
  test/services/homework/index.test.js
Labels: ready to merge

#2358 Hotfix/sc 5202
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/homework/hooks/index.js
  test/services/homework/index.test.js
Labels: do not merge, waiting for review

#2375 Release/25.6.13
  CHANGELOG.md
  migrations/1615887987747-update-nexboard-urls.js
  package-lock.json
  package.json
Labels: WIP

#2395 SC-7868 skip filestorage integration tests if not setup
  CHANGELOG.md
  src/components/fileStorage/repo/fileStorageProvider.repo.integration.test.js
Labels: ready to merge

#2400 Hotfix SC-8829
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/rocketChat/services/rocketChatLogin.js
Labels: ready to merge

#2414 SC-8836 teachers can add classes from other teachers to their courses
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user-group/hooks/classes.js
  src/services/user-group/services/classes.js
  test/services/user-group/hooks/classes.test.js
Labels: WIP

#2419 Bugfix/sc 8732 search improvemnts
  CHANGELOG.md
  migrations/1617011449972-set_search_index.js
  src/services/user/model/user.schema.js
  src/services/user/services/AdminUsers.js
Labels: WIP
