Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-09, with the labels that each got.

#2939 BC-38 - BC-124 - Add ansible files for Bosscloud (default)
  CHANGELOG.md
  ansible/group_vars/default/schulcloud-server.yml
Labels: waiting for review, run tests

#2927 BC-106 - end maintenance for LDAP schools
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/endLdapSchoolYear.js
Labels: run tests

#2956 BC-187 secure systems
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/school/hooks/index.js
  src/services/system/hooks/index.js
  src/services/system/hooks/verifyPayload.js
  test/services/school/index.test.js
  test/services/system/index.test.js
Labels: ready to merge, run tests

#2946 adding missing attribute during school creation
  CHANGELOG.md
  src/services/school/hooks/index.js
  test/services/school/setDefaultStudentListPermission.integration.test.js
  test/services/user-group/hooks/classes.test.js
Labels: waiting for review, run tests

#2923 BC-120, BC-77 - add feature flag for S3 CORS
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  config/default.schema.json
  config/development.json
  config/test.json
  package-lock.json
  package.json
  src/services/fileStorage/strategies/awsS3.js
Labels: waiting for review, run tests

#2959 Feature/bc 233 remove ldapidentifier on systems remove
  CHANGELOG.md
  src/services/system/hooks/index.js
  test/services/helpers/services/schools.js
  test/services/system/index.test.js
Labels: ready to merge, run tests

#2958 Feature/bc 232 prevent schoolyear change
  CHANGELOG.md
  backup/setup/migrations.json
  backup/setup/roles.json
  migrations/1630920140403-add-years-edit-to-superhero.js
  src/services/school/hooks/years.hooks.js
  src/services/school/index.js
  test/services/helpers/testObjects.js
  test/services/school/years.service.integration.test.js
Labels: waiting for review, run tests

#2960 fixed changelog
  CHANGELOG.md
Labels: ready to merge, run tests

#2976 BC-267 skip whitelist-check for api requests on /wopi
  CHANGELOG.md
  apps/server/src/modules/authentication/strategy/jwt-validation.adapter.ts
  package-lock.json
  package.json
  src/app.hooks.js
  src/services/authentication/logic/whitelist.js
Labels: waiting for review, run tests

#2967 BC-262 remove S3 lifecycle code
  CHANGELOG.md
  config/default.schema.json
  src/services/fileStorage/strategies/awsS3.js
  test/services/fileStorage/aws/s3.mock.js
Labels: waiting for review, run tests

#2988 BC-279 add console
  CHANGELOG.md
  apps/server/README.md
  apps/server/src/console/console-writer/console-writer.service.spec.ts
  apps/server/src/console/console-writer/console-writer.service.ts
  apps/server/src/console/console.ts
  apps/server/src/console/server-console.module.ts
  apps/server/src/console/server.console.spec.ts
  apps/server/src/console/server.console.ts
  apps/server/test/console/server-console.e2e-spec.ts
  package-lock.json
  package.json
Labels: waiting for review, run tests

#2957 Feature/bc 179 refactor tasks
  CHANGELOG.md
  apps/server/src/entities/learnroom/course.entity.spec.ts
  apps/server/src/entities/learnroom/course.entity.ts
  apps/server/src/entities/learnroom/testHelper.ts
  apps/server/src/modules/database/mongo-database/index.ts
  apps/server/src/modules/database/mongo-database/mongo-database.module.ts
  apps/server/src/modules/database/mongo-database/mongo-shared-connection.ts
  apps/server/src/modules/database/mongo-database/mongo-shared-driver.ts
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/domain/TaskDomainService.spec.ts
  apps/server/src/modules/task/domain/TaskDomainService.ts
  apps/server/src/modules/task/entity/lesson-task-info.entity.ts
  apps/server/src/modules/task/entity/submission.entity.spec.ts
  apps/server/src/modules/task/entity/submission.entity.ts
  apps/server/src/modules/task/entity/task-with-status.vo.ts
  apps/server/src/modules/task/entity/task.entity.ts
  apps/server/src/modules/task/mapper/task.mapper.spec.ts
  apps/server/src/modules/task/mapper/task.mapper.ts
  apps/server/src/modules/task/repo/submission.repo.integration.spec.ts
  apps/server/src/modules/task/repo/task-scope.ts
  apps/server/src/modules/task/repo/task.repo.integration.spec.ts
  apps/server/src/modules/task/repo/task.repo.ts
  apps/server/src/modules/task/task.module.ts
  apps/server/src/modules/task/uc/task.authorization.service.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/modules/task/utils/TestHelper.ts
  apps/server/src/repositories/learnroom/course.repo.integration.spec.ts
  apps/server/src/repositories/learnroom/course.repo.ts
  apps/server/src/repositories/learnroom/coursegroup.repo.integration.spec.ts
  apps/server/src/repositories/learnroom/coursegroup.repo.ts
  apps/server/src/shared/repo/scope.spec.ts
  apps/server/test/modules/task/task.e2e-spec.ts
Labels: waiting for review, run tests

#2983 BC-164 - synch JWT from server and SHD
  CHANGELOG.md
  src/services/account/services/SupportJWTService.js
  src/services/authentication/hooks/index.js
  src/services/authentication/index.js
  src/services/authentication/logic/whitelist.js
  test/services/account/services/SupportJWTService.test.js
  test/services/authentication/authentication.test.js
Labels: auto_merged, auto update, run tests

#2994 bc-280 enabeling edusharing
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  ansible/roles/schulcloud-server/templates/secret.yml.j2
Labels: waiting for review, run tests

#2982 BC-239 - fix date parsing for students birth date
  CHANGELOG.md
  src/services/user/firstLogin.js
  test/services/user/firstLogin.test.js
Labels: waiting for review, run tests

#2999 BC-294 update mongoose
  package-lock.json
  package.json
Labels: waiting for review, run tests

#2962 BC-121 add bucket to file documents
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1630928992986-addBucketToFiles.js
  src/services/fileStorage/model.js
  src/services/fileStorage/proxy-service.js
  src/services/fileStorage/strategies/awsS3.js
  src/services/fileStorage/strategies/interface.js
  test/services/fileStorage/fixtures.js
  test/services/fileStorage/index.test.js
  test/services/helpers/services/files.js
  test/services/wopi/index.test.js
Labels: waiting for review, run tests

#3000 BC-68 - fix e2e server manifest error
  .github/workflows/build_push_service.yml
  .github/workflows/push.yml
  .github/workflows/test_e2e_pull_request.yml
  .github/workflows/test_e2e_push_main.yml
  CHANGELOG.md
Labels: waiting for review

#2971 BC-213 rewrite file deletion with deletion marker
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/fileStorage/repo/files.repo.integration.test.js
  src/components/fileStorage/repo/files.repo.js
  src/components/fileStorage/uc/deleteUserData.uc.js
  src/services/fileStorage/model.js
  src/services/fileStorage/proxy-service.js
  test/services/fileStorage/index.test.js
  test/services/helpers/services/files.js
Labels: waiting for review, run tests

#3018 Feature/bc 318 persist dashboard
  CHANGELOG.md
  apps/server/src/entities/learnroom/course.entity.ts
  apps/server/src/entities/learnroom/dashboard.entity.spec.ts
  apps/server/src/entities/learnroom/dashboard.entity.ts
  apps/server/src/modules/lernroom/controller/dashboard.controller.spec.ts
  apps/server/src/modules/lernroom/mapper/dashboard.mapper.spec.ts
  apps/server/src/modules/lernroom/usecase/dashboard.uc.spec.ts
  apps/server/src/repositories/learnroom/dashboard.model.entity.ts
  apps/server/src/repositories/learnroom/dashboard.model.mapper.spec.ts
  apps/server/src/repositories/learnroom/dashboard.model.mapper.ts
  apps/server/src/repositories/learnroom/dashboard.repo.spec.ts
  apps/server/src/repositories/learnroom/dashboard.repo.ts
  apps/server/src/server.module.ts
  apps/server/test/modules/lernrooms/dashboard.e2e-spec.ts
  backup/setup/dashboard-grid-element-model.json
  backup/setup/dashboard-model-entity.json
  package-lock.json
Labels: waiting for review, run tests

#2992 BC-274 - migrate course colors
  CHANGELOG.md
  backup/setup/courses.json
  backup/setup/migrations.json
  backup/setup/teams.json
  migrations/1631699471740-adjust-course-colors.js
Labels: ready to merge, run tests

#3026 Release/26.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: WIP

#3032 BC-331 - BC-352 - rename ansible variables for OnePassword
  CHANGELOG.md
  ansible/roles/schulcloud-server/tasks/main.yml
  ansible/roles/schulcloud-server/templates/onepassword.yml.j2
Labels: waiting for review

#3033 Hotfix/bc 365 fix pagination
  CHANGELOG.md
  apps/server/src/modules/task/repo/task.repo.ts
  package-lock.json
  package.json
Labels: waiting for review, run tests

#3035 Hotfix/26.11.2
  CHANGELOG.md
  migrations/1630928992986-addBucketToFiles.js
  package-lock.json
  package.json
  src/services/fileStorage/model.js
Labels: ready to merge
