Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-05, with the labels that each got.

#2500 Resort code for ldap consumer actions in a way of strategy pattern
  src/errors/applicationErrors.js
  src/errors/index.js
  src/logger/syncLogger.js
  src/services/sync/repo/class.repo.js
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/LDAPSyncerConsumer.js
  src/services/sync/strategies/consumerActions/BaseConsumerAction.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  src/services/sync/strategies/consumerActions/SchoolAction.js
  src/services/sync/strategies/consumerActions/UserAction.js
  src/services/sync/strategies/consumerActions/index.js
  src/services/sync/utils/index.js
  src/services/sync/utils/index.test..js
  test/services/sync/repo/class.repo.integration.test.js
  test/services/sync/repo/school.repo.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.test.js
  test/services/sync/strategies/consumerActions/ BaseConsumerAction.test.js
  test/services/sync/strategies/consumerActions/ClassAction.test.js
  test/services/sync/strategies/consumerActions/SchoolAction.test.js
  test/services/sync/strategies/consumerActions/UserAction.test.js
Labels: waiting for review

#2506 SC-6950 - changes validation for officialSchoolNumber
  CHANGELOG.md
  src/services/school/hooks/index.js
Labels: ready to merge

#2499 SC-8898 add missing function for sncy of students and teachers for a class.
  src/logger/syncLogger.js
  src/services/sync/repo/class.repo.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  test/services/sync/repo/class.repo.integration.test.js
  test/services/sync/repo/user.repo.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.test.js
  test/services/sync/strategies/consumerActions/ClassAction.test.js
  test/services/sync/strategies/consumerActions/SchoolAction.test.js
  test/services/sync/strategies/consumerActions/UserAction.test.js
Labels: WIP, auto update

#2041 Feature/ops 1559 enhance build pipeline
  .gitignore
  .travis.yml
  CHANGELOG.md
  build.sh
  package-lock.json
Labels: waiting for review

#2517 fix tests
  apps/server/src/modules/authentication/auth.module.ts
  apps/server/src/modules/authentication/auth.service.spec.ts
  apps/server/src/modules/authorization/authorization.service.spec.ts
  apps/server/src/modules/authorization/feathers-service.provider.spec.ts
  apps/server/src/modules/news/controller/news.controller.spec.ts
  apps/server/src/modules/news/news.service.spec.ts
  apps/server/src/modules/news/repo/news.repo.spec.ts
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/repo/task.repo.spec.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
Labels: WIP

#2509 SC-9031 add DB indices to improve LDAP sync performance
  backup/setup/migrations.json
  migrations/1620316360923-LDAPSyncIndices.js
  src/services/account/model.js
  src/services/school/model.js
  src/services/sync/repo/class.repo.js
  src/services/sync/repo/school.repo.js
  src/services/sync/repo/user.repo.js
  src/services/user-group/model.js
  src/services/user/model/user.schema.js
Labels: ready to merge

#2511 OPS-1499 - fixes condition in travis
  .travis.yml
  CHANGELOG.md
Labels: WIP

#2510 SC-9032: add tests for ldap sync producer
  .travis.yml
  config/default.schema.json
  config/test.json
  src/services/sync/repo/school.repo.js
  src/services/sync/strategies/LDAPSyncer.js
  src/services/sync/strategies/SyncMessageBuilder.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  src/services/sync/strategies/consumerActions/SchoolAction.js
  src/services/sync/strategies/consumerActions/UserAction.js
  test/services/sync/LdapSync.integration.test.js
  test/services/sync/repo/school.repo.integration.test.js
  test/services/sync/strategies/LDAPSyncerConsumer.integration.test.js
  test/services/sync/strategies/LDAPSyncerProducer.test.js
  test/services/sync/strategies/SyncMessageBuilder.test.js
Labels: auto update, waiting for review

#2533 OPS-1499 - fixes travis run on release branch
  .travis.yml
  CHANGELOG.md
Labels: WIP

#2539 Feature/sc 9004/nuxt env config
  CHANGELOG.md
  config/default.schema.json
  config/globals.js
  src/services/config/configService.js
  src/services/config/index.js
  src/services/config/publicAppConfigService.js
  src/services/school/logic/school.js
  test/services/config/hooks/services/publicAppConfigService.test.js
  test/services/school/school.logic.test.js
Labels: ready to merge

#2552 Feature/sc 9055 brandenburg sportinhalt
  CHANGELOG.md
  src/services/edusharing/services/EduSharingConnector.js
  test/services/edusharing/services/EduSharingConnector.test.js
Labels: WIP

#2542 SC-9085 delete registration pin for parent in deletion concept
  CHANGELOG.md
  src/components/user/uc/users.uc.integration.test.js
  src/components/user/uc/users.uc.js
Labels: ready to merge

#2553 SC-8440 - fixed open api validation for manual consent
  CHANGELOG.md
  src/services/user/docs/adminusers.openapi.yaml
Labels: WIP

#2555 SC-8933 - fix date format on first login
  CHANGELOG.md
  src/services/user/firstLogin.js
Labels: ready to merge
