Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-10, with the labels that each got.

#3041 BC-364 - run unstable e2e tests
  .github/workflows/test_unstable_e2e.yml
  CHANGELOG.md
Labels: run unstable tests

#3030 wait for mongo to spin up
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap_file_init_db.yml.j2
Labels: waiting for review

#3025 feature/BC-315 stabilized resolve user roles workflow by use roles from requested user
  CHANGELOG.md
  apps/server/src/modules/authentication/strategy/jwt.strategy.spec.ts
  apps/server/src/modules/authentication/strategy/jwt.strategy.ts
  apps/server/src/modules/user/uc/role.uc.spec.ts
  apps/server/src/modules/user/uc/role.uc.ts
  apps/server/src/modules/user/uc/user.uc.spec.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.facade.spec.ts
  apps/server/src/modules/user/user.facade.ts
Labels: waiting for review

#3045 BC-376 - fix set-value vulnerability
  CHANGELOG.md
  package-lock.json
  package.json
Labels: run unstable tests

#3042 check in firstLogin that students can only pass with existing birthdate
  CHANGELOG.md
  src/services/user/firstLogin.js
  test/services/user/firstLogin.integration.test.js
  test/services/user/firstLogin.test.js
Labels: waiting for review

#3049 BC-377 - fix axios vulnerabilities
  CHANGELOG.md
  package-lock.json
  package.json
Labels: run tests, run unstable tests

#3055 BC-422 run bucket to files migration in parallel
  CHANGELOG.md
  migrations/1630928992986-addBucketToFiles.js
  package-lock.json
  package.json
Labels: waiting for review, run tests
