Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-08, with the labels that each got.

#2854 SC-9233 - fix Lern-Store for THR not loading WLO content
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/edusharing/services/EduSharingConnector.js
Labels: WIP

#2863 extended pull request template with QA check
  .github/PULL_REQUEST_TEMPLATE.md
Labels: run tests

#2835 SC-9211 re-evaluate labels when labels have changed after commit
  .github/workflows/test_e2e.yml
Labels: ready to merge, run tests

#2877 marked amqp-mail-messages as persistent
  apps/server/src/modules/mail/mail.service.spec.ts
  apps/server/src/modules/mail/mail.service.ts
Labels: WIP

#2880 SC-9266 - fix formation of code
  apps/server/src/modules/mail/mail.service.spec.ts
  apps/server/src/modules/mail/mail.service.ts
Labels: waiting for review, run tests

#2884 SC-9269 avoid x.only using eslint
  .eslintrc.js
  CHANGELOG.md
  package-lock.json
  package.json
  test/services/news/index.test.js
Labels: ready to merge

#2797 SC-9192 Fix path mapping
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  ansible/roles/schulcloud-server/templates/api-worker-deployment.yml.j2
  ansible/roles/schulcloud-server/templates/deployment.yml.j2
  apps/server/src/constants.ts
  apps/server/src/main.ts
  apps/server/src/modules/authorization/authorization.service.spec.ts
  apps/server/src/modules/authorization/feathers-auth.provider.spec.ts
  apps/server/src/modules/feathers/feathers-service.provider.spec.ts
  apps/server/src/modules/feathers/feathers-service.provider.ts
  apps/server/src/shared/controller/swagger.spec.ts
  config/default.schema.json
  config/development.json
  package-lock.json
  package.json
  src/app.js
  src/index.js
  src/middleware/apiPath.js
  src/middleware/not-found-handler.js
  src/utils/sanitizeHtml.js
  test/app.test.js
  test/middleware/legacyForward.integration.test.js
  test/services/activation/services/activationService.test.js
  test/services/activation/services/eMailAddress/index.test.js
  test/services/helpers/service.test.js
  test/services/sync/strategies/CSVSyncer/CSVSyncer.integration.test.js
Labels: WIP, run tests

#2893 BC-64 - Fix e2e test branch selection bug
  .github/workflows/test_e2e.yml
Labels: waiting for review, run tests

#2837 Feature/initial learnroom module
  CHANGELOG.md
  apps/server/src/modules/authentication/decorator/auth.decorator.ts
  apps/server/src/modules/authentication/interface/jwt-payload.ts
  apps/server/src/modules/learnroom/controller/index.ts
  apps/server/src/modules/learnroom/entity/course.entity.spec.ts
  apps/server/src/modules/learnroom/entity/course.entity.ts
  apps/server/src/modules/learnroom/entity/coursegroup.entity.spec.ts
  apps/server/src/modules/learnroom/entity/coursegroup.entity.ts
  apps/server/src/modules/learnroom/entity/index.ts
  apps/server/src/modules/learnroom/index.ts
  apps/server/src/modules/learnroom/learnroom.facade.integration.spec.ts
  apps/server/src/modules/learnroom/learnroom.facade.ts
  apps/server/src/modules/learnroom/learnroom.module.ts
  apps/server/src/modules/learnroom/repo/course.repo.integration.spec.ts
  apps/server/src/modules/learnroom/repo/course.repo.ts
  apps/server/src/modules/learnroom/repo/coursegroup.repo.integration.spec.ts
  apps/server/src/modules/learnroom/repo/coursegroup.repo.ts
  apps/server/src/modules/learnroom/repo/index.ts
  apps/server/src/modules/learnroom/uc/course.uc.spec.ts
  apps/server/src/modules/learnroom/uc/course.uc.ts
  apps/server/src/modules/learnroom/uc/index.ts
  apps/server/src/modules/learnroom/utils/testHelper.ts
  apps/server/src/modules/news/controller/news.controller.ts
  apps/server/src/modules/news/controller/team-news.controller.ts
  apps/server/src/modules/news/repo/news-scope.ts
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/repo/index.ts
  apps/server/src/modules/task/task.module.ts
  apps/server/src/modules/task/uc/index.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/modules/user/controller/dto/ResolvedUser.dto.ts
  apps/server/src/modules/user/controller/user.controller.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.facade.ts
  apps/server/src/modules/user/utils/createCurrentTestUser.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/common/error/api-validation.error.spec.ts
  apps/server/src/shared/common/error/business.error.spec.ts
  apps/server/src/shared/common/error/business.error.ts
  apps/server/src/shared/common/error/index.ts
  apps/server/src/shared/common/error/validation.error.spec.ts
  apps/server/src/shared/common/error/validation.error.ts
  apps/server/src/shared/domain/interface/index.ts
  apps/server/src/shared/domain/interface/user.ts
  apps/server/src/shared/repo/index.ts
  apps/server/src/shared/repo/scope.spec.ts
  apps/server/src/shared/repo/scope.ts
  src/services/wopi/hooks/index.js
Labels: waiting for review, run tests

#2892 SC-9192 - enable cors for nestjs app routes
  CHANGELOG.md
  apps/server/src/main.ts
  package-lock.json
  package.json
Labels: run tests

#2876 BC-52 - OPS-2491 - Change the hydra service url
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
Labels: waiting for review, run tests

#2900 BC-64 BC-67 enable e2e tests for push on main branch
  .github/workflows/test_e2e_pull_request.yml
  .github/workflows/test_e2e_push_main.yml
  CHANGELOG.md
Labels: run tests

#2875 Hotfix/sc 9130 s3 whitelist filename fix
  CHANGELOG.md
  src/services/fileStorage/proxy-service.js
  src/services/fileStorage/utils/filePathHelper.js
  src/services/fileStorage/utils/index.js
  test/services/fileStorage/utils/filePathHelper.test.js
Labels: ready to merge, run tests

#2899 BC-41 - adds feature flag for S3 Bucket Lifecycle Management
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/services/fileStorage/strategies/awsS3.js
Labels: run tests

#2905 BC-37 - BC-54 - reduce resource consumption for deployed server
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/api-worker-deployment.yml.j2
  ansible/roles/schulcloud-server/templates/deployment.yml.j2
Labels: waiting for review, run tests

#2906 detect cycles in role inheritance structure
  CHANGELOG.md
  src/services/role/hooks/index.js
  src/services/role/hooks/preventCycle.js
  test/services/role/services/roles.test.js
Labels: ready to merge, run tests

#2908 BC-81 - remove old Lern-Store
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/secret.yml.j2
  config/default.schema.json
  config/development.json
  config/production.json
  config/test.json
  src/services/content/docs/openapi.yaml
  src/services/content/hooks/redirect.js
  src/services/content/hooks/resources.js
  src/services/content/hooks/search.js
  src/services/content/index.js
  src/services/edusharing/hooks/index.js
  test/services/content/content.test.js
  test/services/content/mock/response{$limit1}.json
  test/services/content/mock/response{}.json
Labels: WIP

#2918 BC-119 remove s3 lifecycle migration
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1627022636538-add_S3_expiration.js
Labels: run tests

#2928 BC-163 BC-44 remove JWT_WHITELIST_ACCEPT_ALL
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  config/default.schema.json
  src/services/authentication/logic/whitelist.js
  test/app.hooks.redis.test.js
Labels: waiting for review, run tests

#2904 Feature/sc 9083 vuetify admin schools
  CHANGELOG.md
  config/default.schema.json
  src/services/config/publicAppConfigService.js
Labels: waiting for review, run tests

#2941 remove broken system from seeddata
  CHANGELOG.md
  backup/setup/schools.json
Labels: ready to merge, run tests
