Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-12, with the labels that each got.

#3222 Feature/bc 830 show archived courses
  CHANGELOG.md
  apps/server/src/modules/learnroom/controller/course.controller.spec.ts
  apps/server/src/modules/learnroom/controller/course.controller.ts
  apps/server/src/modules/learnroom/uc/course.uc.spec.ts
  apps/server/src/modules/learnroom/uc/course.uc.ts
  apps/server/test/modules/learnroom/course.e2e-spec.ts
Labels: waiting for review, run tests

#3220 BC-874 update server dependencies
  CHANGELOG.md
  apps/server/src/modules/rocketchat/rocket-chat.service.ts
  apps/server/src/shared/common/interceptor/test/create-test.module.ts
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/types/EncryptedString.type.ts
  package-lock.json
  package.json
Labels: ready to merge, run unstable tests

#3226 BC-830 include start and end date of course in rest api
  CHANGELOG.md
  apps/server/src/modules/learnroom/controller/dto/courseMetadata.response.ts
  apps/server/src/modules/learnroom/mapper/course.mapper.ts
  apps/server/src/shared/domain/entity/course.entity.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
Labels: waiting for review

#3225 Feature/bc 829 courses as dashboard elements
  CHANGELOG.md
  apps/server/src/modules/learnroom/controller/course.controller.spec.ts
  apps/server/src/modules/learnroom/controller/dashboard.controller.spec.ts
  apps/server/src/modules/learnroom/controller/dto/dashboard.response.ts
  apps/server/src/modules/learnroom/mapper/course.mapper.ts
  apps/server/src/modules/learnroom/mapper/dashboard.mapper.spec.ts
  apps/server/src/modules/learnroom/mapper/dashboard.mapper.ts
  apps/server/src/modules/learnroom/uc/dashboard.uc.spec.ts
  apps/server/src/modules/learnroom/uc/dashboard.uc.ts
  apps/server/src/shared/domain/entity/all-entities.ts
  apps/server/src/shared/domain/entity/course.entity.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/domain/entity/dashboard.entity.spec.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboard.model.entity.ts
  apps/server/src/shared/domain/entity/dashboardElement.entity.spec.ts
  apps/server/src/shared/domain/interface/index.ts
  apps/server/src/shared/domain/interface/learnroom.ts
  apps/server/src/shared/domain/types/index.ts
  apps/server/src/shared/domain/types/learnroom.types.ts
  apps/server/src/shared/repo/course/course.repo.integration.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.integration.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.ts
  apps/server/test/modules/learnroom/dashboard.e2e-spec.ts
  backup/setup/migrations.json
  migrations/1638537287726-reset-dashboard-collections-03-12-21.js
Labels: waiting for review

#3203 BC-617 Changes on instances for transition HPI -> Dataport
  CHANGELOG.md
  ansible/roles/schulcloud-server/templates/configmap.yml.j2
  backup/setup/helpdocuments.json
  config/default.schema.json
Labels: waiting for review, run tests

#3231 some fixes
  config/default.schema.json
  src/services/school/model.js
  src/services/sync/model/userMigration.schema.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/SyncMessageBuilder.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  src/services/sync/strategies/consumerActions/SchoolAction.js
  src/services/sync/strategies/consumerActions/UserAction.js
Labels: WIP

#3230 BC-830 sort rooms-list to currently updated descending
  CHANGELOG.md
  apps/server/src/modules/learnroom/uc/course.uc.spec.ts
  apps/server/src/modules/learnroom/uc/course.uc.ts
Labels: waiting for review, run tests

#3233 BC-741 - Sort and split ansible rols
  CHANGELOG.md
  ansible/roles/schulcloud-management/tasks/main.yml
  ansible/roles/schulcloud-server-core/tasks/main.yml
  ansible/roles/schulcloud-server-core/templates/api-delete-s3-files-cronjob.yml.j2
  ansible/roles/schulcloud-server-core/templates/configmap.yml.j2
  ansible/roles/schulcloud-server-core/templates/deployment.yml.j2
  ansible/roles/schulcloud-server-core/templates/onepassword.yml.j2
  ansible/roles/schulcloud-server-core/templates/secret.yml.j2
  ansible/roles/schulcloud-server-core/templates/svc.yml.j2
  ansible/roles/schulcloud-server-init/tasks/main.yml
  ansible/roles/schulcloud-server-init/templates/configmap_file_init_db.yml.j2
  ansible/roles/schulcloud-server-init/templates/job_init_db.yml.j2
  ansible/roles/schulcloud-server-init/templates/management-deployment.yml.j2
  ansible/roles/schulcloud-server-init/templates/management-svc.yml.j2
  ansible/roles/schulcloud-server-ldap/tasks/main.yml
  ansible/roles/schulcloud-server-ldap/templates/deployment.yml.j2
  ansible/roles/schulcloud-server-ldap/templates/service.yml.j2
  ansible/roles/schulcloud-server-ldapsync/tasks/main.yml
  ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-deployment.yml.j2
  ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
  ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-service.yml.j2
  ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-worker-deployment.yml.j2
  ansible/roles/schulcloud-server-tspsync/tasks/main.yml
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-cronjob.yml.j2
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-deployment.yml.j2
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-svc.yml.j2
  file
Labels: waiting for review

#3235 version 26.20.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: waiting for review

#3214 BC-826 add status for finished tasks
  CHANGELOG.md
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/uc/task.authorization.service.spec.ts
  apps/server/src/modules/task/uc/task.authorization.service.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/shared/domain/entity/task.entity.ts
  apps/server/src/shared/repo/task/task-scope.ts
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task.repo.ts
  apps/server/src/shared/testing/create-current-test-user.ts
  apps/server/src/shared/testing/factory/task.factory.ts
  apps/server/test/modules/task/task-finished.e2e-spec.ts
  apps/server/test/modules/task/task.e2e-spec.ts
  apps/server/test/modules/task/taskFinished.e2e-spec.ts
Labels: WIP

#3236 BC-920 remove changelog
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: waiting for review

#3241 BC-837 add script to start user migration
  scripts/startUserMigration.js
Labels: ready to merge

#3238 remove deleted/archived courses from dashboard
  apps/server/src/shared/domain/entity/dashboard.entity.spec.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboardElement.entity.spec.ts
Labels: waiting for review

#3224 BC-837 prepare migration of user accounts to LDAP
  src/services/school/model.js
  src/services/sync/model/importUser.schema.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/consumerActions/ClassAction.js
  src/services/sync/strategies/consumerActions/SchoolAction.js
  src/services/sync/strategies/consumerActions/UserAction.js
  test/services/helpers/services/importUsers.js
  test/services/helpers/services/index.js
  test/services/helpers/testObjects.js
  test/services/sync/repo/user.repo.integration.test.js
  test/services/sync/strategies/consumerActions/ClassAction.test.js
  test/services/sync/strategies/consumerActions/UserAction.test.js
Labels: ready to merge

#3237 BC-925 UX fixes backend
  apps/server/src/modules/learnroom/controller/dto/dashboard.response.ts
  apps/server/src/modules/learnroom/mapper/dashboard.mapper.spec.ts
  apps/server/src/modules/learnroom/mapper/dashboard.mapper.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboardElement.entity.spec.ts
Labels: waiting for review, run tests

#3244 BC-744 - BC-936 - Update the ansible group and host vars
  ansible/group_vars/brb/schulcloud-server.yml
  ansible/group_vars/default/schulcloud-server.yml
  ansible/group_vars/develop/schulcloud-server.yml
  ansible/group_vars/nbc/schulcloud-server.yml
  ansible/group_vars/reference/schulcloud-server.yml
Labels: waiting for review

#3245 versionbump 26.21.0
  package-lock.json
  package.json
Labels: waiting for review

#3243 BC-840 auto match import users on import
  src/services/sync/model/importUser.schema.js
  src/services/sync/repo/user.repo.js
  src/services/sync/strategies/consumerActions/UserAction.js
  test/services/sync/repo/user.repo.integration.test.js
  test/services/sync/strategies/consumerActions/UserAction.test.js
Labels: ready to merge

#3246 BC-915 sync admin role for univention
  src/services/ldap/strategies/univention.js
  test/services/ldap/strategies/univention.test.js
Labels: ready to merge

#3247 BC-958 BC-965 BC-966 import user api definition & update
  apps/server/src/modules/user-import/controller/dto/import-user-filter.query.ts
  apps/server/src/modules/user-import/controller/dto/import-user.response.ts
  apps/server/src/modules/user-import/controller/dto/match-creator.response.ts
  apps/server/src/modules/user-import/controller/dto/role-name.response.ts
  apps/server/src/modules/user-import/controller/dto/update-match.params.ts
  apps/server/src/modules/user-import/controller/dto/user-match.response.ts
  apps/server/src/modules/user-import/controller/import-user.controller.ts
  apps/server/src/modules/user-import/user-import.module.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/controller/swagger.ts
  apps/server/src/shared/domain/entity/all-entities.ts
  apps/server/src/shared/domain/entity/import-user.entity.ts
  apps/server/src/shared/domain/entity/system.entity.ts
Labels: waiting for review

#3249 BC-781 - Update deploy and clean github workflow
  .github/workflows/clean.yml
  .github/workflows/push.yml
Labels: waiting for review

#3252 tryout
  src/externalServices/apiHelper.js
  src/services/fileStorage/proxy-service.js
Labels: WIP
