Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2021-02, with the labels that each got.

#2188 SC-7937 - allows array for add materials to lesson
  CHANGELOG.md
  src/services/lesson/hooks/addMaterial.js
  src/services/lesson/services/AddMaterialService.js
  test/services/lessons/addMaterialService.test.js
Labels: ready to merge

#2234 hotfix 25.5.14 fix broken user index
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/model/user.schema.js
Labels: waiting for review

#2235 Hotfix SC-8571
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/roster/hooks/index.js
  src/services/roster/index.js
  test/services/roster/index.test.js
Labels: waiting for review

#2229 Feature/sc 8500 error handling vol 2
  CHANGELOG.md
  src/components/course/uc/deleteUserData/deleteUserDataSteps.js
  src/components/fileStorage/repo/files.repo.js
  src/components/helpdesk/repo/problem.repo.js
  src/components/helpdesk/uc/helpdesk.uc.js
  src/components/helper/validation.helper.js
  src/components/pseudonym/repo/pseudonym.repo.js
  src/components/pseudonym/uc/pseudonym.uc.js
  src/components/task/repo/task.repo.integration.test.js
  src/components/task/repo/task.repo.js
  src/components/task/uc/deleteUserData.uc.js
  src/components/user-group/repo/classes.repo.js
  src/components/user-group/uc/deleteUserData.uc.js
  src/components/user/repo/registrationPin.repo.js
  src/components/user/uc/registrationPin.uc.js
  src/errors/applicationErrors.js
  src/errors/assertionErrorHelper.js
  src/services/videoconference/logic/index.js
Labels: ready to merge

#1900 OPS-1508 - RAM and CPU Limit Docker Compse file
  CHANGELOG.md
  compose-server-test.dummy
Labels: auto update, waiting for review

#2241 SC-8588 remove apostrophe from bbb allowed room name chars
  src/services/videoconference/logic/index.js
  test/services/videoconference/logic/index.js
Labels: ready to merge

#2247 Hotfix/1/SC-8512 - migration of events duplicates
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1612529901503-remove_event_duplication.js
  package-lock.json
  package.json
Labels: waiting for review

#2249 SC-8408: delete by scope route
  CHANGELOG.md
  src/services/calendar/courseCalendar.js
  src/services/calendar/index.js
Labels: auto update, ready to merge

#2264 Hotfix/3/VOR-1/passwordRecovery
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/passwordRecovery/services/ChangePasswordService.js
  test/services/passwordRecovery/index.test.js
  test/services/passwordRecovery/services/ChangePasswordService.test.js
Labels: waiting for review

#2265 VOR-2 Adjust rule for adding team member from other schools
  CHANGELOG.md
  config/default.schema.json
  package-lock.json
  package.json
  src/components/task/repo/task.repo.integration.test.js
  src/services/user/hooks/publicTeachers.js
Labels: auto update, waiting for review

#2254 SC-8341: add tombstone school to the tombstone user
  CHANGELOG.md
  src/components/user/repo/user.repo.integration.test.js
  src/components/user/uc/users.uc.integration.test.js
  src/components/user/uc/users.uc.js
  src/components/user/uc/users.uc.unit.test.js
Labels: ready to merge, waiting for review

#2080 fix deletion of teachers via new route
  CHANGELOG.md
  src/components/user/services/index.js
  src/components/user/services/user.service.v2.integration.test.js
Labels: waiting for review

#2273 Hotfix/3/vor 3/replace file links
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1562595327050-AddPositionToLessons.js
  migrations/1564493063114-persist_files_by_copied_courses.js
  migrations/1591695787216-move_etherpad.js
  migrations/1610972728660-syncIndexes.js
  migrations/1613348381637-replaceFileLinks.js
  migrations/done/addShareTockenToLessons.js
  migrations/done/editorlinks.js
  migrations/index.js
  migrations/template.js
  package-lock.json
  package.json
  src/components/course/repo/db/lesson.js
  src/services/lesson/hooks/checkIfCourseGroupLesson.js
  src/services/lesson/hooks/copy.js
  src/services/lesson/hooks/index.js
  src/services/lesson/index.js
  src/services/lesson/model.js
  src/services/lesson/services/LessonCopyService.js
  src/services/lesson/services/LessonFilesService.js
  src/services/link/index.js
  src/services/link/link-model.js
  src/services/statistic/index.js
  src/services/user-group/services/course-copy-service.js
  test/services/helpers/services/lessons.js
Labels: waiting for review

#2274 SC-8613 add flag verify ldap config for full/partial sync
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/ldap-config/docs/openapi.yaml
  src/services/ldap-config/service.js
  src/services/ldap/index.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/interface.js
  src/services/ldap/strategies/iserv-idm.js
  src/services/ldap/strategies/iserv.js
  src/services/ldap/strategies/univention.js
Labels: waiting for review

#2283 Revert "SC-8613 add flag verify ldap config for full/partial sync"
  CHANGELOG.md
  src/services/ldap-config/docs/openapi.yaml
  src/services/ldap-config/service.js
  src/services/ldap/index.js
  src/services/ldap/strategies/general.js
  src/services/ldap/strategies/interface.js
  src/services/ldap/strategies/iserv-idm.js
  src/services/ldap/strategies/iserv.js
  src/services/ldap/strategies/univention.js
  test/services/ldap-config/service.integration.test.js
  test/services/ldap-config/service.unit.test.js
Labels: WIP

#2281 SC-8634 Add migration to replace file links in homework
  CHANGELOG.md
  backup/setup/migrations.json
  migrations/1613491062486-replaceFileLinksHomework.js
  package-lock.json
  package.json
  src/services/homework/model.js
Labels: waiting for review

#2291 hotfix/25.6.6/Fix migration and add secure patch conditions.
  CHANGELOG.md
  migrations/1613348381637-replaceFileLinks.js
  migrations/1613491062486-replaceFileLinksHomework.js
  package-lock.json
  package.json
Labels: waiting for review

#2292 SC-8655
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/user/hooks/userService.js
  src/services/user/services/AdminUsers.js
  src/services/user/services/userService.js
  test/services/user/services/AdminUsers.test.js
  test/services/user/services/userService.test.js
Labels: hotfix: do not merge here, waiting for review

#2282 Feature/sc 8541 classes permissions
  CHANGELOG.md
  src/hooks/index.js
  src/services/user-group/hooks/classes.js
  src/services/user-group/hooks/helpers/classHooks.js
  src/services/user-group/services/classes.js
  test/services/user-group/hooks/classes.test.js
  test/services/user-group/index.test.js
  test/services/user-group/services/classes.test.js
Labels: waiting for review

#2290 Hotfix/sc 8477/ldap optimization
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/sync/strategies/LDAPSchoolSyncer.js
Labels: waiting for review

#2296 SC-7021 Deletion of user data after a specific time
  CHANGELOG.md
  src/components/user/repo/db/trashbin.schema.js
Labels: waiting for review

#2263 Feature/SC-7944 - persistent lern-store ids
  CHANGELOG.md
  package.json
  src/services/edusharing/services/EduSharingConnector.js
  test/services/edusharing/mock/response-node-restricted.json
  test/services/edusharing/mock/response-node.json
  test/services/edusharing/services/EduSharingConnector.test.js
  test/services/edusharing/services/merlinGenerator.test.js
Labels: ready to merge

#2303 Feature/sc 6679 text editor table issue
  CHANGELOG.md
  src/utils/sanitizeHtml.js
  test/app.hooks.test.js
Labels: auto update, waiting for review

#2308 Feature/sc 8599 remodel help area contact page
  CHANGELOG.md
  src/services/helpdesk/hooks/index.js
Labels: auto update, waiting for review

#2317 SC-8682 - add isexternal check to adminusers patch
  CHANGELOG.md
  src/services/user/services/AdminUsers.js
  test/services/user/services/AdminUsers.test.js
Labels: waiting for review

#2321 Feature/sc 6679 table structure properties
  CHANGELOG.md
  src/utils/sanitizeHtml.js
  test/app.hooks.test.js
Labels: auto update, waiting for review

#2324 SC-8728 fix configuration reset in tests
  CHANGELOG.md
  test/services/messenger/services/messengerConfigService.test.js
  test/services/messenger/services/messengerPermissionService.test.js
  test/services/messengerSync/utils.test.js
Labels: ready to merge

#2325 Hotfix/1/sc 8714 iserv sync fail
  CHANGELOG.md
  package-lock.json
  package.json
  src/services/fileStorage/strategies/awsS3.js
  src/services/sync/strategies/LDAPSyncer.js
Labels: WIP, hotfix: do not merge here

#2309 SC-8250 - Connect UI for bulk delete
  CHANGELOG.md
  src/components/user/docs/openapi.yaml
  src/components/user/index.js
  src/components/user/repo/user.repo.integration.test.js
  src/components/user/repo/user.repo.js
  src/components/user/services/user.service.v2.integration.test.js
  src/components/user/services/user.service.v2.js
  src/components/user/uc/users.uc.js
  src/errors/validationErrorHelper.js
Labels: waiting for review
