Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2022-01, with the labels that each got.

#3258 BC-1049 inline user match into importuser
  src/services/sync/model/importUser.schema.js
  src/services/sync/strategies/consumerActions/UserAction.js
Labels: WIP

#3248 BC-846 clean up constructors
  apps/server/src/modules/learnroom/controller/dto/dashboard.response.ts
  apps/server/src/modules/learnroom/controller/dto/movePosition.params.ts
  apps/server/src/modules/learnroom/mapper/dashboard.mapper.ts
  apps/server/src/shared/domain/entity/dashboard.entity.ts
  apps/server/src/shared/domain/entity/dashboard.model.entity.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.spec.ts
  apps/server/src/shared/repo/dashboard/dashboard.model.mapper.ts
  apps/server/src/shared/repo/dashboard/dashboard.repo.integration.spec.ts
Labels: waiting for review

#3263 fix positioning of new dashboard elements
  apps/server/src/shared/domain/entity/dashboard.entity.ts
Labels: waiting for review

#3262 BC-909 hide tasks a user created in courses he left
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task.repo.ts
Labels: waiting for review

#3259 Feature/bc 999 update status pages
  config/default.schema.json
  src/services/config/publicAppConfigService.js
Labels: waiting for review, run tests

#3260 Feature/bc 919 navigation rooms overview
  config/default.schema.json
  src/services/config/publicAppConfigService.js
Labels: waiting for review, run tests

#3267 feature/BC-999-update-status-pages config cleanup
  ansible/roles/schulcloud-server-core/templates/configmap.yml.j2
  config/default.schema.json
  config/development.json
  src/externalServices/statusApi.js
  src/services/alert/MessageProvider/status/index.js
  src/services/alert/index.js
Labels: waiting for review

#3271 Release/27.0.0
  package-lock.json
  package.json
Labels: waiting for review

#3270 BC-1006 - Meta file for the roles
  ansible/roles/schulcloud-server-core/meta/main.yml
  ansible/roles/schulcloud-server-init/meta/main.yml
  ansible/roles/schulcloud-server-ldap/meta/main.yml
  ansible/roles/schulcloud-server-ldapsync/meta/main.yml
  ansible/roles/schulcloud-server-tspsync/meta/main.yml
Labels: waiting for review

#3278 BC-867 update deps fishery to v2.1
  apps/server/src/shared/testing/factory/base.factory.ts
  package-lock.json
  package.json
Labels: waiting for review

#3287 BC-1087 - update configmap to an loop
  ansible/roles/schulcloud-server-core/templates/configmap.yml.j2
Labels: waiting for review

#3282 Feature/bc 542 remove current user from jwt logic
  apps/server/src/modules/authentication/auth.module.ts
  apps/server/src/modules/authentication/strategy/jwt.strategy.spec.ts
  apps/server/src/modules/authentication/strategy/jwt.strategy.ts
  apps/server/src/modules/authorization/authorization.service.spec.ts
  apps/server/src/modules/learnroom/learnroom.module.ts
  apps/server/src/modules/learnroom/uc/dashboard.uc.spec.ts
  apps/server/src/modules/learnroom/uc/dashboard.uc.ts
  apps/server/src/modules/learnroom/uc/rooms.uc.spec.ts
  apps/server/src/modules/learnroom/uc/rooms.uc.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/task/controller/task.controller.spec.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/task/mapper/task.mapper.spec.ts
  apps/server/src/modules/task/task.module.ts
  apps/server/src/modules/task/uc/task.authorization.service.spec.ts
  apps/server/src/modules/task/uc/task.authorization.service.ts
  apps/server/src/modules/task/uc/task.uc.spec.ts
  apps/server/src/modules/task/uc/task.uc.ts
  apps/server/src/modules/user/controller/user.controller.spec.ts
  apps/server/src/modules/user/controller/user.controller.ts
  apps/server/src/modules/user/index.ts
  apps/server/src/modules/user/uc/index.ts
  apps/server/src/modules/user/uc/role.uc.spec.ts
  apps/server/src/modules/user/uc/role.uc.ts
  apps/server/src/modules/user/uc/user.uc.spec.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.facade.spec.ts
  apps/server/src/modules/user/user.facade.ts
  apps/server/src/modules/user/user.module.ts
  apps/server/src/shared/domain/entity/course.entity.spec.ts
  apps/server/src/shared/domain/entity/course.entity.ts
  apps/server/src/shared/domain/entity/role.entity.ts
  apps/server/src/shared/domain/entity/task.entity.spec.ts
  apps/server/src/shared/domain/entity/task.entity.ts
  apps/server/src/shared/domain/index.ts
  apps/server/src/shared/domain/service/index.ts
  apps/server/src/shared/domain/service/permission.service.spec.ts
  apps/server/src/shared/domain/service/permission.service.ts
  apps/server/src/shared/repo/course/course.repo.integration.spec.ts
  apps/server/src/shared/repo/news/news.repo.integration.spec.ts
  apps/server/src/shared/repo/role/role.repo.integration.spec.ts
  apps/server/src/shared/repo/role/role.repo.ts
  apps/server/src/shared/repo/submission/submission.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/user/user.repo.integration.spec.ts
  apps/server/src/shared/repo/user/user.repo.ts
  apps/server/src/shared/testing/clean-up-collections.ts
  apps/server/src/shared/testing/cleanup-collections.ts
  apps/server/src/shared/testing/create-current-test-user.ts
  apps/server/src/shared/testing/index.ts
  apps/server/src/shared/testing/mapUserToCurrentUser.ts
  apps/server/test/modules/learnroom/course.e2e-spec.ts
  apps/server/test/modules/learnroom/dashboard.e2e-spec.ts
  apps/server/test/modules/learnroom/rooms.e2e-spec.ts
  apps/server/test/modules/news/news.e2e-spec.ts
  apps/server/test/modules/task/task-finished.e2e-spec.ts
  apps/server/test/modules/task/task.e2e-spec.ts
  apps/server/test/modules/user/user.e2e-spec.ts
  config/test.json
Labels: waiting for review

#3294 version 27.2.0
  package-lock.json
  package.json
Labels: waiting for review

#3291 bc 1115 course board shows tasks that throw permission error
  apps/server/src/modules/learnroom/uc/rooms.uc.spec.ts
  apps/server/src/modules/learnroom/uc/rooms.uc.ts
  apps/server/src/shared/repo/task/task-scope.ts
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task.repo.ts
Labels: waiting for review

#3298 BC-1103 implementing lessons into rooms - Backend
  apps/server/src/modules/learnroom/controller/dto/roomBoardResponse.ts
  apps/server/src/modules/learnroom/learnroom.module.ts
  apps/server/src/modules/learnroom/mapper/board.mapper.spec.ts
  apps/server/src/modules/learnroom/mapper/board.mapper.ts
  apps/server/src/modules/learnroom/uc/rooms.uc.spec.ts
  apps/server/src/modules/learnroom/uc/rooms.uc.ts
  apps/server/src/shared/repo/lesson/lesson.repo.integration.spec.ts
Labels: waiting for review
