Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2022-03, with the labels that each got.

#3341 version 27.7.0
  package-lock.json
  package.json
Labels: waiting for review

#3344 BC-1356 - Fix url for LDAP Sync
  ansible/roles/schulcloud-server-ldapsync/templates/api-ldap-sync-full-cronjob.yml.j2
Labels: waiting for review

#3330 Feature/n21 36 adjust encryption key
  ansible/roles/schulcloud-server-core/templates/secret.yml.j2
  apps/server/src/modules/oauth/oauth.module.ts
  config/default.schema.json
  config/development.json
  config/test.json
Labels: ready to merge

#3356 Feature/n21 48 3rd party logout prototype
  apps/server/src/modules/oauth/controller/dto/oauth-response.ts
  apps/server/src/modules/oauth/controller/oauth-sso.controller.spec.ts
  apps/server/src/modules/oauth/controller/oauth-sso.controller.ts
  apps/server/src/modules/oauth/error/oauth-sso.error.spec.ts
  apps/server/src/modules/oauth/error/oauth-sso.error.ts
  apps/server/src/modules/oauth/mapper/token-request-payload.mapper.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.ts
  apps/server/src/shared/domain/entity/system.entity.ts
  apps/server/src/shared/testing/factory/system.factory.ts
  backup/setup/accounts.json
  backup/setup/systems.json
  backup/setup/users.json
  src/services/school/services/schoolsList.js
  src/services/system/model.js
Labels: waiting for review

#3095 use unknown instead of any
  apps/server/src/core/logger/logger.interface.ts
Labels: waiting for review

#3361 BC-1143 - remove notificaiton service from the code
  compose-server-test.dummy
  config/default.json
  config/default.schema.json
  config/test.json
  src/services/account/services/SupportJWTService.js
  src/services/helpdesk/hooks/index.js
  src/services/index.js
  src/services/notification/docs/openapi.yaml
  src/services/notification/hooks/index.js
  src/services/notification/index.js
  src/utils/apiValidation.js
  test/services/helpers/service.test.js
  test/services/notification/index.test.js
  test/services/notification/mock/mockResponses.js
Labels: waiting for review

#3352 Feature/bc 1272 deletion of file
  apps/server/src/core/logger/logger.interface.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.ts
  apps/server/src/modules/files-storage/controller/dto/file-storage.response.ts
  apps/server/src/modules/files-storage/controller/files-storage.controller.ts
  apps/server/src/modules/files-storage/files-storage.module.ts
  apps/server/src/modules/files-storage/interface/index.ts
  apps/server/src/modules/files-storage/interface/storage-client.ts
  apps/server/src/modules/files-storage/uc/file-record.uc.spec.ts
  apps/server/src/modules/files-storage/uc/file-record.uc.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.spec.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.ts
  apps/server/src/shared/domain/entity/filerecord.entity.ts
  apps/server/src/shared/repo/filerecord/filerecord-scope.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.integration.spec.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.ts
  apps/server/test/modules/files-storage/file-storage-delete-files.e2e-spec.ts
  apps/server/test/modules/files-storage/file-storage-list-files.e2e-spec.ts
  apps/server/test/modules/files-storage/file-storage-with-s3-server.e2e-spec.ts
Labels: waiting for review

#3364 Bump url-parse from 1.5.4 to 1.5.10
  package-lock.json
Labels: dependencies, waiting for review

#3375 BC-1273 - add restoring of files
  apps/server/src/modules/files-storage/client/s3-client.adapter.spec.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.ts
  apps/server/src/modules/files-storage/controller/files-storage.controller.ts
  apps/server/src/modules/files-storage/interface/storage-client.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.spec.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.integration.spec.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.ts
  apps/server/test/modules/files-storage/file-storage-restore-files.e2e-spec.ts
Labels: waiting for review

#3378 bc-1327 - copying of files via file service
  apps/server/src/modules/files-storage/client/s3-client.adapter.spec.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.ts
  apps/server/src/modules/files-storage/controller/dto/file-storage.params.ts
  apps/server/src/modules/files-storage/controller/files-storage.controller.ts
  apps/server/src/modules/files-storage/interface/storage-client.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.spec.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.ts
  apps/server/test/modules/files-storage/file-storage-copy-files.e2e-spec.ts
Labels: waiting for review
