Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2022-04, with the labels that each got.

#3393 Feature/ew 157 change own password refactoring
  apps/server/src/modules/authentication/controller/account.controller.spec.ts
  apps/server/src/modules/authentication/controller/account.controller.ts
  apps/server/src/modules/authentication/controller/dto/index.ts
  apps/server/src/modules/authentication/controller/dto/patch-my-account.params.ts
  apps/server/src/modules/authentication/controller/dto/patch-my-password.params.ts
  apps/server/src/modules/authentication/uc/account.uc.spec.ts
  apps/server/src/modules/authentication/uc/account.uc.ts
  apps/server/src/shared/common/error/authorization.error.spec.ts
  apps/server/src/shared/common/error/authorization.error.ts
  apps/server/src/shared/common/error/forbidden-operation.error.spec.ts
  apps/server/src/shared/common/error/forbidden-operation.error.ts
  apps/server/src/shared/common/error/index.ts
  apps/server/src/shared/domain/entity/user.entity.ts
  apps/server/src/shared/repo/account/account.repo.integration.spec.ts
  apps/server/src/shared/repo/account/account.repo.ts
  apps/server/src/shared/repo/user/user.repo.integration.spec.ts
  apps/server/src/shared/repo/user/user.repo.ts
  apps/server/test/modules/authentication/account.e2e-spec.ts
Labels: waiting for review

#3400 BC-1617 - Make it possible to disable single speaks over configuartions
  apps/server/src/modules/user/uc/index.ts
  apps/server/src/modules/user/uc/user.uc.spec.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.config.ts
  apps/server/src/modules/user/user.module.ts
  package-lock.json
  package.json
Labels: waiting for review

#3366 BC-1408 - School Feature Toggles
  src/services/config/publicAppConfigService.js
  src/services/school/services/permissions.js
Labels: run tests

#3407 Feature/bc 1455 file service request timeout
  .eslintrc.js
  .vscode/settings.default.json
  apps/server/src/core/core.module.ts
  apps/server/src/core/index.ts
  apps/server/src/core/interfaces/core-module-config.ts
  apps/server/src/core/interfaces/index.ts
  apps/server/src/modules/files-storage/files-storage.config.ts
  apps/server/src/modules/files-storage/files-storage.module.ts
  apps/server/src/server.config.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/common/interceptor/constants.ts
  apps/server/src/shared/common/interceptor/index.ts
  apps/server/src/shared/common/interceptor/interfaces/index.ts
  apps/server/src/shared/common/interceptor/interfaces/interceptor-config.ts
  apps/server/src/shared/common/interceptor/timeout.interceptor.spec.ts
  apps/server/src/shared/common/interceptor/timeout.interceptor.ts
  config/default.json
  config/default.schema.json
  config/development.json
  package-lock.json
  package.json
Labels: waiting for review

#3410 ce/fix close operation in test
  apps/server/src/modules/learnroom/mapper/room-board-response.mapper.spec.ts
Labels: waiting for review

#3396 Feature/n21 33 oauth token validation
  apps/server/src/modules/oauth/mapper/token-request-payload.mapper.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.ts
  apps/server/src/shared/domain/entity/system.entity.ts
  apps/server/src/shared/testing/factory/system.factory.ts
  backup/setup/systems.json
  package-lock.json
  package.json
Labels: ready to merge

#3416 Bump winston from 3.5.1 to 3.7.2
  package-lock.json
  package.json
Labels: dependencies, waiting for review

#3423 BC-1667 - remove auto reviewer assignment by pullapprove
  .pullapprove.yml
Labels: waiting for review

#3406 Feature/ew 165 account refactoring
  apps/server/src/modules/authentication/controller/account.controller.spec.ts
  apps/server/src/modules/authentication/controller/account.controller.ts
  apps/server/src/modules/authentication/controller/dto/account-by-id.body.params.ts
  apps/server/src/modules/authentication/controller/dto/account-by-id.params.ts
  apps/server/src/modules/authentication/controller/dto/account-search-list.response.ts
  apps/server/src/modules/authentication/controller/dto/account-search-type.ts
  apps/server/src/modules/authentication/controller/dto/account-search.query.params.ts
  apps/server/src/modules/authentication/controller/dto/account.response.ts
  apps/server/src/modules/authentication/controller/dto/change-password.params.ts
  apps/server/src/modules/authentication/controller/dto/index.ts
  apps/server/src/modules/authentication/mapper/account-response.mapper.ts
  apps/server/src/modules/authentication/uc/account.uc.spec.ts
  apps/server/src/modules/authentication/uc/account.uc.ts
  apps/server/src/shared/common/error/business.error.ts
  apps/server/src/shared/controller/dto/pagination.response.ts
  apps/server/src/shared/domain/entity/import-user.entity.ts
  apps/server/src/shared/repo/account/account.repo.integration.spec.ts
  apps/server/src/shared/repo/account/account.repo.ts
  apps/server/test/modules/authentication/account.e2e-spec.ts
Labels: API, waiting for review

#3412 add new board elements to the top
  apps/server/src/shared/domain/entity/board.entity.spec.ts
  apps/server/src/shared/domain/entity/board.entity.ts
  config/default.schema.json
  src/services/config/publicAppConfigService.js
Labels: waiting for review

#3424 BC-1436 - add logging for Users and Classes errors for the ldap sync
  src/services/sync/strategies/LDAPSyncer.js
Labels: waiting for review

#3427 BC-1386: Missing active state on Courses
  config/default.schema.json
  src/services/config/publicAppConfigService.js
Labels: waiting for review

#3428 EW-213 Keycloak documentation
  apps/server/README.md
  apps/server/doc/summary.json
Labels: waiting for review
