Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2022-02, with the labels that each got.

#3305 Bc 1149 task card reimplementation
  apps/server/src/modules/learnroom/controller/dto/roomBoardResponse-taskStatus.ts
  apps/server/src/modules/learnroom/mapper/board.mapper.ts
  apps/server/src/modules/task/controller/dto/task.response.ts
  apps/server/src/modules/task/mapper/task.mapper.spec.ts
  apps/server/src/modules/task/mapper/task.mapper.ts
  apps/server/src/shared/domain/entity/task.entity.spec.ts
  apps/server/src/shared/domain/entity/task.entity.ts
Labels: waiting for review

#3309 BC-1071 fix sorting bug by similar dueDates for paginated requests
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  apps/server/src/shared/repo/task/task.repo.ts
Labels: waiting for review

#3311 BC-1230 - change mode for configmaps to apply
  ansible/roles/schulcloud-server-core/tasks/main.yml
Labels: waiting for review

#3300 Feature/n21 9 oauth iserv flow
  apps/server/src/modules/authorization/authorization.module.ts
  apps/server/src/modules/authorization/feathers-jwt.provider.spec.ts
  apps/server/src/modules/authorization/feathers-jwt.provider.ts
  apps/server/src/modules/authorization/index.ts
  apps/server/src/modules/oauth/controller/dto/authorization.query.ts
  apps/server/src/modules/oauth/controller/dto/oauth-response.ts
  apps/server/src/modules/oauth/controller/dto/oauth-token-response.ts
  apps/server/src/modules/oauth/controller/dto/oauth.dto.spec.ts
  apps/server/src/modules/oauth/controller/dto/token-request-params.ts
  apps/server/src/modules/oauth/controller/dto/token-request-payload.ts
  apps/server/src/modules/oauth/controller/oauth-sso.controller.spec.ts
  apps/server/src/modules/oauth/controller/oauth-sso.controller.ts
  apps/server/src/modules/oauth/index.ts
  apps/server/src/modules/oauth/mapper/token-request-params.mapper.ts
  apps/server/src/modules/oauth/mapper/token-request-payload.mapper.spec.ts
  apps/server/src/modules/oauth/mapper/token-request-payload.mapper.ts
  apps/server/src/modules/oauth/oauth.module.ts
  apps/server/src/modules/oauth/uc/index.ts
  apps/server/src/modules/oauth/uc/oauth.uc.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/domain/entity/school.entity.ts
  apps/server/src/shared/domain/entity/system.entity.ts
  apps/server/src/shared/domain/entity/user.entity.ts
  apps/server/src/shared/infra/feathers/feathers-service.provider.ts
  apps/server/src/shared/repo/system/index.ts
  apps/server/src/shared/repo/system/system.repo.integration.spec.ts
  apps/server/src/shared/repo/system/system.repo.ts
  apps/server/src/shared/repo/user/user.repo.integration.spec.ts
  apps/server/src/shared/repo/user/user.repo.ts
  apps/server/src/shared/testing/factory/system.factory.ts
  backup/setup/schools.json
  backup/setup/systems.json
  config/default.schema.json
  config/development.json
  package-lock.json
  package.json
  src/services/school/services/schoolsList.js
  src/services/system/model.js
Labels: waiting for review

#3321 BC-1302 - set the default docker registry for all, will be overwritten for develop
  ansible/group_vars/all/schulcloud-server.yml
Labels: waiting for review

#3322 Feature/n21 39 iserv oauth hotfix
  apps/server/src/modules/oauth/mapper/token-request-payload.mapper.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.ts
  apps/server/src/shared/domain/entity/system.entity.ts
  apps/server/src/shared/testing/factory/system.factory.ts
  src/services/school/services/schoolsList.js
  src/services/system/model.js
Labels: ready to merge

#3308 BC-1199 mvp s3 client download upload
  ansible/roles/schulcloud-server-core/tasks/main.yml
  ansible/roles/schulcloud-server-core/templates/api-files-deployment.yml.j2
  ansible/roles/schulcloud-server-core/templates/api-files-svc.yml.j2
  apps/server/src/files-storage.server.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.spec.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.ts
  apps/server/src/modules/files-storage/controller/dto/file-storage.params.ts
  apps/server/src/modules/files-storage/controller/dto/file-storage.response.ts
  apps/server/src/modules/files-storage/controller/dto/index.ts
  apps/server/src/modules/files-storage/controller/files-storage.controller.ts
  apps/server/src/modules/files-storage/files-storage.module.ts
  apps/server/src/modules/files-storage/interface/config.ts
  apps/server/src/modules/files-storage/interface/file.ts
  apps/server/src/modules/files-storage/interface/storage-client.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.spec.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.ts
  apps/server/src/shared/domain/entity/all-entities.ts
  apps/server/src/shared/domain/entity/filerecord.entity.spec.ts
  apps/server/src/shared/domain/entity/filerecord.entity.ts
  apps/server/src/shared/domain/entity/index.ts
  apps/server/src/shared/repo/base.repo.ts
  apps/server/src/shared/repo/filerecord/filerecord-scope.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.integration.spec.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.ts
  apps/server/src/shared/repo/filerecord/index.ts
  apps/server/src/shared/repo/index.ts
  apps/server/src/shared/testing/factory/filerecord.factory.ts
  apps/server/src/shared/testing/factory/index.ts
  apps/server/test/modules/files-storage/file-storage-upload.e2e-spec.ts
  config/default.schema.json
  config/development.json
  config/test.json
  nest-cli.json
  package-lock.json
  package.json
Labels: waiting for review

#3327 version 27.6.0
  package-lock.json
  package.json
Labels: waiting for review

#3326 BC-1139 - Remove of sentry
  TODO.md
  config/default.schema.json
  package-lock.json
  package.json
  src/app.hooks.js
  src/app.js
  src/errors/utils.js
  src/middleware/errorHandler.js
  src/middleware/sentry.js
  src/services/rocketChat/services/rocketChatLogout.js
Labels: waiting for review

#3319 Feature/bc 1123 follow redirect dependency issue
  apps/server/src/shared/domain/entity/file.entity.ts
  apps/server/src/shared/repo/files/files.repo.spec.ts
  apps/server/src/shared/repo/task/task.repo.integration.spec.ts
  jest.config.ts
  package-lock.json
  package.json
  src/services/user/model/consent.schema.js
  src/services/user/model/user.schema.js
Labels: run tests

#3334 BC-1335 - fix tsp sync
  ansible/roles/schulcloud-server-tspsync/tasks/main.yml
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-base-cronjob.yml.j2
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-cronjob.yml.j2
  ansible/roles/schulcloud-server-tspsync/templates/api-tsp-sync-school-cronjob.yml.j2
Labels: waiting for review
