Repository hpi-schul-cloud/schulcloud-server, pull requests merged in 2022-05, with the labels that each got.

#3437 Bc 1579 general helparea for nbc
  backup/setup/helpdocuments.json
Labels: waiting for review

#3413 BC-1614 Refactor env-vars for student-visibility
  config/default.json
  config/default.schema.json
  config/test.json
  src/services/config/publicAppConfigService.js
  src/services/role/index.js
  src/services/role/utils/permissions.js
  src/services/school/hooks/index.js
  src/services/school/index.js
  src/services/school/services/permissions.js
  test/services/school/services/permissions.test.js
  test/services/school/setDefaultStudentListPermission.integration.test.js
  test/services/user-group/hooks/classes.test.js
Labels: waiting for review

#3411 Feature/bc 1404 extend file storage logging
  apps/server/src/console/console.module.ts
  apps/server/src/core/error/dto/index.ts
  apps/server/src/core/error/error.module.ts
  apps/server/src/core/error/filter/global-error.filter.spec.ts
  apps/server/src/core/error/filter/global-error.filter.ts
  apps/server/src/core/interfaces/core-module-config.ts
  apps/server/src/core/logger/index.ts
  apps/server/src/core/logger/interfaces/index.ts
  apps/server/src/core/logger/interfaces/logger-config.ts
  apps/server/src/core/logger/interfaces/logger.interface.ts
  apps/server/src/core/logger/logger.interface.ts
  apps/server/src/core/logger/logger.service.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.ts
  apps/server/src/modules/files-storage/controller/files-storage.controller.ts
  apps/server/src/modules/files-storage/files-storage.config.ts
  apps/server/src/modules/files-storage/files-storage.module.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.spec.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.ts
  apps/server/src/modules/files/job/delete-files.console.spec.ts
  apps/server/src/modules/files/job/delete-files.console.ts
  apps/server/src/modules/files/uc/delete-files.uc.spec.ts
  apps/server/src/modules/index.ts
  apps/server/src/modules/management/management.module.ts
  apps/server/src/modules/news/controller/news.controller.ts
  apps/server/src/modules/news/news.module.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/oauth/controller/oauth-sso.controller.spec.ts
  apps/server/src/modules/oauth/controller/oauth-sso.controller.ts
  apps/server/src/modules/oauth/uc/oauth.uc.spec.ts
  apps/server/src/modules/oauth/uc/oauth.uc.ts
  apps/server/src/modules/task/controller/task.controller.ts
  apps/server/src/modules/user/index.ts
  apps/server/src/modules/user/interfaces/index.ts
  apps/server/src/modules/user/interfaces/user-config.ts
  apps/server/src/modules/user/uc/user.uc.spec.ts
  apps/server/src/modules/user/uc/user.uc.ts
  apps/server/src/modules/user/user.config.ts
  apps/server/src/modules/user/user.module.ts
  apps/server/src/server.config.ts
  apps/server/src/server.module.ts
  apps/server/src/shared/common/interceptor/duration-logging.interceptor.spec.ts
  apps/server/src/shared/common/interceptor/duration-logging.interceptor.ts
  apps/server/src/shared/common/interceptor/index.ts
  apps/server/src/shared/common/interceptor/request-logging.interceptor.ts
  apps/server/src/shared/common/interceptor/timeout.interceptor.ts
  config/default.schema.json
  config/development.json
  config/test.json
Labels: ready to merge

#3431 BC-1370 - remove demo from the code base
  apps/server/src/modules/authentication/uc/account.uc.spec.ts
  apps/server/src/modules/authentication/uc/account.uc.ts
  backup/setup/migrations.json
  backup/setup/roles.json
  backup/setup/users.json
  migrations/1651058725847-remove_demo.js
  migrations/done/privacy.js
  src/services/account/hooks/index.js
  src/services/role/model.js
  src/services/user/hooks/userService.js
  test/services/teams/index.test.js
Labels: waiting for review

#3450 Feature/bc 1678 strings to enums
  apps/server/src/modules/authentication/services/account.service.spec.ts
  apps/server/src/modules/authentication/uc/account.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.spec.ts
  apps/server/src/modules/news/uc/news.uc.ts
  apps/server/src/modules/user-import/constants.ts
  apps/server/src/modules/user-import/mapper/import-user.mapper.spec.ts
  apps/server/src/modules/user-import/mapper/role-name.mapper.spec.ts
  apps/server/src/modules/user-import/mapper/role-name.mapper.ts
  apps/server/src/modules/user-import/mapper/user-match.mapper.spec.ts
  apps/server/src/modules/user-import/uc/user-import.uc.spec.ts
  apps/server/src/modules/user-import/uc/user-import.uc.ts
  apps/server/src/shared/domain/entity/import-user.entity.ts
  apps/server/src/shared/domain/entity/role.entity.ts
  apps/server/src/shared/domain/index.ts
  apps/server/src/shared/domain/rules/base.rule.spec.ts
  apps/server/src/shared/domain/rules/index.ts
  apps/server/src/shared/domain/rules/permission.enum.ts
  apps/server/src/shared/domain/rules/rolename.enum.ts
  apps/server/src/shared/domain/service/permission.service.spec.ts
  apps/server/src/shared/domain/types/importuser.types.ts
  apps/server/src/shared/domain/vo/index.ts
  apps/server/src/shared/repo/importuser/importuser.repo.integration.spec.ts
  apps/server/src/shared/repo/importuser/importuser.scope.ts
  apps/server/src/shared/repo/role/role.repo.integration.spec.ts
  apps/server/src/shared/repo/role/role.repo.ts
  apps/server/src/shared/testing/factory/course.factory.ts
  apps/server/src/shared/testing/factory/import-user.factory.ts
  apps/server/src/shared/testing/factory/role.factory.ts
  apps/server/src/shared/testing/factory/user.factory.ts
  apps/server/test/modules/authentication/account.e2e-spec.ts
  apps/server/test/modules/learnroom/dashboard.e2e-spec.ts
  apps/server/test/modules/user/import.e2e.spec.ts
Labels: waiting for review

#3362 BC-1373 - Add autorun for the migrations to the deployment
  ansible/roles/schulcloud-server-core/tasks/main.yml
  ansible/roles/schulcloud-server-core/templates/migration-job.yml.j2
Labels: waiting for review

#3453 BC-1723 Add NO_COLOR Environment variable.
  config/default.schema.json
Labels: waiting for review

#3461 Feature/bc 1674 add api response decorators
  apps/server/src/modules/authentication/decorator/auth.decorator.spec.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.spec.ts
  apps/server/src/modules/files-storage/client/s3-client.adapter.ts
  apps/server/src/modules/files-storage/controller/files-storage.controller.ts
  apps/server/src/modules/files-storage/files-storage.const.ts
  apps/server/src/modules/files-storage/uc/file-record.uc.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.spec.ts
  apps/server/src/modules/files-storage/uc/files-storage.uc.ts
  apps/server/src/shared/infra/antivirus/antivirus.service.spec.ts
  apps/server/src/shared/infra/antivirus/antivirus.service.ts
  apps/server/src/shared/repo/filerecord/filerecord.repo.integration.spec.ts
  apps/server/test/modules/files-storage/file-storage-download-upload.e2e-spec.ts
Labels: waiting for review

#3456 BC-1498 make port of file service configurable
  ansible/roles/schulcloud-server-core/templates/api-files-svc.yml.j2
Labels: waiting for review

#3455 BC-1761 - Task chips on lesson card
  apps/server/src/modules/learnroom/controller/dto/board/board-lesson.response.ts
  apps/server/src/modules/learnroom/mapper/room-board-response.mapper.spec.ts
  apps/server/src/modules/learnroom/mapper/room-board-response.mapper.ts
  apps/server/src/modules/learnroom/types/room-board.types.ts
  apps/server/src/modules/learnroom/uc/room-board-dto.factory.spec.ts
  apps/server/src/modules/learnroom/uc/room-board-dto.factory.ts
  apps/server/src/modules/learnroom/uc/rooms.uc.ts
  apps/server/src/shared/domain/entity/lesson.entity.spec.ts
  apps/server/src/shared/domain/entity/lesson.entity.ts
  apps/server/src/shared/domain/entity/task.entity.spec.ts
  apps/server/src/shared/domain/entity/task.entity.ts
Labels: waiting for review

#3468 BC-1556 - Course copy service (Backend)
  apps/server/src/modules/learnroom/controller/dto/course-copy.response.ts
  apps/server/src/modules/learnroom/controller/dto/index.ts
  apps/server/src/modules/learnroom/controller/rooms.controller.spec.ts
  apps/server/src/modules/learnroom/controller/rooms.controller.ts
  apps/server/src/modules/learnroom/learnroom.module.ts
  apps/server/src/modules/learnroom/mapper/course-copy.mapper.ts
  apps/server/src/modules/learnroom/uc/course-copy.uc.spec.ts
  apps/server/src/modules/learnroom/uc/course-copy.uc.ts
  apps/server/src/modules/task/controller/dto/task-copy.response.ts
  apps/server/src/shared/domain/service/course-copy.service.spec.ts
  apps/server/src/shared/domain/service/course-copy.service.ts
  apps/server/src/shared/domain/types/copy.types.ts
  apps/server/test/modules/learnroom/rooms.e2e-spec.ts
Labels: waiting for review

#3471 Feature/n21 115 logout uri field
  src/services/ltiTool/model.js
Labels: ready to merge

#3475 BC-1783 - clean up public tech documentation
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: waiting for review

#3434 Feature/ew 166 refactor user functionality
  apps/server/src/modules/account/controller/account.controller.ts
  apps/server/src/modules/account/services/account.service.ts
  apps/server/src/modules/account/uc/account.uc.spec.ts
  apps/server/src/modules/account/uc/account.uc.ts
  apps/server/src/shared/domain/entity/all-entities.ts
  apps/server/src/shared/domain/entity/school.entity.ts
  apps/server/src/shared/repo/account/account.repo.integration.spec.ts
  apps/server/src/shared/repo/account/account.repo.ts
  apps/server/src/shared/repo/school/school.repo.integration.spec.ts
  apps/server/test/modules/authentication/account.e2e-spec.ts
  src/hooks/index.js
  src/services/account/model.js
Labels: javascript

#3457 Feature/ew 207 erwinidm init
  ansible/roles/schulcloud-server-init/tasks/main.yml
  ansible/roles/schulcloud-server-init/templates/configmap_file_init_idm.yml.j2
  ansible/roles/schulcloud-server-init/templates/job_init_idm.yml.j2
  apps/server/README.md
  apps/server/src/console/console.module.ts
  apps/server/src/console/test/identity-management.console.e2e-spec.ts
  apps/server/src/keycloak-user.spec.ts
  apps/server/src/modules/management/management.module.ts
  apps/server/src/shared/infra/identity-management/identity-management.module.spec.ts
  apps/server/src/shared/infra/identity-management/identity-management.module.ts
  apps/server/src/shared/infra/identity-management/identity-management.service.ts
  apps/server/src/shared/infra/identity-management/index.ts
  apps/server/src/shared/infra/identity-management/keycloak/console/keycloak-management.console.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/console/keycloak-management.console.ts
  apps/server/src/shared/infra/identity-management/keycloak/controller/keycloak-management.controller.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/controller/keycloak-management.controller.ts
  apps/server/src/shared/infra/identity-management/keycloak/interface/index.ts
  apps/server/src/shared/infra/identity-management/keycloak/interface/json-account.interface.ts
  apps/server/src/shared/infra/identity-management/keycloak/interface/json-user.interface.ts
  apps/server/src/shared/infra/identity-management/keycloak/interface/keycloak-management-input-files.interface.ts
  apps/server/src/shared/infra/identity-management/keycloak/interface/keycloak-settings.interface.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak-administration.service.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak-administration.service.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak-config.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak-identity-management.service.integration.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak-identity-management.service.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak-identity-management.service.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak.module.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/keycloak.module.ts
  apps/server/src/shared/infra/identity-management/keycloak/uc/Keycloak-management.uc.spec.ts
  apps/server/src/shared/infra/identity-management/keycloak/uc/Keycloak-management.uc.ts
  backup/keycloak/dBildungscloud-realm.json
  backup/keycloak/dBildungscloud-users-0.json
  backup/keycloak/master-users-0.json
  config/default.schema.json
  config/development.json
  config/test.json
  package.json
Labels: waiting for review
